### ISSUE TITLE
Game freeze: Patient tries to visit Psychiatry after GP office visit and get stuck at the door

### ISSUE THREAD

**Issue by ghost** [CorsixTH/CorsixTH#1063] opened 2016-05-01 14:06 UTC
#### Describe the issue

A Patient goes to a GP office and tries to visit the Psychiatry. The game freezes and the patient get stuck at the door of the office.
#### Steps to Reproduce
1. _Load save game attached to this ticket_
2. _wait and watch the new visitors_
#### Save Game

[gpgp.sav.zip](https://github.com/CorsixTH/CorsixTH/files/244147/gpgp.sav.zip)
#### Expected Behavior

no freeze
#### System Information

**CorsixTH Version:** f47ed4a5babd49459a60911cabd82444c6dcd476

**Operating System:** Debian 8 64bit 

**Theme Hospital Version:** CD
#### Gamelog.txt

```
Savegame version is 111 (v0.60-beta2), originally it was 108 (v0.60-beta2)
An error has occurred!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The timer handler.
A stack trace is included below, and the handler has been disconnected.
./Lua/world.lua:1615: bad argument #4 to 'findPath' (number expected, got nil)
stack traceback:
    [C]: in function 'findPath'
    ./Lua/world.lua:1615: in function 'getPath'
    ./Lua/humanoid_actions/walk.lua:373: in function '?'
    ./Lua/entities/humanoid.lua:580: in function 'Humanoid_startAction'
    ./Lua/entities/humanoid.lua:672: in function 'finishAction'
    ./Lua/humanoid_actions/walk.lua:152: in function <./Lua/humanoid_actions/walk.lua:137>
    (tail call): ?
    ./Lua/entity.lua:219: in function 'tick'
    ./Lua/world.lua:1059: in function 'onTick'
    ./Lua/app.lua:1000: in function <./Lua/app.lua:997>
    (tail call): ?
    ./Lua/app.lua:901: in function <./Lua/app.lua:896>

Error in timer handler: 
./Lua/world.lua:1615: bad argument #4 to 'findPath' (number expected, got nil)
stack traceback:
    [C]: in function 'findPath'
    ./Lua/world.lua:1615: in function 'getPath'
    ./Lua/humanoid_actions/walk.lua:373: in function '?'
    ./Lua/entities/humanoid.lua:580: in function 'Humanoid_startAction'
    ./Lua/entities/humanoid.lua:672: in function 'finishAction'
    ./Lua/humanoid_actions/walk.lua:152: in function <./Lua/humanoid_actions/walk.lua:137>
    (tail call): ?
    ./Lua/entity.lua:219: in function 'tick'
    ./Lua/world.lua:1059: in function 'onTick'
    ./Lua/app.lua:1000: in function <./Lua/app.lua:997>
    (tail call): ?
    ./Lua/app.lua:901: in function <./Lua/app.lua:896>
Warning: No event handler for timer
```

**Comment by Alberth289346** [comment] 2016-05-01 18:54
GP is visited after reception, and after each diagnosis room, so it's quite normal to visit the gp more than once.

It crashes with the patient at the psych room, for me. The patient enters and then crashes. I tried taking some furniture out of the way to try determining the cause, but didn't have much luck with it.

**Comment by TheCycoONE** [comment] 2016-05-02 01:38
I agree with @Alberth289346 the crash is definitely triggered when the patient enters the door of the psych room (the doctor has been at the book shelf in all my trials). Confirmed that the crash happens regardless of the screen position.

I didn't discover any useful information about which value is nil or why yet.

**Comment by Alberth289346** [comment] 2016-05-02 17:26
Trying to find an old good version failed. I went back until commit 94e1680 (dec 15, 2015), which updates the savegame number to 108, the number of the attached game. I could reproduce it there.
The bug is thus older from before dec 15, 2015.

Before that mostly fails with an error on finding the reception desk or failing on a build room callback (which got removed in savegame version 108), but I also had one case where the gp office door crashed instead of the psych room door, so it's not purely the psych room door.

**Comment by TheCycoONE** [comment] 2016-05-03 00:09
It's the patient that's crashing. For some reason action does not have an x or a y, in fact the only property it has is name="walk".

**Comment by TheCycoONE** [comment] 2016-05-03 00:33
Here is the stack trace where the bad action gets added to the action queue.

```
        ...rsixTH\Debug\..\..\..\CorsixTH\Lua\entities\humanoid.lua:737: in method 'walkTo'
        ...015\CorsixTH\Debug\..\..\..\CorsixTH\Lua\rooms\psych.lua:87: in method 'commandEnteringPatient'
        ...s_x64_2015\CorsixTH\Debug\..\..\..\CorsixTH\Lua\room.lua:400: in method  'onHumanoidEnter'
        ...TH\Debug\..\..\..\CorsixTH\Lua\humanoid_actions\walk.lua:356: in field 'on_next_tile_set'
        ...TH\Debug\..\..\..\CorsixTH\Lua\humanoid_actions\walk.lua:150: in function <...TH\Debug\..\..\..\CorsixTH\Lua\humanoid_actions\walk.lua:137>
        (...tail calls...)
        ...x64_2015\CorsixTH\Debug\..\..\..\CorsixTH\Lua\entity.lua:219: in method 'tick'
        ..._x64_2015\CorsixTH\Debug\..\..\..\CorsixTH\Lua\world.lua:1059: in method 'onTick'
        ...ps_x64_2015\CorsixTH\Debug\..\..\..\CorsixTH\Lua\app.lua:1000: in function <...ps_x64_2015\CorsixTH\Debug\..\..\..\CorsixTH\Lua\app.lua:997>
        (...tail calls...)
        ...ps_x64_2015\CorsixTH\Debug\..\..\..\CorsixTH\Lua\app.lua:901: in function <...ps_x64_2015\CorsixTH\Debug\..\..\..\CorsixTH\Lua\app.lua:896>
```

**Comment by TheCycoONE** [comment] 2016-05-03 00:37
It's because findObjectNear(patient, "couch") is returning nil. Moving the couch prevents the crash. I think this is a path finding bug because the couch doesn't look blocked (the radiator shouldn't prevent access)

**Comment by MarkL1961** [comment] 2016-05-03 18:01
In my testing I had moved the couch to the middle, removed radiators, separated couch bookcase screen and chair so there was space around them all and still got a crash each time.  The only time it did not crash for me was knocking the room down and building it some where else.
Could the path finding issue be location specific?

**Comment by TheCycoONE** [comment] 2016-05-03 18:20
Curious, I didn't get the crash when I moved the couch to the middle, as I mentioned above. I will be putting an assert in walkTo for the next version so that we can see where these errors are coming from without all the debugging I've been doing.

**Comment by bobcanthelpyou** [comment] 2016-05-05 11:21
I restarted the map with the latest version of CorsixTH and rebuild the psych room exactly like it was in the save game. And i couldn't reproduce a crash. Had a deeper look at the save game and i missed the benches in front of the psych room. I placed some benches in front of the room and hit the crash.

Does the path finding has problems when there is to much stuff on both sides of a door?

**Comment by TheCycoONE** [comment] 2016-05-06 00:51
Ok, so the issue isn't with the pathfinder, the problem is that the tile with the radiator is marked as not passable. It should be passable with can_travel_e = false;

**Comment by TheCycoONE** [comment] 2016-05-06 01:17
I made myself a debug overlay so I could see when the passable flag gets turned on / off, and it appears to be a problem with the couch itself. The tile in front of the top of the couch gets set to not passable when the couch is placed.

**Comment by TheCycoONE** [comment] 2016-05-06 02:18
Doing more testing, I see it's suppose to not be passable. The THOB for the couch is actually suppose to be in front of the top of the couch. When you put the radiator on the tile and save the game the couch THOB gets lost when you load the game again - so it's actually only possible to reproduce this bug by setting it up, saving, then loading the save.

**Comment by Alberth289346** [comment] 2016-05-06 09:45
Hacked the setCellFags to get some info on what happens at lua side: https://github.com/Alberth289346/CorsixTH/tree/debug_setcellflags
(Where 67,73 is in front of the couch, as far as I can tell.)

That gives
```` text
thob	18

stack traceback:
	../Lua/map.lua:590: in method 'setCellFlags'
	../Lua/entities/object.lua:685: in method 'resetAnimation'
	../Lua/world.lua:2317: in method 'resetAnimations'
	../Lua/persistance.lua:280: in function 'LoadGame'
	../Lua/persistance.lua:292: in function 'LoadGameFile'
	(...tail calls...)
	[C]: in function 'pcall'
	../Lua/dialogs/resizables/file_browsers/load_game.lua:41: in method 'choiceMade'
	../Lua/dialogs/resizables/file_browser.lua:206: in field 'select_callback'
	../Lua/dialogs/tree_ctrl.lua:621: in method 'onMouseUp'
	../Lua/window.lua:1462: in method 'onMouseUp'
	../Lua/window.lua:1462: in field 'onMouseUp'
	../Lua/ui.lua:649: in function <../Lua/ui.lua:636>
	(...tail calls...)
	../Lua/app.lua:901: in function <../Lua/app.lua:896>


thob	44

stack traceback:
	../Lua/map.lua:590: in method 'setCellFlags'
	../Lua/entities/object.lua:685: in method 'resetAnimation'
	../Lua/world.lua:2317: in method 'resetAnimations'
	../Lua/persistance.lua:280: in function 'LoadGame'
	../Lua/persistance.lua:292: in function 'LoadGameFile'
	(...tail calls...)
	[C]: in function 'pcall'
	../Lua/dialogs/resizables/file_browsers/load_game.lua:41: in method 'choiceMade'
	../Lua/dialogs/resizables/file_browser.lua:206: in field 'select_callback'
	../Lua/dialogs/tree_ctrl.lua:621: in method 'onMouseUp'
	../Lua/window.lua:1462: in method 'onMouseUp'
	../Lua/window.lua:1462: in field 'onMouseUp'
	../Lua/ui.lua:649: in function <../Lua/ui.lua:636>
	(...tail calls...)
	../Lua/app.lua:901: in function <../Lua/app.lua:896>
````
with 18 = 0x12, and 44 = 0x2C

**Comment by TheCycoONE** [comment] 2016-05-06 11:38
@Alberth289346 the problem as I said only happens when you load the map after it's saved. When it sets the cell flags it makes a two element list, but after load only the radiator is in that cell. I have confirmed this:
* make psych room with couch facing to the south
* add a radiator in front of the couch on the east side (where the couch thob is)
* dumping the object list for that node from c++ => {18, 44}
* save
* exit
* load
* dump the object list again for the same node. => {44}

The question is - what happened to the couch?

**Comment by Alberth289346** [comment] 2016-05-06 13:14
That gets recomputed in Lua, I found out in resetAnimations: https://github.com/CorsixTH/CorsixTH/blob/master/CorsixTH/Lua/world.lua#L2313

**Closed** 2016-05-06 19:29 UTC
Labels: P1 Critical, S:Accepted, S:Investigating
