### ISSUE TITLE
[Bug] Game crashes

### ISSUE THREAD

**Issue by fjthrowaway** [CorsixTH/CorsixTH#2176] opened 2022-05-27 13:37 UTC
### Describe the issue

Game crashes every time at the end of April 10

### Steps to Reproduce

1. *Load save game attached to this ticket*

2. Wait a day for the game to crash

### Expected Behaviour

Don't crash :)

### Save Game

Save game attached to report: Yes
[crash.zip](https://github.com/CorsixTH/CorsixTH/files/8786988/crash.zip)

### CorsixTH Version

v0.66-beta1

### Operating System

Arch Linux

### Theme Hospital Version

CD

### Gamelog.txt

```bash
Savegame version is 170 (v0.66-beta1), originally it was 170 (v0.66-beta1).
Error in timer handler: 
/usr/share/corsix-th/Lua/hospital.lua:867: attempt to index a nil value (field 'hospital')
stack traceback:
	/usr/share/corsix-th/Lua/hospital.lua:867: in method '_fixBoiler'
	/usr/share/corsix-th/Lua/hospital.lua:937: in field 'onEndDay'
	/usr/share/corsix-th/Lua/hospitals/player_hospital.lua:482: in method 'onEndDay'
	/usr/share/corsix-th/Lua/world.lua:1046: in method 'onTick'
	/usr/share/corsix-th/Lua/app.lua:1130: in function </usr/share/corsix-th/Lua/app.lua:1127>
	(...tail calls...)
	/usr/share/corsix-th/Lua/app.lua:1030: in function </usr/share/corsix-th/Lua/app.lua:1025>
```

**Comment by lewri** [comment] 2022-05-27 13:58
This one is a duplicate of #2173 , has been fixed for Beta-2 :)

**Closed by lewri** 2022-05-27 13:58 UTC
Labels: bug
