### ISSUE TITLE
Benches placeable in front of doors

### ISSUE THREAD

**Issue by voodoo-burger** [CorsixTH/CorsixTH#1083] opened 2016-06-01 15:38 UTC
#### Describe the issue
On my custom map/level I am able to place benches in front of most doors, causing patients inside to trigger the "empty action queue" error once their treatment finishes. The benches will be used by queuing patients like normal. I wasn't immediately able to reproduce this on a campaign map.

![benches](https://cloud.githubusercontent.com/assets/11193663/15715644/86841880-281f-11e6-9690-798a2caa9ccc.png)

Savegame: https://drive.google.com/open?id=0B1z_KXLTgDplS2V3c3RhaExjb2s
Level: https://drive.google.com/open?id=0B1z_KXLTgDplUmxab3R1MEw2dFE
Map: https://drive.google.com/open?id=0B1z_KXLTgDplcm5vMnpKQ3ZkQ1k

#### Expected Behavior
I shouldn't be able to build benches in front of doors.

#### System Information
CorsixTH 0.60 on Windows 10.

**Comment by TheCycoONE** [comment] 2016-06-01 15:50
Duplicate of #221

**Closed by TheCycoONE** 2016-06-01 15:50 UTC
