### ISSUE TITLE
Game started crashing every ~2 min or so (segfault) on CorsixTH version 0.5

### ISSUE THREAD

**Issue by tonihele** [CorsixTH/CorsixTH#893] opened 2015-09-06 08:22 UTC
Game started crashing every ~2 min or so (segfault). Happens every time for me with this save. The level has been restarted on 0.5. No need to do anything in particular, just let it run for few minutes. And you can even save before the crash again, to get always ~2min further in the game. So I don't know what triggers it. The game didn't write any log.

The save file:
https://www.dropbox.com/s/89ohn10b0ielu7a/Kaljis2.sav?dl=0

Using GetDeb version of 0.5 on Kubuntu 15.04.

**Comment by Alberth289346** [comment] 2015-09-06 14:55
It does not crash for me, but it does loose at some point (further away than 2 minutes).
Also, the game doesn't have a reception desk, probably avoiding the health inspector to give a fine :)

To eliminate lack of a reception desk as cause, could you try to add a reception desk, and see if it still crashes? (I expect it will, but that means at least the reception desk is not causing the troubles.)

Since you can save and continue from the previous game, it may not have to do with the game itself, but eg with sound or movies, or so. Did you try disabling music or sounds?

**Comment by tonihele** [comment] 2015-09-06 15:19
Yeah, I'm glad the same cheat works in your reimplementation :) Quite a tough level. It's not the reception desk that is causing it.

I can try to play it in Windows as well. As well as try disabling the music & sounds. @TheCycoONE suspected LUA as the cause.

**Comment by TheCycoONE** [comment] 2015-09-07 01:35
Yes I do, the playdeb people decided to use lua 5.1. I don't know how to get in contact with them and tell them to change that, but if you could remove luajit from your system - that might fix it. If it does let us know please.

**Comment by tonihele** [comment] 2015-09-07 05:48
I'll try when I get home. To contact them, you/we need to file a issue to the launchpad. I have credentials somewhere at least, so ultimately I can be a middle man:
https://bugs.launchpad.net/getdeb.net/

**Comment by tonihele** [comment] 2015-09-07 16:52
I removed the luajit, added reception desk. Still segfaults. The window says indeed that opengl,Lua 5.1, 64-bit. Could it be the LUA version?

**Comment by tonihele** [comment] 2015-09-07 16:56
I do seem to have Lua 5.2 installed as well, but CorsixTH doesn't use it apparently. I don't know how these get linked. Just FYI.

**Comment by MarkL1961** [comment] 2015-09-07 19:19
I don't know whether this is relevant and if it's what is causing you a problem, but a few years back I had issues when we added the check for updates.  It turned out that in the past when I installed lua on my system. I had defined its path to windows.  Even though I  had since removed that lua, this path was still being used by windows and that was causing me the problem.   To define the path it was something like right click on mycomputer, then there was a button where had to enter the path to lua.   If you did something similar for luajit when you installed it, then perhaps this path is still in your system somewhere and is over riding what the game looks for?

**Comment by TheCycoONE** [comment] 2015-09-07 21:00
CorsixTH built against lua 5.1 will not find lua 5.2.

If you're willing or able to compile yourself (it actually isn't very hard in Ubuntu) we could walk you through it. Then we can see if the problem goes away, or if not - run a debugger and find where the problem is.

**Comment by tonihele** [comment] 2015-09-08 06:39
I can try. I think I still have it configured in KDevelop. Not sure if it points to Google code, shouldn't be too hard to change it. But help I need most likely, I'm a JAVA developer, it has been 10 years since I last touched C stuff.

**Comment by tonihele** [comment] 2015-09-09 19:39
Ok, I compiled it. Master version. I was unable to switch to 0.5 release. The window still said that  opengl,Lua 5.1, 64-bit. I do have LUA 5.2 dev installed. So I don't know what this is going to prove, but, IT WORKS :)

**Comment by TheCycoONE** [comment] 2015-09-15 01:39
Alright, well I guess all we can conclude is that there's something wrong with the playdeb package. If it still segfaulted we could have maybe seen why. Do you know if there's any way to report it to them?

**Comment by wolfy1339** [comment] 2015-09-15 02:20
I beleive it's [here](https://bugs.launchpad.net/playdeb) that you report bugs

**Comment by tonihele** [comment] 2015-09-15 05:26
I already went ahead, the impatient man I am....
https://bugs.launchpad.net/getdeb.net/+bug/1494587

**Comment by tonihele** [comment] 2015-09-24 19:37
Sadly it didn't solve the problem. The GetDeb version reads LUA 5.2, but it still crashes.

**Comment by TheCycoONE** [comment] 2015-09-24 19:42
Agreed, could you use ```ldd``` to determine what if any differences exist between the libraries used by your compile vs the ones used by playdeb?

**Comment by tonihele** [comment] 2015-09-30 17:51
Hmm, no difference :(  Except I have liblua5.1.so.0 and the GetDeb now has 5.2.

**Comment by TheCycoONE** [comment] 2015-09-30 20:04
Well now I'm running out of ideas. I guess you are not using the exact same code version, so you could ```git checkout v0.50``` to verify.

**Comment by tonihele** [comment] 2015-09-30 20:06
Yes. I have few commits over the tagged release. Ill try to identify what
fixed it then

**Comment by Lego3** [comment] 2015-11-28 14:55
Any news on this issue?

**Comment by tonihele** [comment] 2015-11-28 15:17
No news. I haven't had the time to test it. Ill try to test it in December
(this year :) ).

**Comment by tonihele** [comment] 2016-06-04 09:07
Happens with 0.6 GetDeb version & Kubuntu 16.04... :(

**Comment by TheCycoONE** [comment] 2018-09-21 11:14
@tonihele anything to add from more recent experience?

**Comment by lewri** [comment] 2020-08-17 17:39
I will close this due to age. @tonihele please get back in touch if the problem still happens in 0.64. I'm suspecting GetDeb is at fault but looks like the platform has since been retired.

**Closed by lewri** 2020-08-17 17:39 UTC
