### ISSUE TITLE
Cannot edit or move Operating Theatre room

### ISSUE THREAD

**Issue by aneurysm1985** [CorsixTH/CorsixTH#708] opened 2015-02-28 11:22 UTC
I have a hospital with an Operating Theatre that I want to relocate/delete.

I tried using the 'Edit room/items' tool on this room, but I cannot backtrack any further than the 'move items around the room stage. I cannot go back to the 'blueprint' of the room. 

Once I am in the 'move items around the room' stage, I can no longer place my items anywhere else in the room'. I am stuck with the item permanently selected, and can do nothing more than terminate CorsixTH via my System Monitor within Linux.

I have tried relocating/deleting a Ward within my hospital, and that works OK. So maybe it is just the Operating Theatre that is misbehaving.

I am using the Linux client, which I compiled today.

Here is the gamelog from after the software failure. https://dl.dropboxusercontent.com/u/10133825/CorsixTH%20-%20github/gamelog-operating-theatre-linux.txt
Also, here is a save file from immediately before the failure, in case you want to try reproducing this error yourself. https://dl.dropboxusercontent.com/u/10133825/CorsixTH%20-%20github/Autosave2-operating-theatre-linux.sav

**Comment by SimplyRyan** [comment] 2015-03-01 13:12
Adding the text to the issue to preserve it and allow searching for similar problems across all issues.


Created game with savegame version 101.
Warning: Trying to remove nonexistant room build callback (function: 0xa49c3848) from humanoid (table: 0x983adb60).
Warning: Trying to remove nonexistant room remove callback (function: 0xa49c3798) from humanoid (table: 0x983adb60).
Savegame version is 101 (Trunk), originally it was 101 (Trunk)
Warning: Trying to remove nonexistant room build callback (function: 0xaabbdf58) from humanoid (table: 0xaac5ede8).
Warning: Trying to remove nonexistant room remove callback (function: 0xaa8df088) from humanoid (table: 0xaac5ede8).
Warning: Trying to remove nonexistant room build callback (function: 0xab3dbcf8) from humanoid (table: 0xaabba8d8).
Warning: Trying to remove nonexistant room remove callback (function: 0xaac42990) from humanoid (table: 0xaabba8d8).
Warning: Trying to remove nonexistant room build callback (function: 0xaa187fa8) from humanoid (table: 0xaa868ce8).
Warning: Trying to remove nonexistant room remove callback (function: 0xaa187f68) from humanoid (table: 0xaa868ce8).
Warning: Trying to remove nonexistant room build callback (function: 0xaaa02ca0) from humanoid (table: 0xaac52af0).
Warning: Trying to remove nonexistant room remove callback (function: 0xa6cc1f38) from humanoid (table: 0xaac52af0).
Warning: Trying to remove nonexistant room build callback (function: 0xa5f7b198) from humanoid (table: 0xaac8cbf8).
Warning: Trying to remove nonexistant room remove callback (function: 0xa5f7b158) from humanoid (table: 0xaac8cbf8).
Warning: Trying to remove nonexistant room build callback (function: 0xa5f806a8) from humanoid (table: 0xa4fc3e50).
Warning: Trying to remove nonexistant room remove callback (function: 0xa5f80768) from humanoid (table: 0xa4fc3e50).
Warning: Trying to remove nonexistant room build callback (function: 0xab408558) from humanoid (table: 0xab3fc700).
Warning: Trying to remove nonexistant room remove callback (function: 0xa4331930) from humanoid (table: 0xab3fc700).
Savegame version is 101 (Trunk), originally it was 101 (Trunk)
Error in buttonup handler: 
...le/Games/CorsixTH/CorsixTH/Lua/dialogs/place_objects.lua:230: attempt to index field 'orientations' (a nil value)
stack traceback:
	...le/Games/CorsixTH/CorsixTH/Lua/dialogs/place_objects.lua: in function <...le/Games/CorsixTH/CorsixTH/Lua/dialogs/place_objects.lua:229>
	[C]: in function 'sort'
	...le/Games/CorsixTH/CorsixTH/Lua/dialogs/place_objects.lua:229: in function 'addObjects'
	...uirtle/Games/CorsixTH/CorsixTH/Lua/dialogs/edit_room.lua:606: in function 'returnToDoorPhase'
	...uirtle/Games/CorsixTH/CorsixTH/Lua/dialogs/edit_room.lua:190: in function 'callback'
	/home/squirtle/Games/CorsixTH/CorsixTH/Lua/window.lua:664: in function 'handleClick'
	/home/squirtle/Games/CorsixTH/CorsixTH/Lua/window.lua:1439: in function 'onMouseUp'
	...le/Games/CorsixTH/CorsixTH/Lua/dialogs/place_objects.lua:452: in function 'onMouseUp'
	/home/squirtle/Games/CorsixTH/CorsixTH/Lua/window.lua:1423: in function 'onMouseUp'
	/home/squirtle/Games/CorsixTH/CorsixTH/Lua/ui.lua:622: in function 'dispatch'
	/home/squirtle/Games/CorsixTH/CorsixTH/Lua/app.lua:768: in function </home/squirtle/Games/CorsixTH/CorsixTH/Lua/app.lua:763>

**Comment by Alberth289346** [comment] 2015-06-28 19:45
![vomit](https://cloud.githubusercontent.com/assets/3254232/8397960/3e26f932-1dde-11e5-95f6-d5915c3d322e.png)

As the picture shows, there is vomit inside the operating theatre. When you press 'edit', this gets added to the inventory of objects of the room.
However, since vomit is not a proper room object, the sorter crashes on deciding its size.

**Comment by J-Shep** [comment] 2015-06-28 20:53
This error was also reported in October 2013 : #66

**Comment by J-Shep** [comment] 2015-06-28 21:24
I will close this issue because it a duplicate of #66.

**Comment by MarkL1961** [comment] 2015-06-29 10:17
@Alberth289346   In theory it should not be possible to drop litter or be sick in a room.  So I wonder does it happen through the wall from a patient walking past?

**Comment by J-Shep** [comment] 2015-06-30 21:19
@MarkL1961 In #66 @mrtnptrs mentions that there is a way: if a patient vomits in the room's blueprint just before the confirm button is pressed because the vomit check must only be occurring once when a blueprint has been moved/resized. 

I think the solution to this problem should be to just immediately cancel walk actions which would make a patient enter a blueprint because these action were created before it was made/resized/moved.

**Comment by J-Shep** [comment] 2015-06-30 21:20
But @mrtnptrs reported this in October 2013 so maybe this has been fixed already but #66 wasn't closed.

**Comment by J-Shep** [comment] 2015-06-30 21:23
>> I think the solution to this problem should be to just immediately cancel walk actions which would make a patient enter a blueprint because these action were created before it was made/resized/moved.

The vomit action would also need to have a check to makesure a patient standing on the edge of a blueprint doesn't vomit into it.

**Comment by Alberth289346** [comment] 2015-07-01 04:46
That would mean your patch should be sufficient to prevent this problem for happening in the future.

In the mean time, I have been trying to drop the litter from the object list, but I am missing something as the program locks up whenever I try that.

**Closed** 2015-07-13 01:32 UTC
