### ISSUE TITLE
Infinite loop in entity_map.lua

### ISSUE THREAD

**Issue by Burningfeetman** [CorsixTH/CorsixTH#1094] opened 2016-06-18 09:09 UTC
[Autosave9.zip](https://github.com/CorsixTH/CorsixTH/files/321665/Autosave9.zip)

Reproducable crash on level 1 - Version 0.6
1. Open the zip file, rename the file extension of Autosave9 back to .sav, then load saved game as per normal.
   [Autosaves.zip](https://github.com/CorsixTH/CorsixTH/files/321666/Autosaves.zip)
2. Wait about 10 seconds.
3. The game should freeze, forcing the user to alt-tab to desktop.

Note: Some crazy pants business was noticed with the "Bloaty head" patient moon-walking through rooms, and triggering his cure noises before being treated. 

CorsixTH Version: 0.60
Windows 7 x64
Theme Hospital Version:GOG.com

**Comment by TheCycoONE** [comment] 2016-06-18 23:23
Was there any output in your gamelog.txt?

**Comment by Burningfeetman** [comment] 2016-06-19 09:06
Howdy TheCycoONE, 

Where is the gamelog.txt located? I had a look within the install directory and under appdata, but couldn't find a gamelog.txt file.

**Comment by Grimdoc** [comment] 2016-06-19 09:49
It should be located in the same folder as config.txt. On windows 7 it is
located in C:\Users\<Your username>\AppData\Roaming\CorsixTH
But if there haven't been any errors, I don't think it is created.

**Comment by Burningfeetman** [comment] 2016-06-19 11:03
I see. The crash is a freeze crash as such, after seeing some wonky business with a floaty head patient. I don't believe the file has been created. Does the save game file crash for you?

**Comment by Alberth289346** [comment] 2016-06-19 13:44
Upon loading in master, the game opens and scrolls to the right. By clicking, it stops scrolling.
The advisor is shown, but no message from it.

No messages at the console other than savegame version 111 is used.

The game does not respond to ^C, I have to force-kill (kill -9) it.

**Comment by lewri** [comment] 2016-06-20 10:03
I managed to pull the following from turning on debug:

>Created game with savegame version 111.
Warning: Trying to remove nonexistant room build callback (function: 000000001A1D9C90) from humanoid (table: 000000001A69FC00).
Warning: Trying to remove nonexistant room remove callback (function: 0000000019106FE0) from humanoid (table: 000000001A69FC00).
Warning: Trying to remove nonexistant room build callback (function: 0000000011C4DE80) from humanoid (table: 000000001AC0B8F0).
Warning: Trying to remove nonexistant room remove callback (function: 0000000018B501F0) from humanoid (table: 000000001AC0B8F0).
Savegame version is 111 (v0.60), originally it was 111 (v0.60)


This was just before the freeze. Where the game breaks looks like it fails just because the doctor is waiting for the patient to arrive (the waiting emoticon should appear)


I managed to get the console up while the game crashed. See errors below.
![screenshot 2016-06-20 11 00 12](https://cloud.githubusercontent.com/assets/20030128/16190335/9aad1896-36d6-11e6-821d-ae100ec25fe8.png)

Error loops

> Error in timer handler: 
C:\Program Files\CorsixTH\Lua\entity_map.lua:72: Suspected infinite loop
stack traceback:
	[C]: in function 'error'
	C:\Program Files\CorsixTH\Lua\app.lua:919: in hook '?'
	C:\Program Files\CorsixTH\Lua\entity_map.lua:72: in local 'remove_entity_from_table'
	C:\Program Files\CorsixTH\Lua\entity_map.lua:88: in method 'removeEntity'
	C:\Program Files\CorsixTH\Lua\entity.lua:119: in method 'setTile'
	C:\Program Files\CorsixTH\Lua\entity.lua:174: in method 'setTilePositionSpeed'
	C:\Program Files\CorsixTH\Lua\humanoid_actions\walk.lua:176: in function <C:\Program Files\CorsixTH\Lua\humanoid_actions\walk.lua:137>
	(...tail calls...)
	C:\Program Files\CorsixTH\Lua\entity.lua:219: in field 'tick'
	C:\Program Files\CorsixTH\Lua\entities\staff.lua:149: in method 'tick'
	C:\Program Files\CorsixTH\Lua\world.lua:1075: in method 'onTick'
	C:\Program Files\CorsixTH\Lua\app.lua:1000: in function <C:\Program Files\CorsixTH\Lua\app.lua:997>
	(...tail calls...)
	C:\Program Files\CorsixTH\Lua\app.lua:901: in function <C:\Program Files\CorsixTH\Lua\app.lua:896>

**Comment by TheCycoONE** [comment] 2016-06-20 11:02
Stack trace is consistent with what I was seeing. Cell flags were being fetched over and over.

**Comment by Alberth289346** [comment] 2016-06-20 17:18
```` diff
--- a/CorsixTH/Lua/humanoid_actions/walk.lua
+++ b/CorsixTH/Lua/humanoid_actions/walk.lua
@@ -142,6 +142,7 @@ local action_walk_tick; action_walk_tick = permanent"action_walk_tick"( 
function
   local check_doors = not not humanoid.door_anims
   local x1, y1 = path_x[path_index  ], path_y[path_index  ]
   local x2, y2 = path_x[path_index+1], path_y[path_index+1]
+  print("xy1=("..(x1 or "nil")..", "..(y1 or "nil").."), xy2=("..(x2 or "nil")..", ".
.(y2 or "nil")..")")
 
   if not x2 then
     -- Arrival at final tile
````
Added a debug line in walk.lua, and it endlessly prints

```` text
xy1=(86, 68), xy2=(86, 69)
````

**Comment by mugmuggy** [comment] 2017-10-19 09:18
I've taken a look at the save and sometimes get some other scenarios happening but replicate the freeze. My experience generally has the Doctor enter and freeze when he attempts to 'meander' in the room. The Dr is given Walk action sending him to (86,70), outside the room. The Walk action path is something like (85,68),(86,68),(86,69),(86,70) which is straight through the wall. 

Checking the cellFlags for (86,68), shows that the cell is completely passable, travelSouth/East/West/North all true.  #1105 refers to walking through walls as well for a tile next to a door. I confirmed the issue in #1105 is also that the tile is passable when we expect travelWest to be false.

For this issue, placing a radiator against the wall for example updates the travelSouth and prevents the crash from occuring, remove it again and its entirely possible to have the issue occur again. The Dr will meander out of the room after treating patient and then back in (not sure why), and if you remove the radiator at this point it probably will freeze again. Unsure of what circumstances can lead to this state.

**Comment by TheCycoONE** [comment] 2017-10-20 10:51
Great find @mugmuggy 

For both this issue, and your door PR it would be helpful to have a routine that recalculated expected cell flags, then we could repair saves and automate detection.

**Comment by mugmuggy** [comment] 2017-10-21 13:49
I have knocked together a routine that handles this type of scenario and added it to the Room class, which I called from afterLoad, like a generic 'fixer', alas afterLoad isn't called if the savegame version is the same, though we don't have an identified cause of the glitch.

The Door PR I believe you mean that scenario around the bench which would have the old footprint from the previous save (as these are persisted) and not the 'new' instance. Adding an afterLoad routine there to bring it up to date with the new footprint works too.

**Comment by TheCycoONE** [comment] 2017-10-22 00:42
@mugmuggy Right about the bench thing. That is all that is blocking that PR, if you could bump the version and put an afterload there.

For this, I was speculating outside of the version condition and make it noisy, like:
`WARNING: Correcting corrupt map tile at [X,Y]. Flag xxxxxxxx is on, should be off.`
For every such issue.

It should be clearly labeled in code as a hack, until we find the cause.

**Comment by TheCycoONE** [comment] 2017-10-24 20:16
Duplicate of #1105

**Closed by TheCycoONE** 2017-10-24 20:16 UTC
Labels: Priority-Critical, State-Accepted
