### ISSUE TITLE
game is stuck on pause after i load my save game

### ISSUE THREAD

**Issue by overlordchaos** [CorsixTH/CorsixTH#1299] opened 2017-12-02 19:28 UTC
#### Describe the issue
once i load my game, an error occurs on the cmd window and the hospital its on permanent pause.
no matter what speed i set its paused.
#### Steps to Reproduce
1. *Load save game and custom map attached to this ticket*

2.try to change game speeds

3.(just obserb)

#### Save Game
https://drive.google.com/open?id=1E2AvmTMVR0LTx0VzJXyOY0bw3lG9N_Ed
(add the custom level and map to corsixth\levels program files folder and the save as usual)
#### Expected Behavior
the game should run just fine.
#### System Information
**CorsixTH Version:** *e.g. 0.50 or 7d886f35ca*
0.61 RC 1
**Operating System:** *e.g. Windows 10*
win 10 x64
**Theme Hospital Version:** *CD, GOG.com, Origin, or Demo*
gog.com
#### Gamelog.txt
(CMD window)
Warning: Failed to read custom graphics configuration:
C:\Program Files\CorsixTH\Graphics\file_mapping.txt: No such file or directory
Checking for CorsixTH updates...
You are running the latest version of CorsixTH.
An error has occurred!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The timer handler.
A stack trace is included below, and the handler has been disconnected.
C:\Program Files\CorsixTH\Lua\game_ui.lua:698: attempt to index a nil value (field 'multigesturemove')
stack traceback:
        C:\Program Files\CorsixTH\Lua\game_ui.lua:698: in method 'onTick'
        C:\Program Files\CorsixTH\Lua\app.lua:1010: in function <C:\Program Files\CorsixTH\Lua\app.lua:1005>
        (...tail calls...)
        C:\Program Files\CorsixTH\Lua\app.lua:909: in function <C:\Program Files\CorsixTH\Lua\app.lua:904>

Warning: No event handler for timer

(gamelog.txt)
Created game with savegame version 119.
Savegame version is 119 (v0.61-beta1), originally it was 119 (v0.61-beta1)
Warning: Trying to remove nonexistant room build callback (function: 00000172210C00E0) from humanoid (table: 000001722124ED70).
Warning: Trying to remove nonexistant room remove callback (function: 0000017224E21E50) from humanoid (table: 000001722124ED70).
Warning: Trying to remove nonexistant room build callback (function: 00000172210C5480) from humanoid (table: 00000171ADBBB6A0).
Warning: Trying to remove nonexistant room remove callback (function: 0000017219BA15B0) from humanoid (table: 00000171ADBBB6A0).
Savegame version is 119 (v0.61-beta1), originally it was 119 (v0.61-beta1)
Savegame version changed from 119 (v0.61-rc1) to 121 (v0.61-rc1). The save was created using 119 (v0.61-rc1)
Error in timer handler: 
C:\Program Files\CorsixTH\Lua\game_ui.lua:698: attempt to index a nil value (field 'multigesturemove')
stack traceback:
	C:\Program Files\CorsixTH\Lua\game_ui.lua:698: in method 'onTick'
	C:\Program Files\CorsixTH\Lua\app.lua:1010: in function <C:\Program Files\CorsixTH\Lua\app.lua:1005>
	(...tail calls...)
	C:\Program Files\CorsixTH\Lua\app.lua:909: in function <C:\Program Files\CorsixTH\Lua\app.lua:904>
Savegame version is 121 (v0.61-rc1), originally it was 119 (v0.61-rc1)
Error in timer handler: 
C:\Program Files\CorsixTH\Lua\game_ui.lua:698: attempt to index a nil value (field 'multigesturemove')
stack traceback:
	C:\Program Files\CorsixTH\Lua\game_ui.lua:698: in method 'onTick'
	C:\Program Files\CorsixTH\Lua\app.lua:1010: in function <C:\Program Files\CorsixTH\Lua\app.lua:1005>
	(...tail calls...)
	C:\Program Files\CorsixTH\Lua\app.lua:909: in function <C:\Program Files\CorsixTH\Lua\app.lua:904>

**Comment by TheCycoONE** [comment] 2017-12-02 22:38
Thanks for the report. Looks like a regression related to multigesture.

This is a release blocker.

**Comment by overlordchaos** [comment] 2017-12-02 23:37
yes. can you give me a link for the beta 6.1? cause i cannot play my mega hospital :(

**Comment by TheCycoONE** [comment] 2017-12-02 23:55
On the releases page.

**Comment by TheCycoONE** [comment] 2017-12-03 01:58
I see, the savegame version wasn't bumped properly, so the afterload condition that was suppose to enable multigesture didn't happen. This breaks compatibility with save games from the beta only; games from earlier (before savegame_version 118) should work fine.

@overlordchaos if you want to recover your save game, edit game_ui.lua, and change https://github.com/CorsixTH/CorsixTH/commit/b68864a6555826f6410e1055ad6f11d71bfb2597#diff-2941452853592df382d60ed7e9d6a3bcR1144 from `< 118` to `< 120`

**Comment by TheCycoONE** [comment] 2017-12-03 01:59
I will add a note to the release page.

**Comment by overlordchaos** [comment] 2017-12-03 04:30
@TheCycoONE bad news, did the change as you showed me and i got an error on the start menu. you need to do some sort of savbe game conversion if you ask me at least on the first load to "update" the save game up to newer releases. in the screenshot the error:
https://imgur.com/a/wBfNF

**Comment by TheCycoONE** [comment] 2017-12-03 13:53
We have a conversion, that's literally what I had you tweaking.

There is a small window of saves it doesn't handle between when mugmuggy wrote multigesture support and when I merged it which is entirely my fault.

I don't feel that correcting an issue that only affects beta 1 saves (0.60 saves convert fine) to be worth delaying the release another two weeks for.

Your second issue error I can't explain off hand. I'll take a look at your save over the next few days to see what is going on there.

**Comment by overlordchaos** [comment] 2017-12-03 16:35
@TheCycoONE i never meant to delay the release. just put a warning that beta 0.61 players MIGHT have a issue with the save files. if you can find an easy way to tweak the game (as you previously tried) and fix all the issues its fine by me. its just anyone using beta 0.61 will have this same issue as me probably.

**Comment by MarkL1961** [comment] 2017-12-03 17:06
When you are testing a beta you can expect this to happen sometimes, just delete the save and start over.

**Comment by overlordchaos** [comment] 2017-12-03 18:23
@MarkL1961 sorry but corsixTH IS on beta level. there is no release just yet, only RC. so if you tell me "well if you use a beta you know what to spect" sure but i dont have the option to go for the stable version.
anyways i never desire to delay the release. just find a solution to this issue OR in the worst case a warning that anyone uphrading from 061 beta to RC may lost all their save games.

**Closed** 2017-12-06 19:33 UTC
Labels: Component-UI, Priority-Critical, Type-Game Crash
