### ISSUE TITLE
Emergency's shouldn't happen when the disease has not been "found" yet, mouse freezes

### ISSUE THREAD

**Issue by dvanderfaeillie** [CorsixTH/CorsixTH#1190] opened 2017-01-05 22:48 UTC
#### Describe the issue
When starting a new hospital (level 8), I constructed an inflation room which allows the emergency "Bloaty head" to occur. However the disease was not yet diagnosed.

I accepted the emergency and wanted to open the casebook of a patient. The mouse somehow freezed, I could still move the mouse but was unable to click anything. I had to quit and reload the autosave. (and not open the casebook of those patients)

I guess the game 'crashes' because it wants to open something which cannot be opened yet. (Disease was not yet discovered).

#### Steps to Reproduce
See the above.

#### System Information
**CorsixTH Version:** CorsixTh *Trunk version*

**Operating System:** *Elementary OS Loki (Ubuntu 16.04)*

**Theme Hospital Version:** *Origin*

**Comment by TheCycoONE** [comment] 2017-01-06 13:33
Duplicate of #1156

**Closed by TheCycoONE** 2017-01-06 13:33 UTC
