### ISSUE TITLE
[Bug] Segfault unknown cause

### ISSUE THREAD

**Issue by squigley** [CorsixTH/CorsixTH#1769] opened 2020-12-26 04:38 UTC
#### Describe the issue

Was playing, was trying to place some benches, and then the whole thing crashed. Console shows a segfault:

`An error has occurred!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The timer handler.
A stack trace is included below, and the handler has been disconnected.
./Lua/room.lua:494: attempt to index field 'queue' (a nil value)
stack traceback:
	./Lua/room.lua:494: in function 'tryAdvanceQueue'
	./Lua/objects/doors/swing_door_right.lua:138: in function 'timer_function'
	./Lua/entity.lua:216: in function <./Lua/entity.lua:193>
	(...tail calls...)
	./Lua/world.lua:1051: in function 'onTick'
	./Lua/app.lua:1008: in function <./Lua/app.lua:1005>
	(...tail calls...)
	./Lua/app.lua:909: in function <./Lua/app.lua:904>

Warning: Proper idle not in action_queue
Segmentation fault
`

#### Steps to Reproduce
1. *Load save game attached to this ticket*

I have attached the most recent auto save

2. Try to place benches.

3. Game crashed.

#### Save Game
Attached. 
[save.zip](https://github.com/CorsixTH/CorsixTH/files/5742692/save.zip)

#### Expected Behaviour

Bench would place.

#### System Information
**CorsixTH Version: v0.61**

**Operating System: Linux Mint 19**

**Theme Hospital Version: GOG.com**

#### Gamelog.txt

Attached. [gamelog.txt](https://github.com/CorsixTH/CorsixTH/files/5742691/gamelog.txt)

**Comment by lewri** [comment] 2020-12-26 09:35
As you're running 0.61, and not the latest version (0.64) could you try again with that version for us?

**Comment by mugmuggy** [comment] 2020-12-27 01:22
The stack trace issue was fixed in 0.64, thats the tryAdvanceQueue error, the warning is just that, a warning and normally doesn't present a problem. They probably occured together when the crashed surgery crashed.

However we have no timeline on a seg fault occuring afterwards or what might be the cause, but it would look like there was a little bit of time between that and the seg fault occuring and a few fixes around potential seg faults have been fixed since 0.61.

**Comment by TheCycoONE** [comment] 2020-12-27 02:58
There have definitely been segfault fixes since 0.61 and no way to identify or fix this one without a core dump / back trace.

Closing for now. Please reopen if you are able to reproduce in the latest version. If you can reproduce with the latest version try getting a back trace of the segfault (see https://jvns.ca/blog/2018/04/28/debugging-a-segfault-on-linux/)

**Closed by TheCycoONE** 2020-12-27 02:58 UTC

**Comment by squigley** [comment] 2020-12-27 04:25
No problem, thanks all for looking into this. After I opened this ticket I realised I was able to restart the game and reload the most recent autosave, and when I tried to reproduce it, it worked fine..

I am updating to newer code. I am running Linux Mint 19 on my laptop which is why I had 0.61, since that's what's in their repo. I also had an issue trying to use innoextract which I opened a ticket about, and updating to a newer version was the resolution to that issue too :-)
