### ISSUE TITLE
Drug Effictiveness Failure - Back to GP's office instead of Death for ineffective cure

### ISSUE THREAD

**Issue by urbie** [CorsixTH/CorsixTH#295] opened 2014-08-14 10:31 UTC
In DOS version of TH I played, if the drug was not effective the patient paid a small fee for the attempted cure and is sent back to GP's office. Then after the visit back to the GP, the patient is resent for the cure until its successful.

**Comment by lewri** [comment] 2020-07-31 11:22
After checking through the original I couldn't reproduce this with a super low guess at cure rate. I think this mention in the guide might've been a possible mechanic but was dropped from the game -- but the guide wasn't updated. The "not cured" icon doesn't' even actually appear on dying patients in the original.

My thoughts were this kicks in when you use the manual "guess at cure" button in the patient info window and the cure fails. But alas it is not.

**Comment by Alberth289346** [comment] 2020-07-31 15:45
It seems like a bad game mechanics to me. If you don't have good drugs, all patients will go through the diagnosis-test-cure cycle several times (theoretically forever until they die).
Effectively, you thus get 2-5 times as many patients walking around in the hospital than the in-stream of new patients, ie the hospital will drown in patients and you have no way out with all the bad cure-results and inevitable long queues constantly hitting your reputation.
Under the defend-able simplification that you selected the best available cure the first time, what are you going to do a second time? Give the same drug again that didn't work the first time? Give a less good drug?

Last but not least, it's no fun getting the same patients over and over again (users will notice patients don't go home, and send bug reports!). It's simpler to just kill the patient on failure, and have a new patient coming in.

**Comment by lewri** [comment] 2020-08-01 15:06
Based on age of the request and the downsides of this enhancement pointed out by Alberth I'll close this one off.

**Closed by lewri** 2020-08-01 15:06 UTC
Labels: enhancement
