### ISSUE TITLE
[Bug] Parts of the hospital not reachable error blocks placing valid room

### ISSUE THREAD

**Issue by viviannastasa** [CorsixTH/CorsixTH#2320] opened 2023-04-18 16:35 UTC
### Describe the issue

Could not place a validly spaced and located room as it was stated that parts of the hospital wouldn't be reachable. 
Access to that part of the hospital was reachable via third entrance to the building and a corridor that was maybe too far from the new room's location in the building.
None of the adjacent rooms had entrances on the 'blocked' side. 

### Steps to Reproduce

1. *Load save game attached to this ticket*

2. Try to place a room as in attached screenshot
![corsixth_access_issue](https://user-images.githubusercontent.com/58228541/232843702-4ba233be-5ba3-4938-8e6f-c53b5c0f6c55.png)
3.Notice you cannot place it though it wouldn't block access.

### Expected Behaviour

The engine should account for the separate entrance and the available corridor, regardless of its distance from the new room.

### Save Game

Save game attached to report: Yes
[1.zip](https://github.com/CorsixTH/CorsixTH/files/11264135/1.zip)

### CorsixTH Version

0.66

### Operating System

Win10

### Theme Hospital Version

Origin

### Gamelog.txt

```bash
------------------------- CorsixTH configuration file -------------------------
~~~~Lewri: truncated~~~~

-------------------------------------------------------------------------------
-- If true, parts of the hospital can be made inaccessible by blocking the path
-- with rooms or objects. If false, all parts of the hospital must be kept
-- accessible, the game will disallow any attempt to blocking the path.
--
allow_blocking_off_areas = false

~~~Lewri: truncated~~~~
```

### Additional Information

I never encountered this behavior in the original version, so I'm assuming it's a CorsixTH issue.

**Comment by TheCycoONE** [comment] 2023-04-18 17:07
Duplicate of #826

**Comment by TheCycoONE** [comment] 2023-04-18 20:05
Informed this may not be a duplicate, though it's very hard to tell from the screenshot. We'll need to check the save to see if the bottom corridor is blocked.

**Comment by lewri** [comment] 2023-04-24 17:49
It's the bench next to the ward, it blocks the path even if it looks visibly passable.
![image](https://user-images.githubusercontent.com/20030128/234075905-4ca4debf-5105-4863-a4e1-14941715f8aa.png)

Have checked with a debug patient, they go around the long way.
![image](https://user-images.githubusercontent.com/20030128/234076268-c5575ebe-b72e-4f29-9f0f-767a8c8f91ec.png)

**Comment by lewri** [comment] 2023-04-25 13:01
Intended behaviour in original -- because a door becomes inaccessible with the blueprint. That bench is blocking.

![image](https://user-images.githubusercontent.com/20030128/234283971-c0c91685-e480-4edf-8976-9457c891a77c.png)

**Closed by lewri** 2023-04-25 13:01 UTC
