### ISSUE TITLE
Impossible to teach a GP level doctor to have a new skill

### ISSUE THREAD

**Issue by hans-void** [CorsixTH/CorsixTH#2262] opened 2022-10-01 17:50 UTC
### Describe the issue

When a GP-level doctor is teached by a specialist, for example with surgeon skill, the GP becomes a specialist before the new skill. Once having the specialist level, the doctor quits the teaching room.

### Steps to Reproduce

- Put specialist doctor with surgeon skill in teaching room
- Put GP-level doctor with no skill in teaching room
- Wait a bit
- GP level doctor becomes specialist and leaves the room, not being a surgeon

### Expected Behaviour

- It should be possible to get additional skills in the teaching room

### CorsixTH Version

0,66 
### Operating System

Windows 10

**Comment by SilPho** [comment] 2022-10-01 18:42
This was a problem I would often run into in the original game as well. CorsixTH does re-create the same behaviour (except that CorsixTH doesn't show the partial training percentage in the Staff Management screen after Consultant status is reached)

However, this does feel like a potential future enhancement option to allow Consultants to act as students for as long as they have an incomplete specialist skill.

**Comment by lewri** [comment] 2022-10-01 20:21
It's not that they can't get the skill. It's more than they don't progress enough in learning the skill by the time they reach consultant. This has come up before in #1458, which is still open.

However, I've taken a peek at the code and it's all very linear currently.
https://github.com/CorsixTH/CorsixTH/blob/3ebcbd64b7d4d3869d70da2f85ed6f81163dd313/CorsixTH/Lua/entities/humanoids/staff/doctor.lua#L58-L94
https://github.com/CorsixTH/CorsixTH/blob/3ebcbd64b7d4d3869d70da2f85ed6f81163dd313/CorsixTH/Lua/entities/humanoids/staff/doctor.lua#L185-L193

The fact the second function has `TODO`s is probably very telling that our implementation is unpolished. However, we could do with mugmuggy's (or someone else's) insight into how the original game's training rates worked to improve this too.

**Comment by TheCycoONE** [comment] 2022-10-02 20:11
Matching the original behaviour will not fix this issue. It's an open question whether fixing it is desirable, or consultants are too set in their ways to learn any new skills.

**Comment by MRMIdAS** [comment] 2023-02-06 21:21
My thought is leave it how it is in the original game.

While I understand that everyone learns new things despite their seniority IRL, I agree it'd change the late game for a lot of the later hospitals, and I would suspect, take some of the challenge away, especially on Consultant difficulty.

Perhaps the solution is to make new difficulties, Easy-Normal-Classic Normal-Consultant-Classic Consultant. Or something like that, with such QOL features disabled in "classic".

**Comment by TheCycoONE** [comment] 2024-10-19 03:06
Closing as duplicate of #1458

**Closed** 2024-10-19 03:06 UTC
Labels: enhancement, S:Discussion
