### ISSUE TITLE
Nurse don't want to do vaccination when epidemics

### ISSUE THREAD

**Issue by eeerlend** [CorsixTH/CorsixTH#630] opened 2015-01-23 23:31 UTC
**What steps will reproduce the problem?**
1. The hospital needs an epidemic going
2. Click on patients infected, so they will be "ready for vaccination"
3. Drop an idle nurse nearby

**What is the expected output? What do you see instead?**
When dropping a nurse nearby, they should do a vaccination immediately. Instead, I have trouble getting the people vaccinated at all.

**What version of CorsixTH are you using?**
0.40

**What operating system / compile settings are you using?**
Mac OSX Yosemite

**What level was this on (e.g. "Demo level", "Full game level 12")?**
Custom level, "St. Peters Near Cawley"

**Comment by eeerlend** [comment] 2015-01-25 02:33
After reading the wiki, it seems like the patients should not be vaccinated when in que standing/walking. Tested again, and the nurses do vaccinate if the patient is sitting - so not sure if this really is a bug or not...

**Comment by TheCycoONE** [comment] 2015-01-25 04:35
@sadger could you verify?  If it's not a bug I'll close it.

**Comment by sadger** [comment] 2015-01-25 15:24
At the moment they will only vaccinate if the patient is "static" they could be waiting in a queue and perhaps sitting. The nurses won't follow patients around currently and will only go to patients they are very near (5 squares away at most). We did play around with some movement of the nurses but they were chasing the patients for ages without success, it seemed better to do it this way. What you experienced is probably a bit different from the original but intended. Hope that clears it up for you.

**Comment by mugmuggy** [comment] 2017-11-24 12:44
I can see this in trunk, as I was looking at the patients dying issues #1268 (has active epidemic luckily) and #1285 and was experimenting, calling this function and found the bug.

https://github.com/CorsixTH/CorsixTH/blob/fe1a526b5f1da2439b71d9641165bd2dcbf1bbc3/CorsixTH/Lua/entity_map.lua#L183-L195

getHumandoids/getObjectsAtCoordinate returns an empty table, not nil, so the function is always returning an empty table.

I have fix for this in a branch currently with some cpp things from a [static analysis](https://github.com/CorsixTH/CorsixTH/compare/master...mugmuggy:somefixes) I ran.

**Comment by sadger** [comment] 2017-11-24 12:55
I think this is grounds enough to reopen. I'll look into this myself but looks like a good fix at a glance.

**Comment by mugmuggy** [comment] 2017-11-24 23:04
I think you'll have edge cases relying on that function when called from Epidemic:getBestVaccinationTile. 

As an example, the bench case that cuts short processing is unaffected by a human/object in the tile in front of the bench (ie a radiator placed on the tile) doesn't affect it, but to vaccinate a queued patient standing up it does. 

You could have a patient in a corner that only has one passable tile which has a side object on it, but you'll never get there as its not a candidate because of this function, or, Like in #1284 the door (I said humanoid in that analysis but it's the door) will prevent you getting to a patient at the end of a 1 tile wide path.

**Comment by sadger** [comment] 2017-11-25 14:40
I think with vaccinations they aren't supposed to be very efficient anyway, there is a random chance they don't even happen. They certainly aren't high priority for the nurses. So I think with the entity map fix we could just not handle these edge cases. Depends how easy the fix would be.

**Comment by TheCycoONE** [comment] 2017-11-29 22:16
@sadger @mugmuggy Close this?

**Comment by sadger** [comment] 2017-11-29 22:27
I would like to hear @mugmuggy  's take on this but if we don't hear back soon it can be closed following the fix that will improve matters a lot.

**Comment by mugmuggy** [comment] 2017-11-30 01:56
Probably wasn't worth merging my fix in as this is still a little buggy. If the take is to ignore the objects/humanoids next to the patient, you'd just call getAdjacentSquares from Epidemic:getBestVaccinationTile instead as your checking the path distance anyway.

Either way I think we would have just introduced another bug, in that there is now potential for the nurse to vaccinate through walls and doors. You'd need to check room/path distance (between vaccination point and patient), to find the most correct usable tile. I think that is why maybe you were checking humanoids/objects, but would have had to exclude side objects if the tile was passable.

So it probably still needs to be tweaked. As I said I came across this issue, when I was looking at the stuck dying patients, that were receiving invalid walk instructions as that was trying to find 2 tiles side by side for the fall animation and the save in #1268 just happens to have a lot of dying patients stuck at the psych when running and some rocking up are contagious.

**Comment by TheCycoONE** [comment] 2017-11-30 02:12
Well it was marked ready and I was cleaning up PRs for the release candidate.

**Comment by sadger** [comment] 2017-11-30 09:32
There is extra validation done in the vaccinate action which should hopefully avoid any vaccinations through walls https://github.com/CorsixTH/CorsixTH/blob/master/CorsixTH/Lua/humanoid_actions/vaccinate.lua#L53 . Mainly because I don't think we can have a nurse and patient with a wall between them but with neither of them in a room. I think I need to do some testing on how naughty the nurses are after this fix.

**Comment by mugmuggy** [comment] 2017-11-30 10:04
Should cover that case, the only one then would be, over the top of side objects but I don't know if that was possible in TH or not.

**Comment by sadger** [comment] 2017-11-30 10:08
I think it should be good enough how it is, thanks @mugmuggy  Closing.

**Closed by sadger** 2017-11-30 10:08 UTC

**Comment by TheCycoONE** [comment] 2017-11-30 11:51
It is possible to be in the hall with a wall between patients. It's quite an edge case as I can't think of a map that does it. Fine to leave for now.
