### ISSUE TITLE
The wall of the infirmary disappears

### ISSUE THREAD

**Issue by KeeperSt** [CorsixTH/CorsixTH#1255] opened 2017-10-01 18:50 UTC
#### Describe the issue
  The wall of the infirmary disappears, when people passes next to it.

#### Steps to Reproduce
  1. Build the infirmary.
  2. Put a bed next to the wall.
  3. Anyone who passes next to the wall (which is next to the bed), makes disappear that wall.

#### Save Game
https://www.dropbox.com/s/jcrxxo172fnvhnd/keeper9.sav?dl=0

#### System Information
**CorsixTH Version:**0.60

**Operating System:**Windows 10 64 bits

**Theme Hospital Version:**CD
### Additional Info
![med general29](https://user-images.githubusercontent.com/31771827/31057758-20aee4ec-a6e8-11e7-9732-fc2b524fc5f2.jpg)

**Comment by lewri** [comment] 2017-10-07 17:17
I'm pretty sure I saw this happen in the original. Or that the wall used to flicker in and out repeatedly while someone went past.

I did reproduce the error though, but gamelog had nothing useful.

**Comment by lewri** [comment] 2017-10-07 17:54
After a bit of further digging, the part of the bed coming through the wall is a sprite that changes when a patient is in the bed. I can only guess the game doesn't know what to do when
1 - the sprite is obscured by a wall
2 - a person walks by said wall

I noticed flipping the bed 180 stops the problem. So I would my money on that.
Have you noticed if the problem happens when someone is in the bed? And if it does does the bed appear empty or occupied?

**Comment by lewri** [comment] 2017-11-20 17:01
Excuse my oversightedness as I recently went back to try and debug more (because I don't know Lua or how to use its console to query the affected tile, didn't get much further) but the affected tile isn't actually next to the part of bed that changes.

All I could decipher is something by tick.

Example:

Tick 0 - No patient on tile

Tick 1 - Patient now on tile
--Some script must be run here in regards to anything using the tile when the patient steps on it (bed.lua, ward.lua I couldn't see anything of an obvious conflict). The output of the script must (in English) say something like: This tile is occupied by a humanoid, the tile on the left is occupied by a bed, the wall on the left can't exist. I will remove the wall.

Tick 2 - Patient leaves tile
--I don't think the same script is triggered as they leave...

Tick 3 - Patient leaves adjcaent tile
--Whatever script happened on tick 1 now puts the wall back.

I'm not sure what part of the code is saying a wall can't exist in this certain circumstance...  Maybe it's similar to the radiator bug. But I'm at my limit with how much I can help, @TheCycoONE

**Comment by TheCycoONE** [comment] 2017-11-20 17:32
Thanks @lewri 
It's closely related or the same as #475 and a couple other glitches between people and objects. I'm aware of the general issue, but haven't devoted time to it.

**Comment by TheCycoONE** [comment] 2017-11-20 17:34
There is no such script, there is a render algorithm, partially documented here: https://github.com/CorsixTH/CorsixTH/wiki/Rendering

**Comment by lewri** [comment] 2017-11-20 17:48
> Rendering is done in a 2D manner, and no depth sorting is performed, so things appear on-screen in the order in which they are rendered - if two things overlap, then the one which was rendered last will be the one appearing on-screen.

Thinking about that... what would make the bed render after the wall? Are there values set for these things somewhere?

**Comment by MarkL1961** [comment] 2017-11-20 19:27
Is the bed (or other objects at times) appearing because the patient is walking next to it and the rendering is not taking into account there is a wall in between, so you should not see it anyway?  In the above image it looks to me that the top of the wall remains and the bits below disappear.
I have read the wiki on rendering, but it is way above my limited knowledge, so I am only offering possibilities.

**Comment by TheCycoONE** [comment] 2017-11-22 02:10
The actual cause is related to redrawing which isn't mentioned that wiki article.

The below patch fixes the bed issue, but creates another glitch with people showing through walls. A real fix will be to make the redraw logic a bit more sophisticated.
```
diff --git a/CorsixTH/Src/th_map.cpp b/CorsixTH/Src/th_map.cpp
index e8ee4f40..c564dd48 100644
--- a/CorsixTH/Src/th_map.cpp
+++ b/CorsixTH/Src/th_map.cpp
@@ -1059,7 +1059,7 @@ void THMap::draw(THRenderTarget* pCanvas, int iScreenX, int iScreenY,
             //in the tile above it side objects to the east of the tile).
             if(bRedrawAnimations && !bFirst)
             {
-                bool bTileNeedsRedraw = bPreviousTileNeedsRedraw;
+                bool bTileNeedsRedraw = false;// bPreviousTileNeedsRedraw;

                 //check if an object in the adjacent tile to the left of the current tile needs to be redrawn
                 //and if necessary draw it
```

**Comment by TheCycoONE** [comment] 2017-11-24 02:48
This logic was introduced as part of a very large commit by Alex Ghiran in 2012: 99245e26 (As such it's obviously not directly related to any of the graphical issues reported in 2011)

**Comment by lewri** [comment] 2024-03-30 22:32
Merged into meta

**Closed by lewri** 2024-03-30 22:32 UTC
Labels: C:Graphical
