### ISSUE TITLE
Suspected infinite loop: Handyman got stuck in ward door

### ISSUE THREAD

**Issue by bobcanthelpyou** [CorsixTH/CorsixTH#867] opened 2015-08-10 11:55 UTC
That issue is a little bit strange. Can't reproduce it every time. Maybe it is related to the uncleanable vomit on the floor in the room, but i don't know. I fired every handyman when asking for more money. So it is possible that a handyman didn't clean up before he left, and nobody else take care of it (like #388)

I built a ward over the vomit and placed the door near the uncleanable vomit. When a handyman access the ward and will try to leave, he get stuck at the door with a suspected infinite loop.

![screenshot](https://cloud.githubusercontent.com/assets/4523264/9170602/8b77fb44-3f64-11e5-9991-1cc84abc82ab.png)

Steps to reproduce:
- load loop01.sav
- build a ward like in the screenshot
  - (maybe you have to wait until a patient put some new vomit on the blueprint of the ward)
- place a handyman in the ward (if none of the handymen access the room by themselves) 
- wait

```
An error has occured!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The timer handler.
A stack trace is included below, and the handler has been disconnected.
./Lua/class.lua:136: Suspected infinite loop
stack traceback:
    [C]: in function 'error'
    ./Lua/app.lua:797: in function <./Lua/app.lua:794>
    ./Lua/class.lua:136: in function 'is'
    ./Lua/entity_map.lua:54: in function 'addEntity'
    ./Lua/entity.lua:133: in function 'setTile'
    ./Lua/entity.lua:174: in function 'setTilePositionSpeed'
    ./Lua/humanoid_actions/walk.lua:175: in function <./Lua/humanoid_actions/walk.lua:137>
    (tail call): ?
    (tail call): ?
    (tail call): ?
    (tail call): ?
    (tail call): ?
    ...
    (tail call): ?
    (tail call): ?
    (tail call): ?
    (tail call): ?
    ./Lua/entity.lua:218: in function 'tick'
    ./Lua/entities/staff.lua:149: in function 'tick'
    ./Lua/world.lua:1121: in function 'onTick'
    ./Lua/app.lua:878: in function <./Lua/app.lua:875>
    (tail call): ?
    ./Lua/app.lua:779: in function <./Lua/app.lua:774>

Error in timer handler:
[....]
Warning: No event handler for timer
```

When you continue the game, everyone else get stuck with a suspected infinite loop, too (see loop04.sav). The stack traceback is slightly different

```
An error has occured!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The timer handler.
A stack trace is included below, and the handler has been disconnected.
./Lua/entity.lua:123: Suspected infinite loop
stack traceback:
    [C]: in function 'error'
    ./Lua/app.lua:797: in function <./Lua/app.lua:794>
    ./Lua/entity.lua:123: in function 'setTile'
    ./Lua/entity.lua:174: in function 'setTilePositionSpeed'
    ./Lua/humanoid_actions/walk.lua:175: in function <./Lua/humanoid_actions/walk.lua:137>
    (tail call): ?
    (tail call): ?
    (tail call): ?
    (tail call): ?
    (tail call): ?
    (tail call): ?
    (tail call): ?
    ...
    (tail call): ?
    (tail call): ?
    (tail call): ?
    (tail call): ?
    ./Lua/entity.lua:218: in function 'tick'
    ./Lua/entities/staff.lua:149: in function 'tick'
    ./Lua/world.lua:1121: in function 'onTick'
    ./Lua/app.lua:878: in function <./Lua/app.lua:875>
    (tail call): ?
    ./Lua/app.lua:779: in function <./Lua/app.lua:774>
```

Savegames:
http://filebin.ca/2BeXlcLbuyLl/loop04.sav (there is a big meeting at the door ..)
http://filebin.ca/2BeQDI4MYVFo/loop01.sav (before issue, no ward is build yet)

CorsixTH trunk e053c4390356af739dd8926a058242e21d0491ae / Lua 5.1 / Debian Jessie 64bit / Single Scenario: Confined

**Comment by lewri** [comment] 2020-12-05 12:22
I've downloaded the save for this (thankfully still up) and ran a few times.
It looks like whatever caused the bug in 2015 is fixed as it wouldn't crash. I suspect that the original bug was caused by a vomit not being removed by the new ward. But now our blueprints clean up vomit properly.

Closing optimistically.

**Closed by lewri** 2020-12-05 12:22 UTC
