### ISSUE TITLE
Patient who vomit while building a room

### ISSUE THREAD

**Issue by Necrobare** [CorsixTH/CorsixTH#679] opened 2015-02-07 21:00 UTC
Hi ! 

I spot a new bug, in a very specific case:

- I am at the first step of builing a room. I define a valid area and a patient in on this area
- I validate, then in second step I locate the door and windows without issue
- I validate, then the patient move out of this area, but before moving he vomits in the blue area
- In this case, as soon as he leave the area, the vomit disapear and the room appears.
- Then, if I try to edit/delete the room, the edit menu appears but is completly bugged: buttons X or validate has no effects and I can't close the menu. The only issue is to go back to windows to stop the game.

**Comment by Necrobare** [comment] 2015-02-07 21:16
I managed to get a save at the last step of room construction:

http://www.filedropper.com/test_25

**Comment by MarkL1961** [comment] 2015-02-08 08:24
Issue #66  and issue #147 are related

**Comment by TheCycoONE** [comment] 2015-07-15 22:48
File doesn't appear to exist anymore, but we believe this is a duplicate of #66

**Closed by TheCycoONE** 2015-07-15 22:48 UTC
