### ISSUE TITLE
Clicking under employee raise buttons

### ISSUE THREAD

**Issue by CosbyArt** [CorsixTH/CorsixTH#1300] opened 2017-12-03 09:17 UTC
#### Describe the issue

While training doctors they ask for raises as they learn, and clicking the button to accept the raise or not (to sack them), if there is anything under the message button itself that the cursor can move (such as a radiator, bench, plant, soda machine, doctor, nurse, etc) once the message disappears the item underneath is picked-up and held by the mouse cursor.

That is simply clicking the raise "button" results in the doctor getting a raise and I am left with a picked-up object underneath the message box on the game itself from a single mouse click. It seems to happen whenever the mouse happens to be lined up with a object under the position the mouse is clicked on the button.

In this instance it froze the game, music played normally between songs, but everything else was frozen. In the end I had to use Windows task manager to close CorsixTH. I just finished deleting my research room to free the area, as everything was 100% done, and I clicked a training doctor raise accept message button and it picked-up one of the wandering research doctors beneath the raise button and froze.

#### Steps to Reproduce
1. Train a doctor and when he asks for a raise, if the raise message is over a object that can be picked-up, it will give the doctor a raise and pick-up the object.

#### Expected Behavior
The doctor raise message to disappear and no further interference with the game. Perhaps some sort of delay/pause in the mouse click is needed after a message to prevent picking-up objects under a message.

#### System Information
**CorsixTH Version:** *e.g. 0.50 or 7d886f35ca*
v0.61-beta1

**Operating System:** *e.g. Windows 10*
Windows 8.1

**Theme Hospital Version:** *CD, GOG.com, Origin, or Demo*
GOG.com

#### Gamelog.txt
*For information about where to find gamelog.txt see:
https://github.com/CorsixTH/CorsixTH/wiki/Frequently-Asked-Questions#where-do-i-find-the-configuration-or-the-gamelog-file*
```
Paste gamelog.txt output here

Created game with savegame version 119.
Savegame version is 119 (v0.61-beta1), originally it was 119 (v0.61-beta1)
Warning: Trying to remove nonexistant room build callback (function: 000000F8565551A0) from humanoid (table: 000000F856DD6330).
Warning: Trying to remove nonexistant room remove callback (function: 000000F851347380) from humanoid (table: 000000F856DD6330).
Warning: Trying to remove nonexistant room build callback (function: 000000F8575E89F0) from humanoid (table: 000000F856FBC720).
Warning: Trying to remove nonexistant room remove callback (function: 000000F859BBEB70) from humanoid (table: 000000F856FBC720).
Warning: Trying to remove nonexistant room build callback (function: 000000F856D83D00) from humanoid (table: 000000F856C19170).
Warning: Trying to remove nonexistant room remove callback (function: 000000F85A5C90F0) from humanoid (table: 000000F856C19170).
Savegame version is 119 (v0.61-beta1), originally it was 119 (v0.61-beta1)
Warning: Trying to remove nonexistant room build callback (function: 000000F05196C890) from humanoid (table: 000000F05BAF7920).
Warning: Trying to remove nonexistant room remove callback (function: 000000F040065CA0) from humanoid (table: 000000F05BAF7920).
Warning: Trying to remove nonexistant room build callback (function: 000000F051970430) from humanoid (table: 000000F05B380B30).
Warning: Trying to remove nonexistant room remove callback (function: 000000F051821560) from humanoid (table: 000000F05B380B30).
Warning: Trying to remove nonexistant room build callback (function: 000000F05196FE90) from humanoid (table: 000000F05A725630).
Warning: Trying to remove nonexistant room remove callback (function: 000000F05AE97A40) from humanoid (table: 000000F05A725630).
Warning: Trying to remove nonexistant room build callback (function: 000000F05C77C4D0) from humanoid (table: 000000F059C72D00).
Warning: Trying to remove nonexistant room remove callback (function: 000000F05B18DF60) from humanoid (table: 000000F059C72D00).
Warning: Trying to remove nonexistant room build callback (function: 000000F05F3E8B70) from humanoid (table: 000000F05B208AD0).
Warning: Trying to remove nonexistant room remove callback (function: 000000F05BFF3B00) from humanoid (table: 000000F05B208AD0).
Warning: Trying to remove nonexistant room build callback (function: 000000F05F011900) from humanoid (table: 000000F0512C6C20).
Warning: Trying to remove nonexistant room remove callback (function: 000000F05BA18D50) from humanoid (table: 000000F0512C6C20).
Warning: Trying to remove nonexistant room build callback (function: 000000F05C784ED0) from humanoid (table: 000000F05BB88680).
Warning: Trying to remove nonexistant room remove callback (function: 000000F05B0F1790) from humanoid (table: 000000F05BB88680).
Warning: Trying to remove nonexistant room build callback (function: 000000F05F3EDBE0) from humanoid (table: 000000F05BAA9270).
Warning: Trying to remove nonexistant room remove callback (function: 000000F05A3A6BF0) from humanoid (table: 000000F05BAA9270).
Warning: Trying to remove nonexistant room build callback (function: 000000F05C77D850) from humanoid (table: 000000F05A70FBB0).
Warning: Trying to remove nonexistant room remove callback (function: 000000F04006C810) from humanoid (table: 000000F05A70FBB0).
Warning: Trying to remove nonexistant room build callback (function: 000000F05C781BD0) from humanoid (table: 000000F0512DA1A0).
Warning: Trying to remove nonexistant room remove callback (function: 000000F05C1EEA00) from humanoid (table: 000000F0512DA1A0).
Warning: Trying to remove nonexistant room build callback (function: 000000F05F3ED160) from humanoid (table: 000000F03F7FCA40).
Warning: Trying to remove nonexistant room remove callback (function: 000000F05A3A51E0) from humanoid (table: 000000F03F7FCA40).
Warning: Trying to remove nonexistant room build callback (function: 000000F05B4E8790) from humanoid (table: 000000F05C54EB10).
Warning: Trying to remove nonexistant room remove callback (function: 000000F05B0F1D30) from humanoid (table: 000000F05C54EB10).
Warning: Trying to remove nonexistant room build callback (function: 000000F05EEA2FC0) from humanoid (table: 000000F05127F010).
Warning: Trying to remove nonexistant room remove callback (function: 000000F0400695D0) from humanoid (table: 000000F05127F010).
Warning: Trying to remove nonexistant room build callback (function: 000000F05C77DBB0) from humanoid (table: 000000F05A2187F0).
Warning: Trying to remove nonexistant room remove callback (function: 000000F05181E8F0) from humanoid (table: 000000F05A2187F0).
Warning: Trying to remove nonexistant room build callback (function: 000000F05C779D70) from humanoid (table: 000000F05C86DF70).
Warning: Trying to remove nonexistant room remove callback (function: 000000F05EFD80A0) from humanoid (table: 000000F05C86DF70).
Warning: Trying to remove nonexistant room build callback (function: 000000F05B4E52B0) from humanoid (table: 000000F05A203670).
Warning: Trying to remove nonexistant room remove callback (function: 000000F059F33D00) from humanoid (table: 000000F05A203670).
Warning: Trying to remove nonexistant room build callback (function: 000000F05F3F3BE0) from humanoid (table: 000000F0512C8020).
Warning: Trying to remove nonexistant room remove callback (function: 000000F05FAA0820) from humanoid (table: 000000F0512C8020).
Warning: Trying to remove nonexistant room build callback (function: 000000F05B4E65D0) from humanoid (table: 000000F05BDA4F60).
Warning: Trying to remove nonexistant room remove callback (function: 000000F05B556D80) from humanoid (table: 000000F05BDA4F60).
Warning: Trying to remove nonexistant room build callback (function: 000000F05F3F1300) from humanoid (table: 000000F05C55BBD0).
Warning: Trying to remove nonexistant room remove callback (function: 000000F05A4B3730) from humanoid (table: 000000F05C55BBD0).
Warning: Trying to remove nonexistant room build callback (function: 000000F05B8ED2E0) from humanoid (table: 000000F05119CDB0).
Warning: Trying to remove nonexistant room remove callback (function: 000000F05B560620) from humanoid (table: 000000F05119CDB0).
Warning: Trying to remove nonexistant room build callback (function: 000000F05B4EA770) from humanoid (table: 000000F05FB350A0).
Warning: Trying to remove nonexistant room remove callback (function: 000000F03F801F30) from humanoid (table: 000000F05FB350A0).
Warning: Trying to remove nonexistant room build callback (function: 000000F05B4E8190) from humanoid (table: 000000F05B3056A0).
Warning: Trying to remove nonexistant room remove callback (function: 000000F05A0693E0) from humanoid (table: 000000F05B3056A0).
Warning: Trying to remove nonexistant room build callback (function: 000000F040106C40) from humanoid (table: 000000F03F7EE3C0).
Warning: Trying to remove nonexistant room remove callback (function: 000000F05FA607C0) from humanoid (table: 000000F03F7EE3C0).
Warning: Trying to remove nonexistant room build callback (function: 000000F0401051A0) from humanoid (table: 000000F05C097720).
Warning: Trying to remove nonexistant room remove callback (function: 000000F05AE10D50) from humanoid (table: 000000F05C097720).
Warning: Trying to remove nonexistant room build callback (function: 000000F05EBE5A30) from humanoid (table: 000000F059A4AC60).
Warning: Trying to remove nonexistant room remove callback (function: 000000F05F2ABE60) from humanoid (table: 000000F059A4AC60).
Warning: Trying to remove nonexistant room build callback (function: 000000F05EBE4E90) from humanoid (table: 000000F059A44D60).
Warning: Trying to remove nonexistant room remove callback (function: 000000F05F59B7A0) from humanoid (table: 000000F059A44D60).
Warning: Trying to remove nonexistant room build callback (function: 000000F05C77E750) from humanoid (table: 000000F05BB129A0).
Warning: Trying to remove nonexistant room remove callback (function: 000000F03F80DC60) from humanoid (table: 000000F05BB129A0).
Warning: Trying to remove nonexistant room build callback (function: 000000F05F5825F0) from humanoid (table: 000000F05BD5B930).
Warning: Trying to remove nonexistant room remove callback (function: 000000F059D54430) from humanoid (table: 000000F05BD5B930).
Warning: Trying to remove nonexistant room build callback (function: 000000F05F585EF0) from humanoid (table: 000000F05B61E090).
Warning: Trying to remove nonexistant room remove callback (function: 000000F05AE8F9D0) from humanoid (table: 000000F05B61E090).
Warning: Trying to remove nonexistant room build callback (function: 000000F05F586130) from humanoid (table: 000000F05C09A6A0).
Warning: Trying to remove nonexistant room remove callback (function: 000000F05EBCBC90) from humanoid (table: 000000F05C09A6A0).
Warning: Trying to remove nonexistant room build callback (function: 000000F05F5976B0) from humanoid (table: 000000F05FA84DA0).
Warning: Trying to remove nonexistant room remove callback (function: 000000F05FC01CF0) from humanoid (table: 000000F05FA84DA0).
Warning: Trying to remove nonexistant room build callback (function: 000000F05F595430) from humanoid (table: 000000F05CA06B20).
Warning: Trying to remove nonexistant room remove callback (function: 000000F051956CD0) from humanoid (table: 000000F05CA06B20).
Warning: Trying to remove nonexistant room build callback (function: 000000F05F591B90) from humanoid (table: 000000F05FB22720).
Warning: Trying to remove nonexistant room remove callback (function: 000000F03FDFF4B0) from humanoid (table: 000000F05FB22720).
Warning: Trying to remove nonexistant room build callback (function: 000000F05F593E10) from humanoid (table: 000000F03F7E5E40).
Warning: Trying to remove nonexistant room remove callback (function: 000000F05B006EC0) from humanoid (table: 000000F03F7E5E40).
Warning: Trying to remove nonexistant room build callback (function: 000000F05C780DF0) from humanoid (table: 000000F05EF30990).
Warning: Trying to remove nonexistant room remove callback (function: 000000F04012D3B0) from humanoid (table: 000000F05EF30990).
Savegame version is 119 (v0.61-beta1), originally it was 119 (v0.61-beta1)
Error in timer handler: 
...rogram Files\CorsixTH\Lua\humanoid_actions\seek_room.lua:173: attempt to compare nil with number
stack traceback:
	...rogram Files\CorsixTH\Lua\humanoid_actions\seek_room.lua:173: in upvalue 'action_seek_room_no_diagnosis_room_found'
	...rogram Files\CorsixTH\Lua\humanoid_actions\seek_room.lua:335: in field '?'
	C:\Program Files\CorsixTH\Lua\entities\humanoid.lua:578: in upvalue 'Humanoid_startAction'
	C:\Program Files\CorsixTH\Lua\entities\humanoid.lua:670: in method 'finishAction'
	C:\Program Files\CorsixTH\Lua\humanoid_actions\idle.lua:66: in local 'timer_function'
	C:\Program Files\CorsixTH\Lua\entity.lua:216: in field 'tick'
	C:\Program Files\CorsixTH\Lua\entities\staff.lua:149: in method 'tick'
	C:\Program Files\CorsixTH\Lua\world.lua:1051: in method 'onTick'
	C:\Program Files\CorsixTH\Lua\app.lua:1007: in function <C:\Program Files\CorsixTH\Lua\app.lua:1004>
	(...tail calls...)
	C:\Program Files\CorsixTH\Lua\app.lua:908: in function <C:\Program Files\CorsixTH\Lua\app.lua:903>
Error in buttonup handler: 
...rogram Files\CorsixTH\Lua\humanoid_actions\seek_room.lua:260: attempt to call a nil value (method 'updateMessage')
stack traceback:
	...rogram Files\CorsixTH\Lua\humanoid_actions\seek_room.lua:260: in local 'callback'
	C:\Program Files\CorsixTH\Lua\world.lua:809: in method 'notifyRoomRemoved'
	C:\Program Files\CorsixTH\Lua\room.lua:907: in method 'deactivate'
	C:\Program Files\CorsixTH\Lua\dialogs\edit_room.lua:157: in method 'abortRoom'
	C:\Program Files\CorsixTH\Lua\dialogs\edit_room.lua:176: in field 'callback_ok'
	C:\Program Files\CorsixTH\Lua\dialogs\confirm_dialog.lua:81: in method 'close'
	C:\Program Files\CorsixTH\Lua\dialogs\confirm_dialog.lua:71: in local 'callback'
	C:\Program Files\CorsixTH\Lua\window.lua:682: in method 'handleClick'
	C:\Program Files\CorsixTH\Lua\window.lua:1478: in method 'onMouseUp'
	C:\Program Files\CorsixTH\Lua\window.lua:1462: in field 'onMouseUp'
	C:\Program Files\CorsixTH\Lua\ui.lua:654: in function <C:\Program Files\CorsixTH\Lua\ui.lua:641>
	(...tail calls...)
	C:\Program Files\CorsixTH\Lua\app.lua:908: in function <C:\Program Files\CorsixTH\Lua\app.lua:903>
```

### Additional Info
*Paste any screen shots or other additional information that might help
illustrate the problem.*

![shot 2017-12-03 03 44 23](https://user-images.githubusercontent.com/34206133/33523804-a489531c-d7dd-11e7-819f-8e36a8adc76d.jpg)

**Comment by TheCycoONE** [comment] 2017-12-04 02:08
Duplicate of longstanding issue #521 
This issue in the gamelog is interesting but unrelated. Did you notice any other behavior related to that you could open another ticket for?

**Closed by TheCycoONE** 2017-12-04 02:08 UTC
