### ISSUE TITLE
Add fullscreen/windowed mode keybind toggle

### ISSUE THREAD

**Issue by Richard-L** [CorsixTH/CorsixTH#1952] opened 2021-06-22 21:15 UTC
As we had discussed, either F11 or (better) ALT+ENTER.

Mild relations to:
https://github.com/CorsixTH/CorsixTH/issues/1637
https://github.com/CorsixTH/CorsixTH/issues/1610
https://github.com/CorsixTH/CorsixTH/issues/704

^704 likely would also fix focus issues after ALT+TAB

**Comment by lewri** [comment] 2021-06-22 21:56
I think other issues as mentioned may block this working as intended. Though it'd likely work okay with fullscreen (windowed)

**Comment by TheCycoONE** [comment] 2021-06-23 01:07
We already have one...

**Comment by flackr** [comment] 2021-06-23 01:18
https://github.com/CorsixTH/CorsixTH/blob/master/CorsixTH/Lua/config_finder.lua#L546

**Comment by TheCycoONE** [comment] 2021-06-23 01:36
Ok, I understand - when the game is at full resolution, then toggling to window mode doesn't show you the window chrome like you might expect, because the game takes up the entire desktop.

If you lower the resolution the toggle behaves like you would expect.

**Comment by TheCycoONE** [comment] 2021-06-23 01:42
That issue is #1637 though I can better describe it. Closing this issue.

**Closed by TheCycoONE** 2021-06-23 01:42 UTC
Labels: C:SDL2
