### ISSUE TITLE
People walking over burned down areas causing crash of game

### ISSUE THREAD

**Issue by danielcespedes2824** [CorsixTH/CorsixTH#1011] opened 2016-03-27 04:08 UTC
#### Gamelog.txt
*For information about where to find gamelog.txt see:
https://github.com/CorsixTH/CorsixTH/wiki/Frequently-Asked-Questions#where-do-i-find-the-configuration-or-the-gamelog-file*
```
Paste gamelog.txt output here


---------------------------------------------------------------

Welcome to CorsixTH 0.50!

---------------------------------------------------------------

This window will display useful information if an error occurs.

---------------------------------------------------------------

Checking for CorsixTH updates...
You are running the latest version of CorsixTH.
An error has occured!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The timer handler.
A stack trace is included below, and the handler has been disconnected.
C:\Program Files\CorsixTH\Lua\humanoid_actions\walk.lua:227: attempt to index a nil value (field 'queue')
stack traceback:
        C:\Program Files\CorsixTH\Lua\humanoid_actions\walk.lua:227: in function <C:\Program Files\CorsixTH\Lua\humanoid_actions\walk.lua:209>
        (...tail calls...)
        C:\Program Files\CorsixTH\Lua\humanoid_actions\walk.lua:187: in local 'timer_function'
        C:\Program Files\CorsixTH\Lua\entity.lua:218: in field 'tick'
        C:\Program Files\CorsixTH\Lua\entities\staff.lua:149: in method 'tick'
        C:\Program Files\CorsixTH\Lua\world.lua:1121: in method 'onTick'
        C:\Program Files\CorsixTH\Lua\app.lua:878: in function <C:\Program Files\CorsixTH\Lua\app.lua:875>
        (...tail calls...)
        C:\Program Files\CorsixTH\Lua\app.lua:779: in function <C:\Program Files\CorsixTH\Lua\app.lua:774>

Warning: No event handler for timer
An error has occured!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The timer handler.
A stack trace is included below, and the handler has been disconnected.
C:\Program Files\CorsixTH\Lua\class.lua:135: Suspected infinite loop
stack traceback:
        [C]: in function 'error'
        C:\Program Files\CorsixTH\Lua\app.lua:797: in hook '?'
        C:\Program Files\CorsixTH\Lua\class.lua:135: in field 'is'
        C:\Program Files\CorsixTH\Lua\entity_map.lua:54: in method 'addEntity'
        C:\Program Files\CorsixTH\Lua\entity.lua:133: in field 'setTile'
        C:\Program Files\CorsixTH\Lua\entities\patient.lua:935: in method 'setTile'
        C:\Program Files\CorsixTH\Lua\entity.lua:174: in method 'setTilePositionSpeed'
        C:\Program Files\CorsixTH\Lua\humanoid_actions\walk.lua:175: in function <C:\Program Files\CorsixTH\Lua\humanoid_actions\walk.lua:137>
        (...tail calls...)
        C:\Program Files\CorsixTH\Lua\entity.lua:218: in method 'tick'
        C:\Program Files\CorsixTH\Lua\world.lua:1121: in method 'onTick'
        C:\Program Files\CorsixTH\Lua\app.lua:878: in function <C:\Program Files\CorsixTH\Lua\app.lua:875>
        (...tail calls...)
        C:\Program Files\CorsixTH\Lua\app.lua:779: in function <C:\Program Files\CorsixTH\Lua\app.lua:774>

An error has occured!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The timer handler.
A stack trace is included below, and the handler has been disconnected.
C:\Program Files\CorsixTH\Lua\entity.lua:132: Suspected infinite loop
stack traceback:
        [C]: in function 'error'
        C:\Program Files\CorsixTH\Lua\app.lua:797: in hook '?'
        C:\Program Files\CorsixTH\Lua\entity.lua:132: in field 'setTile'
        C:\Program Files\CorsixTH\Lua\entities\patient.lua:935: in method 'setTile'
        C:\Program Files\CorsixTH\Lua\entity.lua:174: in method 'setTilePositionSpeed'
        C:\Program Files\CorsixTH\Lua\humanoid_actions\walk.lua:175: in function <C:\Program Files\CorsixTH\Lua\humanoid_actions\walk.lua:137>
        (...tail calls...)
        C:\Program Files\CorsixTH\Lua\entity.lua:218: in method 'tick'
        C:\Program Files\CorsixTH\Lua\world.lua:1121: in method 'onTick'
        C:\Program Files\CorsixTH\Lua\app.lua:878: in function <C:\Program Files\CorsixTH\Lua\app.lua:875>
        (...tail calls...)
        C:\Program Files\CorsixTH\Lua\app.lua:779: in function <C:\Program Files\CorsixTH\Lua\app.lua:774>

An error has occured!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The timer handler.
A stack trace is included below, and the handler has been disconnected.
C:\Program Files\CorsixTH\Lua\class.lua:135: Suspected infinite loop
stack traceback:
        [C]: in function 'error'
        C:\Program Files\CorsixTH\Lua\app.lua:797: in hook '?'
        C:\Program Files\CorsixTH\Lua\class.lua:135: in field 'is'
        C:\Program Files\CorsixTH\Lua\entity_map.lua:54: in method 'addEntity'
        C:\Program Files\CorsixTH\Lua\entity.lua:133: in method 'setTile'
        C:\Program Files\CorsixTH\Lua\entity.lua:174: in method 'setTilePositionSpeed'
        C:\Program Files\CorsixTH\Lua\humanoid_actions\walk.lua:175: in function <C:\Program Files\CorsixTH\Lua\humanoid_actions\walk.lua:137>
        (...tail calls...)
        C:\Program Files\CorsixTH\Lua\entity.lua:218: in field 'tick'
        C:\Program Files\CorsixTH\Lua\entities\staff.lua:149: in method 'tick'
        C:\Program Files\CorsixTH\Lua\world.lua:1121: in method 'onTick'
        C:\Program Files\CorsixTH\Lua\app.lua:878: in function <C:\Program Files\CorsixTH\Lua\app.lua:875>
        (...tail calls...)
        C:\Program Files\CorsixTH\Lua\app.lua:779: in function <C:\Program Files\CorsixTH\Lua\app.lua:774>

An error has occured!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The timer handler.
A stack trace is included below, and the handler has been disconnected.
C:\Program Files\CorsixTH\Lua\humanoid_actions\walk.lua:165: Suspected infinite loop
stack traceback:
        [C]: in function 'error'
        C:\Program Files\CorsixTH\Lua\app.lua:797: in hook '?'
        C:\Program Files\CorsixTH\Lua\humanoid_actions\walk.lua:165: in function <C:\Program Files\CorsixTH\Lua\humanoid_actions\walk.lua:137>
        (...tail calls...)
        C:\Program Files\CorsixTH\Lua\entity.lua:218: in method 'tick'
        C:\Program Files\CorsixTH\Lua\world.lua:1121: in method 'onTick'
        C:\Program Files\CorsixTH\Lua\app.lua:878: in function <C:\Program Files\CorsixTH\Lua\app.lua:875>
        (...tail calls...)
        C:\Program Files\CorsixTH\Lua\app.lua:779: in function <C:\Program Files\CorsixTH\Lua\app.lua:774>



### Additional Info
*Paste any screen shots or other additional information that might help
illustrate the problem.*

**Comment by MarkL1961** [comment] 2016-03-27 12:03
Exploded rooms are closed off so how are patients and staff interacting with closed rooms?

**Comment by danielcespedes2824** [comment] 2016-03-28 16:26
Hi Mark!

The problem is that the room exploded and became disabled but it was built
right on the connection to the expansion of the land. When i bought the
expansion of the property, it opened up and the people would try to get to
the other side through the corridor that ledto the burnt room. It had no
wall on the picture (unfortunately i didnt get take a screenshot). And
everytime one person would get to the "illegal" tile, Iwould get an error
message.

**Comment by Lego3** [comment] 2016-03-28 16:37
Aha, then it sounds like the root cause is #451?

**Comment by TheCycoONE** [comment] 2016-03-28 16:58
I don't think we'd need to address this if #451 was fixed.

Closing as a duplicate.

**Closed by TheCycoONE** 2016-03-28 16:58 UTC
