### ISSUE TITLE
Random Crashes 

### ISSUE THREAD

**Issue by Lou89** [CorsixTH/CorsixTH#690] opened 2015-02-13 20:10 UTC
Hi,

Newbie to Theme Hospital and CorsixTH so if I'm overlooking something obvious, please bare with me.
I don't notice a pattern or particular event when the game crashes but the game crashes almost every 20 minutes or so of continuous game play. I'll add the game log below as I've seen this requested for other players issues. I also have a screenshot of the black box (Sorry I'm not sure what it's called) but for some reason i cant get it to upload in the message (dragging and dropping or selecting the file). 

Gamelog.

Created game with savegame version 91.
Savegame version is 91 (0.40), originally it was 91 (0.40)
Warning: Trying to remove nonexistant room build callback (function: 0x0d4d8f20) from humanoid (table: 0x08783c90).
Warning: Trying to remove nonexistant room remove callback (function: 0x1485d3a0) from humanoid (table: 0x08783c90).
Warning: Trying to remove nonexistant room build callback (function: 0x0e1450a8) from humanoid (table: 0x032de080).
Warning: Trying to remove nonexistant room remove callback (function: 0x0d979bd0) from humanoid (table: 0x032de080).
Warning: Trying to remove nonexistant room build callback (function: 0x0d332788) from humanoid (table: 0x14acb268).
Warning: Trying to remove nonexistant room remove callback (function: 0x0d35a178) from humanoid (table: 0x14acb268).
Warning: Trying to remove nonexistant room build callback (function: 0x085e3ca8) from humanoid (table: 0x085e1e88).
Warning: Trying to remove nonexistant room remove callback (function: 0x0e183530) from humanoid (table: 0x085e1e88).
Warning: Trying to remove nonexistant room build callback (function: 0x0d8cd248) from humanoid (table: 0x0d7ea7a8).
Warning: Trying to remove nonexistant room remove callback (function: 0x0d9059f8) from humanoid (table: 0x0d7ea7a8).
Savegame version is 91 (0.40), originally it was 91 (0.40)
Savegame version is 91 (0.40), originally it was 91 (0.40)
Warning: Trying to remove nonexistant room build callback (function: 0x15ecd160) from humanoid (table: 0x15dfc630).
Warning: Trying to remove nonexistant room remove callback (function: 0x1ae71168) from humanoid (table: 0x15dfc630).
Savegame version is 91 (0.40), originally it was 91 (0.40)
Savegame version is 91 (0.40), originally it was 91 (0.40)
Savegame version is 91 (0.40), originally it was 91 (0.40)
Savegame version is 91 (0.40), originally it was 91 (0.40)
Savegame version is 91 (0.40), originally it was 91 (0.40)
Savegame version is 91 (0.40), originally it was 91 (0.40)
Warning: Trying to remove nonexistant room build callback (function: 0x0e73f770) from humanoid (table: 0x173df128).
Warning: Trying to remove nonexistant room remove callback (function: 0x17427c40) from humanoid (table: 0x173df128).
Warning: Trying to remove nonexistant room build callback (function: 0x15e00ac0) from humanoid (table: 0x0f7b3f58).
Warning: Trying to remove nonexistant room remove callback (function: 0x0e672528) from humanoid (table: 0x0f7b3f58).
Warning: Trying to remove nonexistant room build callback (function: 0x15ddcdb0) from humanoid (table: 0x173df128).
Warning: Trying to remove nonexistant room remove callback (function: 0x08844e08) from humanoid (table: 0x173df128).
Savegame version is 91 (0.40), originally it was 91 (0.40)
Savegame version is 91 (0.40), originally it was 91 (0.40)
Savegame version is 91 (0.40), originally it was 91 (0.40)
Savegame version is 91 (0.40), originally it was 91 (0.40)
Savegame version is 91 (0.40), originally it was 91 (0.40)
Warning: Trying to remove nonexistant room build callback (function: 0x0fa73708) from humanoid (table: 0x0f9c79a8).
Warning: Trying to remove nonexistant room remove callback (function: 0x0b890198) from humanoid (table: 0x0f9c79a8).
Savegame version is 91 (0.40), originally it was 91 (0.40)
Savegame version is 91 (0.40), originally it was 91 (0.40)
Savegame version is 91 (0.40), originally it was 91 (0.40)
Error in timer handler: 
C:\Program Files\CorsixTH\Lua\entity.lua:123: Suspected infinite loop
stack traceback:
	C:\Program Files\CorsixTH\Lua\entity.lua: in function 'setTile'
	C:\Program Files\CorsixTH\Lua\entity.lua:171: in function 'setTilePositionSpeed'
	C:\Program Files\CorsixTH\Lua\humanoid_actions\walk.lua:175: in function 'timer_function'
	C:\Program Files\CorsixTH\Lua\entity.lua:215: in function 'tick'
	C:\Program Files\CorsixTH\Lua\entities\staff.lua:146: in function 'tick'
	C:\Program Files\CorsixTH\Lua\world.lua:1103: in function 'onTick'
	C:\Program Files\CorsixTH\Lua\app.lua:852: in function 'dispatch'
	C:\Program Files\CorsixTH\Lua\app.lua:753: in function <C:\Program Files\CorsixTH\Lua\app.lua:748>
 
If anyone could give a hand i'd greatly appreciate it :)

Thanks in advance!

**Comment by TheCycoONE** [comment] 2015-02-13 20:20
Duplicate of #657

**Closed by TheCycoONE** 2015-02-13 20:20 UTC
