### ISSUE TITLE
Freeze Error

### ISSUE THREAD

**Issue by sionmaisley** [CorsixTH/CorsixTH#1334] opened 2018-01-19 17:17 UTC
After starting a pandemic mission everyone in the hospital is frozen, ive tried adjusting the speed and reloading but still the same issue, restarting the level sent me to a blank screen.

Running: The timer handler.
A stack trace is included below, and the handler has been disconnected.
C:\Program Files\CorsixTH\Lua\epidemic.lua:551: attempt to index a nil value (local 'action')
stack traceback:
        C:\Program Files\CorsixTH\Lua\epidemic.lua:551: in upvalue 'is_static'
        C:\Program Files\CorsixTH\Lua\epidemic.lua:561: in method 'markedPatientsCallForVaccination'
        C:\Program Files\CorsixTH\Lua\epidemic.lua:109: in method 'tick'
        C:\Program Files\CorsixTH\Lua\hospital.lua:1410: in method 'manageEpidemics'
        C:\Program Files\CorsixTH\Lua\hospital.lua:834: in method 'tick'
        C:\Program Files\CorsixTH\Lua\world.lua:1039: in method 'onTick'
        C:\Program Files\CorsixTH\Lua\app.lua:1008: in function <C:\Program Files\CorsixTH\Lua\app.lua:1005>
        (...tail calls...)
        C:\Program Files\CorsixTH\Lua\app.lua:909: in function <C:\Program Files\CorsixTH\Lua\app.lua:904>

Warning: No event handler for timer

Version 0.61

OS: Windows 10

Origin Version

**Comment by pschoffer** [comment] 2018-01-20 11:42
Hi @sionmaisley, do you have a save game or a way to reproduce this?

**Comment by sionmaisley** [comment] 2018-01-20 12:48
I don't know where to find my save files

Sent from Yahoo Mail on Android 
 
  On Sat, 20 Jan 2018 at 11:42, pschoffer<notifications@github.com> wrote:   
Hi @sionmaisley, do you have a save game or a way to reproduce this?

**Comment by sionmaisley** [comment] 2018-01-20 13:24
Found it after much digging


Thanks 
Sent from Yahoo Mail on Android 
 
  On Sat, 20 Jan 2018 at 12:48, Christian Thorpe<sionmaisley@yahoo.co.uk> wrote:   I don't know where to find my save files

Sent from Yahoo Mail on Android 
 
  On Sat, 20 Jan 2018 at 11:42, pschoffer<notifications@github.com> wrote:   
Hi @sionmaisley, do you have a save game or a way to reproduce this?

**Comment by pschoffer** [comment] 2018-01-20 16:18
This might be useless for you now but in [FAQ](https://github.com/CorsixTH/CorsixTH/wiki/Frequently-Asked-Questions) you can find a section that deals with save game location. 

Have you attached the file?

**Comment by sionmaisley** [comment] 2018-01-20 16:33
Yes I just attached and sent it in the last email

Sent from Yahoo Mail on Android 
 
  On Sat, 20 Jan 2018 at 16:18, pschoffer<notifications@github.com> wrote:   
This might be useless for you now but in FAQ you can find a section that deals with save game location.

Have you attached the file?

**Comment by pschoffer** [comment] 2018-01-20 16:41
I am not sure if github can process email attachments this way, because I don't see it here on the issue. You might need to attach it here.

**Comment by sionmaisley** [comment] 2018-01-20 17:17
OK here it is
[Autosave12.zip](https://github.com/CorsixTH/CorsixTH/files/1649039/Autosave12.zip)

**Comment by pschoffer** [comment] 2018-01-20 18:53
Cool thanks. I checked your safe and everything seems to be fine (I did't get the error you mentioned).  

But when I checked the error report that you posted, I think I know what could cause the issue. I will prepare a fix for that, but it is really hard to reproduce (epidemic needs to struck a person that wasn't initialized properly).

**Comment by sionmaisley** [comment] 2018-01-20 19:03
Trust me to find a rare issue haha thanks for your help

**Comment by pschoffer** [comment] 2018-01-25 19:54
We added some more logging to be able to figure out next time what could have caused this wrong state. But as I am not able to reproduce the issue, this Is as far as I can go with it. I would suggest closing this issue.

**Comment by mugmuggy** [comment] 2020-01-16 10:16
Taking a look I seen #1431 has the same stack trace. And I've taken another look at this and found a bug and just stuffing around today, I hit the same stack trace as #1439 in a save with an extensive hospital, and these are 3 of the same basic issue.

The dead patients are meant to be removed.
https://github.com/CorsixTH/CorsixTH/blob/97553a95afea7c08a4e086d9c7c7866c6154fdba/CorsixTH/Lua/epidemic.lua#L271-L278

If 2+ removals occur, within that loop executing there is a chance that a patient that should be removed remains and a patient that shouldn't have was. This leads to a side effect of as mentioned in https://github.com/CorsixTH/CorsixTH/issues/1439#issuecomment-412723216 of the patient ui not showing up, the patient will also show the vaccination mouse cursor when hovering too.

And there could be other side effects of not removing them, then the patient ticking (after the epidemic ticking) and going back in again on the epidemic tick, especially when fax is displayed and the coverup_in_progress state changes between them.

**Comment by TheCycoONE** [comment] 2020-01-16 11:49
Going to reverse that loop as a first step @mugmuggy ?

**Comment by mugmuggy** [comment] 2020-01-16 12:37
Yep, its only minor. There are other potential issues around the infected flag being used, but there are no cases supplied where gbv.EpidemicConcurrentLimit comes into play. And that checkPatientsForRemoval should probably be called from Epidemic:startCoverUp just before the coverup_in_progress flag is set which in theory addresses the epidemic-entity-ui tick, where the entity is fed up and leaving.

Ideally still need to address the DieActions being interrupted, today as I didn't build anything I assume its the rerouting of patients due to queue depth, as they'll be zombies, going through the rest of the motions, never to die again.

**Comment by lewri** [comment] 2020-06-09 14:35
May be resolved by PR #1579

**Closed** 2020-06-09 21:34 UTC
