### ISSUE TITLE
Staff members getting stuck - selectable but not moveable

### ISSUE THREAD

**Issue by McSlurryHole** [CorsixTH/CorsixTH#149] opened 2014-01-16 06:01 UTC
1. selecting one of these "stuck" staff members and firing them then immediately hiring another staff member will cause the "an error has occurred" tool tip to pop up and the new staff member will be stuck as well.

What is the expected output? What do you see instead?
- after an error occurs a staff member will be stuck in place, the staff  member is still able to be selected and fired, but you cannot move the staff member.

What version of CorsixTH are you using (e.g. "0.21", "SVN r123")?
- I am using version 0.3

What operating system / compile settings are you using?
- Windows 7 64bit

What level was this on (e.g. "Demo level", "Full game level 12")?
- Campaign level 7,8

**Comment by Alberth289346** [comment] 2016-05-12 20:07
Looks like the machine was not reachable, judging by the error.
Since the link to the save is dead as well, and the issue is quite old, I am closing this one. If you encounter it again, please make a new issue.

fwiw, a stuck staff member means the game is already derailed, trying to do anything at that point is without guarantees that it will work. Such save games are also not useful for debugging, it needs a savegame just before things go wrong

**Comment by MarkL1961** [comment] 2016-05-12 21:42
@Alberth289346  save is available

https://drive.google.com/folderview?id=0B0HUYrWk9OBjbE43M3BZT1ZuQnM&usp=sharing

**Comment by lewri** [comment] 2020-07-23 10:31
I can no longer replicate this (had a game with a stuck doctor) in 0.64.
Going to close and assume resolved.

**Closed by lewri** 2020-07-23 10:31 UTC
Labels: Investigating
