### ISSUE TITLE
[Bug] Color contrast degradation since CorsixTH 0.67.0

### ISSUE THREAD

**Issue by ARGAMX** [CorsixTH/CorsixTH#2713] opened 2024-11-06 18:29 UTC
### Describe the issue

CorsixTH lost some color contrast between 0.66.0 and 0.67.0.
0.66.0 colors is looks like vanilla Theme Hospital colors.
0.67.0 colors is faded.

0.68.0 have the same faded colors as 0.67.0.
looks like regression in 0.67.0.

Most noticeable on the green benches and the red vending machine.
two GIFs for demonstration: (gif compressed and lost some initial png quality, but still noticeable)

![merged-screensots-colors-66-67_1](https://github.com/user-attachments/assets/cfad90ee-608a-4988-ae5f-535b6c7d6017)

![merged-screensots-colors-66-67_2](https://github.com/user-attachments/assets/210e4ea9-91bf-4e88-a989-c636d0150892)

### Steps to Reproduce

1. Run CorsixTH 0.66.0.
2. Load attached colors_contrast_lost.sav
3. Run CorsixTH 0.67.0
4. Load attached colors_contrast_lost.sav
5. Observe color difference.

### Expected Behaviour

Colors should be is like vanilla Theme Hospital colors.

### Save Game

[colors_contrast_lost.sav.zip](https://github.com/user-attachments/files/17651497/colors_contrast_lost.sav.zip)

### CorsixTH Version

0.67.0

### Operating System

MacOS Sonoma 14.5

**Comment by lewri** [comment] 2024-11-06 21:55
Is 0.68.0 the same too (I assume it is)

Could you also try setting direct_zoom to false in the config.txt and see if the contrast changes?

**Comment by lewri** [comment] 2024-11-07 07:32
Thanks. `nil` is `true` here for direct zoom.

I don't think we changed much else with how we draw between 0.66 and 0.67

**Comment by TheCycoONE** [comment] 2024-11-07 11:43
@ARGAMX do you know how to run a git bisect and compile?

**Comment by lewri** [comment] 2024-11-07 18:16
For reference, I can't replicate in Windows. It could be Mac specific.

**Comment by ARGAMX** [comment] 2024-11-07 18:44
> I'd be interested to know if 0.68.0 matches the colours of 0.66 or 0.67

0.68.0 have the same faded colors as 0.67.0.

**Comment by colinjmatt** [comment] 2024-11-07 19:28
Definitely a difference in colour between my builds (0.67 and earlier) and the current build from Mac Source Ports (0.67 (the new version) and up.
![1587699757-0x0-0-0](https://github.com/user-attachments/assets/9c2f7e58-11d5-4815-ad4e-b546ec8b4bb6)

**Comment by colinjmatt** [comment] 2024-11-07 19:31
I've compared with a screenshot of Theme Hospital from EA's website, and the colour gradient of the screenshot matches that of the newer builds. It looks like my builds were "too colourful" to be accurate to the original.

Left - my build
Top-right - EA screenshot
Bottom-right - Mac Source Ports build

<img width="1795" alt="Screenshot 2024-11-07 at 19 24 14" src="https://github.com/user-attachments/assets/5971b735-ede5-45cf-8617-35df744286ad">

**Comment by colinjmatt** [comment] 2024-11-07 19:34
Here's the list of dependencies and versions I used to build 0.66 & 0.67
![image](https://github.com/user-attachments/assets/5edb8835-a423-4952-b76d-131241d97c4c)

**Comment by ARGAMX** [comment] 2024-11-07 20:18
> It looks like my builds were "too colourful" to be accurate to the original.
> 
> Left - my build Top-right - EA screenshot Bottom-right - Mac Source Ports build

When I run vanilla Theme Hospital from GOG, which runs in DosBox, I see the same colourful colors as in your build (Left image). Not as EA screenshot.

**Comment by lewri** [comment] 2024-11-07 21:07
Thinking it's potentially this is an upstream SDL issue after Colin's input, some time after 2.28.2; but only applies to MacOS. @tomkidd do the Mac Source Ports build just grab the latest available SDL?

**Comment by TheCycoONE** [comment] 2024-11-07 22:45
I wonder if this is an HDR issue then

**Comment by TheCycoONE** [comment] 2024-11-07 22:56
Please try setting the environment variable SDL_RENDER_DRIVER=opengl or software

**Comment by Squall-Leonhart** [comment] 2024-11-26 06:44
> > It looks like my builds were "too colourful" to be accurate to the original.
> > Left - my build Top-right - EA screenshot Bottom-right - Mac Source Ports build
> 
> Strange, but when I run vanilla Theme Hospital from GOG, which runs via DosBox, I see the same colourful colors as in your build (Left image). Not as EA screenshot.

This doesn't mean much, the dos palettes were up to the given card of the time,  what i see in the supplied mac screenshots is colour artifacts because the range has been expanded beyond what it should be.

**Comment by Squall-Leonhart** [comment] 2024-11-26 08:52
The MacOS specific issue was fixed in https://github.com/libsdl-org/SDL/commit/d2300516c3998277c993fd4ac336fbb4ba71641a

**Comment by TheCycoONE** [comment] 2024-11-27 22:53
I saw that as well; it seems there's enough evidence that this is actually a fix rather than a regression.

**Closed by TheCycoONE** 2024-11-27 22:53 UTC
Labels: C:SDL2, bug, OS:Mac, S:Upstream

**Comment by Squall-Leonhart** [comment] 2024-11-28 08:18
That certainly does not match the previous buggy behavior, it does have slightly different colouration but there are no artifacts in the colors as there was in 0.66 on mac.
