### ISSUE TITLE
Failure message with in-game popup

### ISSUE THREAD

**Issue by h3xx** [CorsixTH/CorsixTH#1272] opened 2017-11-02 03:30 UTC
I was playing the game normally with no settings activated other than default, then an in-game window popped open a detail view of a Handyman, and it also popped up an in-game window saying "Sorry, but an error has occurred [...]" (see screenshot below)

#### Steps to Reproduce

**Inconsistently reproduced.** Unable to reproduce using the following save which was the latest auto-save before the issue:

#### Save Game

https://github.com/h3xx/garbitch/blob/bug-report-corsix-th/Autosave3.sav?raw=true

#### System Information
**CorsixTH Version:** e1bc25d7b67cbef64cefc6f3383d9f5b7243165c

**Operating System:** Linux/x86_64 (Slackware 14.2-current)

**Theme Hospital Version:** 

#### Gamelog.txt

    Created game with savegame version 117.
    Savegame version is 117 (Trunk), originally it was 117 (Trunk)
    Warning: Trying to remove nonexistant room build callback (function: 0x40224cb0) from humanoid (table: 0x41af42e8).
    Warning: Trying to remove nonexistant room remove callback (function: 0x40224c00) from humanoid (table: 0x41af42e8).
    Warning: Trying to remove nonexistant room build callback (function: 0x41a2ee58) from humanoid (table: 0x4140e088).
    Warning: Trying to remove nonexistant room remove callback (function: 0x41a2ede0) from humanoid (table: 0x4140e088).
    Warning: Trying to remove nonexistant room build callback (function: 0x407391c0) from humanoid (table: 0x40bdb200).
    Warning: Trying to remove nonexistant room remove callback (function: 0x4197ef00) from humanoid (table: 0x40bdb200).
    Error in timer handler: 
    /usr/share/games/CorsixTH/Lua/world.lua:2134: attempt to perform arithmetic on local 'y' (a nil value)
    stack traceback:
        /usr/share/games/CorsixTH/Lua/world.lua: in function 'removeObjectFromTile'
        /usr/share/games/CorsixTH/Lua/objects/litter.lua:98: in function 'remove'
        ...hare/games/CorsixTH/Lua/humanoid_actions/sweep_floor.lua:45: in function 'timer_function'
        /usr/share/games/CorsixTH/Lua/entity.lua:216: in function 'tick'
        /usr/share/games/CorsixTH/Lua/entities/staff.lua:149: in function 'tick'
        /usr/share/games/CorsixTH/Lua/world.lua:1051: in function 'onTick'
        /usr/share/games/CorsixTH/Lua/app.lua:1005: in function 'dispatch'
        /usr/share/games/CorsixTH/Lua/app.lua:906: in function </usr/share/games/CorsixTH/Lua/app.lua:901>

### Additional Info

![screenshot-2017-1101-2211](https://user-images.githubusercontent.com/615684/32308074-e6173b5e-bf51-11e7-8ff0-bb4c6e1877b2.png)

*It said I should report the issue so I am reporting it*

**Comment by TheCycoONE** [comment] 2017-11-02 12:22
Duplicate of #1155

**Closed by TheCycoONE** 2017-11-02 12:22 UTC
