### ISSUE TITLE
New fonts are messed up after toggling fullscreen mode.

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#461] opened 2014-12-23 01:59 UTC
_From [lserg...@gmail.com](https://code.google.com/u/106889504232580085254/) on January 08, 2011 11:22:28_

What steps will reproduce the problem? 1. Configure the game to run in Chinese or Russian.
2. Go to options dialog and toggle fullscreen mode.

What do you see instead?
Localized lines are replaced with white rectangles or sometimes misplaced textures and stay that way.

What version of CorsixTH are you using (e.g. "Beta 2", "SVN r123 ")? r1184 What operating system / compile settings are you using? Windows 7 x86

**Attachment:** [008.jpg](http://code.google.com/p/corsix-th/issues/detail?id=655)

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=655_

**Comment by Lego3** [comment] 2015-11-28 14:22
Closing. We have moved to SDL2 (i.e. a lot has happened...) and I can't reproduce.

**Closed by Lego3** 2015-11-28 14:22 UTC
Labels: P3 Medium, Googlecode
