### ISSUE TITLE
nil staff exception

### ISSUE THREAD

**Issue by xuancong84** [CorsixTH/CorsixTH#436] opened 2014-12-18 01:44 UTC
For 0.40rc2, I saw this stack dump in my terminal:
./Lua/rooms/pharmacy.lua line 76
staff:setNextAction{name = "walk", x = stf_x, y = stf_y}
but staff is nil

So the simple fix is to enclose the following block with "if staff~=nil then"
I am not very familiar with the code, but I think many events can occur simultaneously, so when the patient enters the pharmacy, it can be coincidentally that the nurse is lifted by the mouse, or the nurse is fired after you reject salary raise, or the nurse starts going to staff room for a rest, etc. Similar things can happen in many other scenarios. I forgot what caused this to happen. This is very rare.

**Comment by J-Shep** [comment] 2015-07-25 13:52
With *Room:commandEnteringPatient()* and *Room:commandEnteringStaff()* being sensitive to race conditions how about we make these functions execute their statements in protected call coroutines with a interrupted/failed callback response provided as a parameter?

**Comment by TheCycoONE** [comment] 2015-07-25 17:01
Why do you think a coroutine would help here? The issue is the timing of the callback, not that it's being interrupted.

**Comment by J-Shep** [comment] 2015-07-25 19:09
@TheCycoONE  I didn't properly think about how these functions work: they don't control what humanoids are doing in a room as they use it, they control what the humanoids will do when they use it by queuing up their actions in advance.

So I thought by running the algorithms for these functions in coroutines they could be interrupted by a function like: Room:abortUse(). Then the code for action callbacks wouldn't need to include if statement checks for race condition variable errors like a staff member being nil because they've been picked up. Calls to commandEnteringPatient() & commandEnteringStaff() would provide a use_aborted callback to call when a room's use had been aborted in order to tell humanoids what to do.

I also realise now that my Room:abortUse() idea could be implemented without using interruptible coroutines, if it would be worth implementing.

**Comment by J-Shep** [comment] 2015-07-25 19:48
@TheCycoONE  Your right, my idea wouldn't have worked, I didn't think through my idea before posting it.

**Comment by lewri** [comment] 2020-06-09 13:55
This issue was tagged as a priority-critical. Is it safe to assume this should be resolved by now?

**Comment by lewri** [comment] 2020-08-01 15:29
I can no longer replicate this in the current version. Unless someone else knows this error still exists I will close it.

**Closed by lewri** 2020-08-01 15:29 UTC
Labels: P1 Critical, bug
