### ISSUE TITLE
Yearly report while editing room blocks yearly report

### ISSUE THREAD

**Issue by mortengormmadsen** [CorsixTH/CorsixTH#699] opened 2015-02-20 22:26 UTC
v0.4, L5, DX, fullscreen = true width = 1280 height = 720
Had edit room open at placing doors and windows and the yearly report came up. The edit dialog was still in the background and in focus. Could not interact with yearly report - only the edit room dialog.
Expected yearly report to be in focus.

**Comment by SimplyRyan** [comment] 2015-02-21 14:45
Do you have any error reports or a save game? If so please provide them here so we can look into the issue further.

**Comment by mortengormmadsen** [comment] 2015-02-23 19:04
The game does not crash, hence no crash.
The problem occurs because of lost dialog focus. Savegame attach for convenience.

*Reproduction of the problem*
Resolution higher than standard game such the yearly report doesnt cover 100% of the window.
Fast forward to december 30'ish.
Edit an existing room.
Clear interior to place doors/windows.
Wait for the yearly report.
The yearly report comes up.
Clicking buttons/trophies works.
Click outside the report

*Problem*
Clicking buttons/trophies doesnt work - the yearly report no longer has focus and cant get it back before the edit dialog has been closed.

*Savegame at dec 30*
http://bit.ly/1D48mHl

**Comment by SimplyRyan** [comment] 2015-02-24 21:59
Thanks for the feedback, while the game didn't crash you should see some text on the window that opens with the game e.g. like this issue #682

**Comment by MarkL1961** [comment] 2015-02-25 11:47
@SimplyRyan  Would you get anything in the console?  I can't check this right now, but from what I understand it is not the game that is crashing and there is no actual error.  
The annual report has popped up whilst he is editing a room and the editing menu has kept the focus.  There is a way round it i.e. closing the edit room menu, but that is not ideal. Closing the annual report would be okay, but as it does not have the focus you cannot interact with it.  Normally the full screen menus have focus when they are open

**Comment by mortengormmadsen** [comment] 2015-02-25 18:36
@SimplyRyan @MarkL1961 is right - it's not a crash, hence no console output. Can I enable more logging somehow?

The problem can be fixed by making the yearly report modal.

**Comment by MarkL1961** [comment] 2015-02-25 19:12
@mortengormmadsen  Sometimes hitting the escape key can close an open menu, does that help?

There is no other logging available other than enabling debug.  I don't think that will help here though.
What we need to do is give the annual screen the focus when it opens and pauses the game and then the open edit room or any other menu won't make a difference as it will still be there once you close the awards screen (I think that is the last is the series)

**Comment by mortengormmadsen** [comment] 2015-02-25 20:11
Hitting ESC closes all popups and deletes the room. It's a workarround but not any better than manually clicking the X of Edit room.
(Updated  *Reproduction of the problem* - popups in general takes focus although only the Edit dialog does not allow the yearly report to get it back. Added my suggestion).

**Comment by MarkL1961** [comment] 2015-02-25 20:47
I have struggled to reproduce this and the only way I could was to ignore or move the year end screen to finish off the room.  If I close the year end screen first I don't have a problem as I can then go back to the room.
So for me the year end screen has the focus until you click away from it/behind it.

**Comment by mortengormmadsen** [comment] 2015-02-25 22:24
In my case I edited a room near the edge of the screen which caused the Edit room dialog to appear also near the edge of the screen. The problem occured because I clicked the edit room dialog something like ½s after the yearly report appeared, leaving me in the unwanted situation.

**Comment by MarkL1961** [comment] 2015-02-25 22:46
Can you upload a pic of which state the room was in at the time as there are many stages and perhaps I am not catching it at the right one?  
I will then take another look tomorrow night

**Comment by mortengormmadsen** [comment] 2015-02-26 06:55
http://bit.ly/18nQuQ4
Made a video.

**Comment by SimplyRyan** [comment] 2015-02-26 12:54
Apologies for my previous comment I read the issue as the window had frozen and the game hung. Sorry about that.

**Comment by MarkL1961** [comment] 2015-02-26 19:13
I cannot see any problem.
I start to edit the room to the same stage as you and the end of year screen pops up.  I move it out of the way and I am then able to finish off the room and go back to the end of year screen.
If you cannot do that and we are both using 0.40 I cannot think why it is you cannot complete the room!
Not sure if this will make a difference, but you could try and re-install 0.40.

**Comment by MarkL1961** [comment] 2015-02-26 19:57
@TheCycoONE @J-Shep 
I could be wrong as I have not played CTH fully for ages, but I thought the game paused at the end of year?
If the game did pause I don't think there would be an issue here as you would then have to deal with the end of year screen, then close it to continue the game and finish off the room edit in this case.
Has some change in recent months stopped the pausing or am I not remembering it correctly?

**Comment by mortengormmadsen** [comment] 2015-02-26 20:49
That is still a workarround. Yearly report should be a modal dialog in my oppinion. For the reference, the game is paused while the yearly is up (as it used to be in the original game).
Also you shouldn't be able to alter rooms while the game is paused but that is another discussion.

**Comment by MarkL1961** [comment] 2015-02-26 21:02
I hadn't noticed that the game was paused because I had slowed it down to give me time to edit the room.
You are right in that if the game is paused, then how is it you can continue editing the room?
I am not sure what modal dialog is, but if it is what I think it is, then we are in a way agreed.
That screen takes precedence and should be dealt with first.  Is this what you mean?

**Comment by mortengormmadsen** [comment] 2015-02-26 21:06
Exactly =)

**Comment by MarkL1961** [comment] 2015-02-26 21:09
In the settings menu there is an option in customise to disable building whilst on pause.
I have the setting on to allow building.  If I disable building on pause then I cannot use the edit room menu.
What setting are you using?

**Comment by MarkL1961** [comment] 2015-02-26 21:13
With the disable build option I can now produce your error.  Got there in the end :)
You are correct in saying what you say about now not being able to interact with the year end menu if you click away from it and click on the edit room menu

**Comment by MarkL1961** [comment] 2015-02-26 21:15
I'll try and look into why over the weekend, but don't let that stop anyone else from taking a look

**Comment by tobylane** [comment] 2018-02-14 21:00
Fixed, the awards (and winning fax) can be interacted with while a room is being built. Savegame https://cl.ly/pXwK

**Closed by tobylane** 2018-02-14 21:00 UTC
