### ISSUE TITLE
Patients cannot enter room

### ISSUE THREAD

**Issue by JimNasium123** [CorsixTH/CorsixTH#1466] opened 2018-09-13 16:31 UTC
#### Describe the issue

In level 3 patients suddenly could not enter the GP or General Diagnostics. I tried restarting, and again halfway through patients could not enter the GP room.

#### Steps to Reproduce
1. https://drive.google.com/file/d/1FTrL6wHHFFmAi4MTdBxWHw98e-CLpKNz/view?usp=sharing

2.

3.

#### System Information
**CorsixTH Version:** 0.62

**Operating System:** Windows 10

**Theme Hospital Version:** Origin

#### Gamelog.txt
*For information about where to find gamelog.txt see:
https://github.com/CorsixTH/CorsixTH/wiki/Frequently-Asked-Questions#where-do-i-find-the-configuration-or-the-gamelog-file*
```
Created game with savegame version 127.
Savegame version is 127 (v0.62), originally it was 127 (v0.62)
Error in timer handler: 
Lua\entities\humanoid.lua:618: Can only finish current action
stack traceback:
	[C]: in function 'assert'
	Lua\entities\humanoid.lua:618: in method 'finishAction'
	Lua\rooms\general_diag.lua:68: in field 'after_use'
	Lua\humanoid_actions\multi_use_object.lua:316: in local 'timer_function'
	Lua\entity.lua:216: in method 'tick'
	Lua\world.lua:1036: in method 'onTick'
	Lua\app.lua:1014: in function <Lua\app.lua:1011>
	(...tail calls...)
	Lua\app.lua:915: in function <Lua\app.lua:910>
```

### Additional Info
*Paste any screen shots or other additional information that might help
illustrate the problem.*

**Comment by mugmuggy** [comment] 2018-09-13 21:39
Dupe of #1104

**Closed** 2018-09-13 21:51 UTC
