### ISSUE TITLE
Main menu: Campaign: Player name: cursor doesn't line up with character

### ISSUE THREAD

**Issue by mattmill30** [CorsixTH/CorsixTH#145] opened 2014-01-16 04:20 UTC
When a name is entered, and the cursor is moved backwards (using the arrow keys), the cursor doesn't line up with the selected (editable) character.

**Comment by TheCycoONE** [comment] 2015-07-17 12:32
Duplicate of #750

**Closed by TheCycoONE** 2015-07-17 12:32 UTC
Labels: Priority-Low
