### ISSUE TITLE
Attempt to perform arithmetic on a nil value (local 'y')

### ISSUE THREAD

**Issue by cruelbob** [CorsixTH/CorsixTH#1344] opened 2018-01-29 09:44 UTC
```
An error has occurred!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The timer handler.
A stack trace is included below, and the handler has been disconnected.
Z:\Users\cruelbob\Downloads\CorsixTH\Lua\world.lua:2134: attempt to perform arithmetic on a nil value (local 'y')
stack traceback:
	Z:\Users\cruelbob\Downloads\CorsixTH\Lua\world.lua:2134: in method 'removeObjectFromTile'
	Z:\Users\cruelbob\Downloads\CorsixTH\Lua\objects\litter.lua:99: in method 'remove'
	...\Downloads\CorsixTH\Lua\humanoid_actions\sweep_floor.lua:45: in local 'timer_function'
	Z:\Users\cruelbob\Downloads\CorsixTH\Lua\entity.lua:216: in field 'tick'
	Z:\Users\cruelbob\Downloads\CorsixTH\Lua\entities\staff.lua:149: in method 'tick'
	Z:\Users\cruelbob\Downloads\CorsixTH\Lua\world.lua:1051: in method 'onTick'
	Z:\Users\cruelbob\Downloads\CorsixTH\Lua\app.lua:1008: in function <Z:\Users\cruelbob\Downloads\CorsixTH\Lua\app.lua:1005>
	(...tail calls...)
	Z:\Users\cruelbob\Downloads\CorsixTH\Lua\app.lua:909: in function <Z:\Users\cruelbob\Downloads\CorsixTH\Lua\app.lua:904>

Warning: No event handler for timer
```

**Comment by TheCycoONE** [comment] 2018-01-29 11:47
Duplicate of #1329

**Closed by TheCycoONE** 2018-01-29 11:47 UTC
