### ISSUE TITLE
Doctor freeze in GP's office and after some minutes the complete game freezes

### ISSUE THREAD

**Issue by ajaramillo** [CorsixTH/CorsixTH#694] opened 2015-02-18 01:33 UTC
Hello, I'm using CorsixTH 0.4 with the game installation bought on Origin. Also, I'm running on openSUSE 13.2. I hope you can help me!

Autosave file:

https://www.dropbox.com/s/xbn11kl8msnr8ji/Autosave1.sav?dl=0

**Comment by sadger** [comment] 2015-02-23 04:05
Do you have the output of your gamelog.txt when it freezes or console output? The file  in question will be in your .config/CorsixTH directory

**Comment by maverique** [comment] 2016-04-21 00:30
This is happening to me and it has happened in 0.50 and 0.60. 

A doctor gets stuck in the GP's office and after a few minutes it crash. In my case, if you accelerate the ingame speed it crashes faster. The game throws an error notification and asks if I want to attempt a recovery and keeps doing that every 5 seconds.

[Here's my save.](https://drive.google.com/file/d/0B9_mh8vFFnvVbnBVdmhPNnQybFU/view?usp=sharing)




Checking for CorsixTH updates...
You are running the latest version of CorsixTH.
An error has occurred!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The timer handler.
A stack trace is included below, and the handler has been disconnected.
...Games\Theme Hospital\CorsixTH\Lua\rooms\slack_tongue.lua:56: attempt to index a nil value (local 'slicer')
stack traceback:
        ...Games\Theme Hospital\CorsixTH\Lua\rooms\slack_tongue.lua:56: in method 'commandEnteringPatient'
        ...\GalaxyClient\Games\Theme Hospital\CorsixTH\Lua\room.lua:400: in method 'onHumanoidEnter'
        ...es\Theme Hospital\CorsixTH\Lua\humanoid_actions\walk.lua:356: in field 'on_next_tile_set'
        ...es\Theme Hospital\CorsixTH\Lua\humanoid_actions\walk.lua:150: in function <...es\Theme Hospital\CorsixTH\Lua\humanoid_actions\walk.lua:137>
        (...tail calls...)
        ...alaxyClient\Games\Theme Hospital\CorsixTH\Lua\entity.lua:219: in method 'tick'
        ...GalaxyClient\Games\Theme Hospital\CorsixTH\Lua\world.lua:1064: in method 'onTick'
        ...)\GalaxyClient\Games\Theme Hospital\CorsixTH\Lua\app.lua:979: in function <...)\GalaxyClient\Games\Theme Hospital\CorsixTH\Lua\app.lua:976>
        (...tail calls...)
        ...)\GalaxyClient\Games\Theme Hospital\CorsixTH\Lua\app.lua:880: in function <...)\GalaxyClient\Games\Theme Hospital\CorsixTH\Lua\app.lua:875>

**Comment by Alberth289346** [comment] 2016-04-21 15:14
I can confirm the crash, but it doesn't make sense :p

**Comment by TheCycoONE** [comment] 2016-04-21 16:03
The save game link is dead and there has been no response to the request for more information in over a year.

**Closed by TheCycoONE** 2016-04-21 16:03 UTC
Labels: State-Accepted
