### ISSUE TITLE
MD and handyman are stuck in the scanner room.

### ISSUE THREAD

**Issue by EythanF** [CorsixTH/CorsixTH#1150] opened 2016-11-02 13:22 UTC
#### Describe the issue

M.D and handyman are stuck in the scanner room (top-left). 

#### Steps to Reproduce
1. *Load save game attached to this ticket*

#### Save Game
https://mon-partage.fr/f/Ywe5O4oA/

#### System Information
Version 0.60

Linux mint 18.0, corsixth via GetDeb with ubuntu 16.04 version

**Comment by MarkL1961** [comment] 2016-11-02 19:04
It appears to be the door that is blocked to this room preventing anyone from using it.

I have a feeling this may have been fixed since 0.60, perhaps this can be confirmed?

**Comment by Alberth289346** [comment] 2016-11-03 05:41
Hi MarkL,

The reason these bugs are so hard to fix is that they are only found long after the bad part has done its dirty job, when the entire state is one big mess that is impossible to untangle.

We added more checks when actions are created, so the program will abort with an error when an "impossible" command is created, ie catch the bad part "in the act" so to say.
We hope to find the real cause in this way.

However, until someone plays the CorsixTH version in the master branch and reports such an error message, it's all just theory.

**Comment by MarkL1961** [comment] 2016-11-03 19:08
@Alberth289346 
I'll download the current master and see if some of these things happen to me then. 
With the attached save editing the room fixed the issue, but that does not find the cause.

I'll close this and open a new issue if and when I come across these error messages

**Closed by MarkL1961** 2016-11-03 19:08 UTC

**Comment by Alberth289346** [comment] 2016-11-04 05:48
Great! Thanks for testing.

**Comment by MarkL1961** [comment] 2016-11-08 19:41
I have run this same level for 5 years using a more up to date version from trunk and I am not getting any errors - which is brilliant in some ways, but annoying when you want it to go wrong......
@EythanF Can you remember what things you did prior to the staff getting stuck i.e. did you move rooms around

**Comment by EythanF** [comment] 2016-11-08 19:58
I don't remember, sorry.
