### ISSUE TITLE
[Bug] Patients loosing they 'waiting for decision' icon.

### ISSUE THREAD

**Issue by ARGAMX** [CorsixTH/CorsixTH#2633] opened 2024-09-25 16:56 UTC
### Describe the issue

Patients loosing they 'waiting for decision' icon.

<img width="215" alt="Screenshot 2024-09-25 at 20 00 47" src="https://github.com/user-attachments/assets/cb8da099-a1e7-4031-b808-33fcd3c9ce2f">

Also they actively and profession vomiting the whole hospital.

### Steps to Reproduce

1. *Load save game attached to this ticket*
2. Observe that there is 2 fax related to 'making decision'. But only 1 patient with waiting icon in Hospital.
3. Another patient is going to GP and after exit GP he will also move to 'waiting for decision' state. And soon he will loose that icon and start vomiting hospital too.

### Expected Behaviour

1. 'waiting for decision' Icon always visible until decision made.

### Save Game

[lost_waiting_deceision_icon2.sav.zip](https://github.com/user-attachments/files/17135017/lost_waiting_deceision_icon2.sav.zip)

### CorsixTH Version

0.68.0 Beta 1

### Operating System

MacOS Sonoma 14.5

**Comment by lewri** [comment] 2024-09-29 16:08
Duplicate of #2496

**Closed by lewri** 2024-09-29 16:08 UTC
Labels: bug, S:Info-given

**Comment by ARGAMX** [comment] 2024-09-29 16:26
Resolved in 0.68.0 RC 2 ✅
