### ISSUE TITLE
Game freeze

### ISSUE THREAD

**Issue by cooldaypt** [CorsixTH/CorsixTH#1598] opened 2020-04-27 11:06 UTC
#### Describe the issue
Game stops. People stop moving, nothing moves.
no sound, nothing works and the cmd windows shows the error below.

#### Steps to Reproduce
1. *Load save game attached to this ticket*
no savegame since I don't know where it was stored.
2.

3.

#### Save Game
*It is often useful for us if you have a save game from shortly before the
issue occurs that can be used to recreate the problem. Sometimes a save that
shows the issue happening may be useful as well. As GitHub currently only
supports uploading of images, you will have to upload your your savegames to
an another source such as [Google Drive](https://drive.google.com),
[Dropbox](https://dropbox.com), or
[SkyDrive/OneDrive](https://onedrive.live.com). Add the link to the file to
your issue and make the file(s) public, so we can access your gamelog or
savegame. The most important thing is to not remove these files after you
uploaded them!*

#### System Information
**CorsixTH Version:** *e.g. 0.50 or 7d886f35ca*

**Operating System:** *e.g. Windows 10*

**Theme Hospital Version:** *CD, GOG.com, Origin, or Demo*

#### Gamelog.txt
*For information about where to find gamelog.txt see:
https://github.com/CorsixTH/CorsixTH/wiki/Frequently-Asked-Questions#where-do-i-find-the-configuration-or-the-gamelog-file*
```
Paste gamelog.txt output here
```

### Additional Info
*Paste any screen shots or other additional information that might help
illustrate the problem.*

Checking for CorsixTH updates...
You are running the latest version of CorsixTH.
Warning: Removing disease "pregnant" due to missing treatment room "operating_th
eatre".
An error has occurred!
Almost anything can be the cause, but the detailed information below can help th
e developers find the source of the error.
Running: The timer handler.
A stack trace is included below, and the handler has been disconnected.
Lua\entities\humanoid.lua:906: Action queue was empty. This should never happen.

humanoid - class: Standard Female Patient
Warmth: 0.396   Happiness: 0.773   Fatigue: 0.000  Thirst: 0.491  Toilet_Need: 0
.443   Health: 0.000
Actions: []
stack traceback:
        [C]: in function 'error'
        Lua\entities\humanoid.lua:906: in method 'getCurrentAction'
        Lua\hospital.lua:698: in method 'countSittingStanding'
        Lua\hospital.lua:728: in method 'checkFacilities'
        Lua\hospital.lua:982: in method 'onEndDay'
        Lua\world.lua:1004: in method 'onTick'
        Lua\app.lua:1111: in function <Lua\app.lua:1108>
        (...tail calls...)
        Lua\app.lua:1012: in function <Lua\app.lua:1007>

Warning: No event handler for timer

**Comment by TheCycoONE** [comment] 2020-04-27 11:42
Could you fill out the issue template please.

**Comment by cooldaypt** [comment] 2020-04-27 16:24
done :) thank you

**Comment by mugmuggy** [comment] 2020-04-27 21:30
Saves are stored (assuming windows) in %APPDATA%\CorsixTH\Saves and there is Autosaves directory in there as well.

The error is the same as in #1584 so I assume its the same issue and a dead person has entered a room. Ideally the save will help determine what situation allowed it to get that to that state.

**Comment by lewri** [comment] 2020-08-30 11:29
@cooldaypt Do you still have the savegame available for this? If not we'll close.

**Comment by cooldaypt** [comment] 2020-09-02 09:55
I don't think I have.. Thank you :)

Please keep safe

A 2020-08-30 06:29, lewri escreveu:

> @cooldaypt [1] Do you still have the savegame available for this? If not we'll close. 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or unsubscribe [3].

-- 
Com os melhores cumprimentos 

Thomas Ender
00351 96 737 04 44 

Links:
------
[1] https://github.com/cooldaypt
[2]
https://github.com/CorsixTH/CorsixTH/issues/1598#issuecomment-683409145
[3]

**Comment by TheCycoONE** [comment] 2020-09-03 13:55
Closing as a duplicate of #1584 then

**Closed by TheCycoONE** 2020-09-03 13:55 UTC
Labels: Needs 'before problem' Savegame
