### ISSUE TITLE
GP's office blocked

### ISSUE THREAD

**Issue by Raffa50** [CorsixTH/CorsixTH#1350] opened 2018-02-14 12:58 UTC
I have a GP's office that is blocked (door problem?) 
patients can't enter, so I dismissed the doctor but he can't leave so now I have an unusable GP's office with patients in the queue :( (doesn't work to set queue size to 0)
#### Steps to Reproduce
1. *Load save game attached to this ticket*

2. Notice that there is a dismissed doctor in the left most GP's office, he can't leave neither I can't edit the office

#### Save Game
https://drive.google.com/file/d/12MelrcOlFPI_aIhq1yeONMlB1cqKi14r/view?usp=sharing

#### Expected Behavior
the doctor should leave the office and the GP's office should be editable or get back to work correctly
#### System Information
**CorsixTH Version:**  0.61

**Operating System:** Windows 10

**Theme Hospital Version:** From TH website / CD

#### Gamelog.txt
Created game with savegame version 122.
Savegame version is 122 (v0.61), originally it was 122 (v0.61)
Warning: Trying to remove nonexistant room build callback (function: 000001CAAD64C860) from humanoid (table: 000001CAAAAF9450).
Warning: Trying to remove nonexistant room remove callback (function: 000001CAAD226B10) from humanoid (table: 000001CAAAAF9450).
Warning: Trying to remove nonexistant room build callback (function: 000001CAAD658E00) from humanoid (table: 000001CAAAB0CA10).
Warning: Trying to remove nonexistant room remove callback (function: 000001CAAE14F200) from humanoid (table: 000001CAAAB0CA10).
Warning: Trying to remove nonexistant room build callback (function: 000001CAAD6561C0) from humanoid (table: 000001CAAAB0B290).
Warning: Trying to remove nonexistant room remove callback (function: 000001CAAE070DF0) from humanoid (table: 000001CAAAB0B290).
Warning: Trying to remove nonexistant room build callback (function: 000001CAAD642A80) from humanoid (table: 000001CAADF24FC0).
Warning: Trying to remove nonexistant room remove callback (function: 000001CAAE4E1090) from humanoid (table: 000001CAADF24FC0).
Warning: Trying to remove nonexistant room build callback (function: 000001CAAD6A5560) from humanoid (table: 000001CAAE1F5320).
Warning: Trying to remove nonexistant room remove callback (function: 000001CAADA67260) from humanoid (table: 000001CAAE1F5320).
Warning: Trying to remove nonexistant room build callback (function: 000001CAAA495080) from humanoid (table: 000001CAADF3A800).
Warning: Trying to remove nonexistant room remove callback (function: 000001CAB1A9C940) from humanoid (table: 000001CAADF3A800).
Warning: Trying to remove nonexistant room build callback (function: 000001CAAD64DB80) from humanoid (table: 000001CAADEBA430).
Warning: Trying to remove nonexistant room remove callback (function: 000001CAB1AA8410) from humanoid (table: 000001CAADEBA430).
Savegame version is 122 (v0.61), originally it was 122 (v0.61)
Warning: Trying to remove nonexistant room build callback (function: 000002694A473CD0) from humanoid (table: 000002694ADE6AD0).
Warning: Trying to remove nonexistant room remove callback (function: 000002694AE13F20) from humanoid (table: 000002694ADE6AD0).
Warning: Trying to remove nonexistant room build callback (function: 000002694A479CD0) from humanoid (table: 000002694ADD1A50).
Warning: Trying to remove nonexistant room remove callback (function: 000002695B81C910) from humanoid (table: 000002694ADD1A50).
Warning: Trying to remove nonexistant room build callback (function: 000002691D17B000) from humanoid (table: 000002694ADC6550).
Warning: Trying to remove nonexistant room remove callback (function: 000002695B427AC0) from humanoid (table: 000002694ADC6550).
Warning: Trying to remove nonexistant room build callback (function: 000002691D18A960) from humanoid (table: 000002694AB4C120).
Warning: Trying to remove nonexistant room remove callback (function: 000002695136E830) from humanoid (table: 000002694AB4C120).
Warning: Trying to remove nonexistant room build callback (function: 000002691D1817E0) from humanoid (table: 0000026951742B70).
Warning: Trying to remove nonexistant room remove callback (function: 00000269512B9C40) from humanoid (table: 0000026951742B70).
Warning: Trying to remove nonexistant room build callback (function: 000002695066A690) from humanoid (table: 00000269510415F0).
Warning: Trying to remove nonexistant room remove callback (function: 000002694AF5D240) from humanoid (table: 00000269510415F0).
Warning: Trying to remove nonexistant room build callback (function: 0000026950668B90) from humanoid (table: 00000269516C5540).
Warning: Trying to remove nonexistant room remove callback (function: 000002695B6F4770) from humanoid (table: 00000269516C5540).
Warning: Trying to remove nonexistant room build callback (function: 000002695066A210) from humanoid (table: 0000026950921DB0).
Warning: Trying to remove nonexistant room remove callback (function: 000002695B41B9D0) from humanoid (table: 0000026950921DB0).
Warning: Trying to remove nonexistant room build callback (function: 000002691D170800) from humanoid (table: 00000269517467B0).
Warning: Trying to remove nonexistant room remove callback (function: 0000026951DE2150) from humanoid (table: 00000269517467B0).
Warning: Trying to remove nonexistant room build callback (function: 000002691D171C40) from humanoid (table: 000002694A2A9510).
Warning: Trying to remove nonexistant room remove callback (function: 00000269504FB850) from humanoid (table: 000002694A2A9510).
Warning: Trying to remove nonexistant room build callback (function: 00000269506673F0) from humanoid (table: 000002691D3CF870).
Warning: Trying to remove nonexistant room remove callback (function: 0000026952FC15A0) from humanoid (table: 000002691D3CF870).
Warning: Trying to remove nonexistant room build callback (function: 00000269506589F0) from humanoid (table: 000002694A5130E0).
Warning: Trying to remove nonexistant room remove callback (function: 000002695B3FC6D0) from humanoid (table: 000002694A5130E0).
Warning: Trying to remove nonexistant room build callback (function: 000002695065F5F0) from humanoid (table: 0000026951046AB0).
Warning: Trying to remove nonexistant room remove callback (function: 00000269529A54C0) from humanoid (table: 0000026951046AB0).
Warning: Trying to remove nonexistant room build callback (function: 000002691D180160) from humanoid (table: 000002695090E3F0).
Warning: Trying to remove nonexistant room remove callback (function: 0000026953F8CCC0) from humanoid (table: 000002695090E3F0).
Error in timer handler: 
C:\Program Files\CorsixTH\Lua\humanoid_actions\walk.lua:30: Invalid value for parameter 'x'
stack traceback:
	[C]: in function 'assert'
	C:\Program Files\CorsixTH\Lua\humanoid_actions\walk.lua:30: in local 'constructor'
	C:\Program Files\CorsixTH\Lua\class.lua:74: in global 'WalkAction'
	C:\Program Files\CorsixTH\Lua\entities\humanoid.lua:727: in method 'walkTo'
	C:\Program Files\CorsixTH\Lua\rooms\psych.lua:108: in method 'loop_callback'
	...ogram Files\CorsixTH\Lua\humanoid_actions\use_object.lua:324: in local 'timer_function'
	C:\Program Files\CorsixTH\Lua\entity.lua:216: in field 'tick'
	C:\Program Files\CorsixTH\Lua\entities\staff.lua:149: in method 'tick'
	C:\Program Files\CorsixTH\Lua\world.lua:1051: in method 'onTick'
	C:\Program Files\CorsixTH\Lua\app.lua:1008: in function <C:\Program Files\CorsixTH\Lua\app.lua:1005>
	(...tail calls...)
	C:\Program Files\CorsixTH\Lua\app.lua:909: in function <C:\Program Files\CorsixTH\Lua\app.lua:904>

**Comment by da4id** [comment] 2018-02-15 20:25
Seems to be related to #1104

**Comment by mugmuggy** [comment] 2018-02-23 07:43
Same issue as discussed in #1087, as its another doctor that has reserved the door (Dr in general diagnosis)

**Comment by TheCycoONE** [comment] 2018-02-23 13:52
Closing as duplicate of #1087

**Closed by TheCycoONE** 2018-02-23 13:52 UTC
