### ISSUE TITLE
Crash when patient with transparency leaves scanner room

### ISSUE THREAD

**Issue by odstornes** [CorsixTH/CorsixTH#902] opened 2015-09-27 13:24 UTC
I seem to have encountered something causing a crash. I have no coding experience, so I don't really know where to start looking, but after a few hours of trying different things, it seems that I've narrowed the problem down to one patient. The attached savegame will crash on jun 6, a few seconds after a patient with transparency leaves the scanner room in the upper right corner of my hospital lot. Sending the patient home right before he enters stops the game from crashing. 

Link to dropbox folder with savegame: https://www.dropbox.com/sh/2bkovm5skfem0sm/AACfpwpnxPGxTuy5iC8VFdNWa?dl=0

My setup: Corsix 0,50. Windows 10 home edition, Intel i7-4702MQ CPU @ 2.20GHz 32GB RAM.

**Comment by TheCycoONE** [comment] 2015-09-27 16:16
Thanks for the report and the save game. Could you also copy in the gamelog.txt or console output from the crash?

**Comment by Alberth289346** [comment] 2015-09-28 16:30
It's a C++ crash for me.

The culprit seems to be the window with the patient walking home that is open (and walking off-world at June 6).

Could you try closing that, to check if that fixes the issue? (Clicking the scanner room patient might work because you then also close the currently open window (and open a new one with the scanner room patient).)

Crash looks somewhat random-ish. At normal speed, it doesn't crash, at speed as set by the save, it does crash, at mostly the same point, but with different addresses. One partial dump:
````gdb
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000000000043e99c in THLinkList::getDrawingLayer (this=0x945c36203d5be653)
    at /home/alberth/corsix-th/corsix_alberth_fork/CorsixTH/Src/th.h:37
37          int getDrawingLayer() {return m_drawingLayer;}
(gdb) bt
#0  0x000000000043e99c in THLinkList::getDrawingLayer (this=0x945c36203d5be653)
    at /home/alberth/corsix-th/corsix_alberth_fork/CorsixTH/Src/th.h:37
#1  0x000000000043bcad in THMap::draw (this=0x81348b8, pCanvas=0xc25ab8, iScreenX=620, iScreenY=870, iWidth=3116, 
    iHeight=1752, iCanvasX=0, iCanvasY=0) at /home/alberth/corsix-th/corsix_alberth_fork/CorsixTH/Src/th_map.cpp:890
#2  0x000000000044ec5b in l_map_draw (L=0x67a1ba8)
    at /home/alberth/corsix-th/corsix_alberth_fork/CorsixTH/Src/th_lua_map.cpp:772
#3  0x00007fc15e0a1360 in luaD_precall () from /lib64/liblua-5.3.so
#4  0x00007fc15e0b6a1d in luaV_execute () from /lib64/liblua-5.3.so
#5  0x00007fc15e0a15e0 in unroll () from /lib64/liblua-5.3.so
#6  0x00007fc15e0a0cc2 in luaD_rawrunprotected () from /lib64/liblua-5.3.so
#7  0x00007fc15e0a17f9 in lua_resume () from /lib64/liblua-5.3.so
#8  0x00000000004492ad in l_mainloop (L=0xb54108)
    at /home/alberth/corsix-th/corsix_alberth_fork/CorsixTH/Src/sdl_core.cpp:288
````
Below it is more liblua, and a few main.cpp (Src/main.cpp:186, SrcUnshared/main.cpp:85)
0x945c36203d5be653 is a random value, I also get 0x20 in another crash.

**Comment by TheCycoONE** [comment] 2015-09-28 16:50
Duplicate of #124

**Closed by TheCycoONE** 2015-09-28 16:50 UTC
