### ISSUE TITLE
corsixth crashes on windows 7

### ISSUE THREAD

**Issue by utkusen** [CorsixTH/CorsixTH#1414] opened 2018-05-29 17:14 UTC
#### Describe the issue
When I run corsixth, it crashes with this error: https://imgur.com/a/bbOAmK1

#### Steps to Reproduce
1. Install Visual C++ Redistributable for Visual Studio 2017 

2. Download demo

3. Install corsixth with related HOST directory and run it

#### System Information
**CorsixTH Version:** 0.61

**Operating System:** Windows 7 (Virtual Machine)

**Theme Hospital Version:** Demo

#### Gamelog.txt
gamelog.txt doesn't exists on described location

**Comment by TheCycoONE** [comment] 2018-05-29 18:08
The issue is outside of CorsixTH. Ensure your operating system and drivers are up to date.

Sorry there isn't much else to go on.

**Comment by TheCycoONE** [comment] 2018-09-21 11:05
@utkusen are you able to test with the latest master?

**Comment by TheCycoONE** [comment] 2019-01-29 01:16
Closing because there is no information to fix the error and no update from the submitter.

**Closed by TheCycoONE** 2019-01-29 01:16 UTC
Labels: Type-Game Crash
