### ISSUE TITLE
[Bug] Game crashes mousing over Ward Doors

### ISSUE THREAD

**Issue by MRMIdAS** [CorsixTH/CorsixTH#2495] opened 2024-02-18 04:50 UTC
### Describe the issue

Built a ward, moused over doors, game froze.
[crashy.sav.gz](https://github.com/CorsixTH/CorsixTH/files/14321188/crashy.sav.gz)

### Steps to Reproduce

1. *Load save game attached to this ticket*

2. Mouse over ward doors.

### Expected Behaviour

Mouse moves after mousing over Ward Doors

### Save Game

Save game attached to report: Yes

### CorsixTH Version

0.67

### Operating System

Win10

### Theme Hospital Version

GOG.com

### Gamelog.txt

```bash
Checking for CorsixTH updates...
You are running the latest version of CorsixTH.
An error has occurred!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The motion handler.
A stack trace is included below, and the handler has been disconnected.
Lua\game_ui.lua:485: attempt to index a nil value (field 'master')
stack traceback:
        Lua\game_ui.lua:485: in method 'onCursorWorldPositionChange'
        Lua\game_ui.lua:551: in function <Lua\game_ui.lua:539>
        (...tail calls...)
        Lua\app.lua:1102: in function <Lua\app.lua:1097>

Warning: No event handler for motion
An error has occurred!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The timer handler.
A stack trace is included below, and the handler has been disconnected.
Lua\game_ui.lua:485: attempt to index a nil value (field 'master')
stack traceback:
        Lua\game_ui.lua:485: in method 'onCursorWorldPositionChange'
        Lua\game_ui.lua:853: in method 'onTick'
        Lua\app.lua:1204: in function <Lua\app.lua:1199>
        (...tail calls...)
        Lua\app.lua:1102: in function <Lua\app.lua:1097>

Warning: No event handler for timer
```

**Comment by lewri** [comment] 2024-02-18 09:04
Thanks for the report! This is a duplicate of #2477 and will be fixed in the next release. For now, you should not build a ward or operating theatre while the game is paused.

**Closed by lewri** 2024-02-18 09:04 UTC
