### ISSUE TITLE
Editing room causes an error

### ISSUE THREAD

**Issue by MarkL1961** [CorsixTH/CorsixTH#133] opened 2014-01-11 19:18 UTC
Load the save and edit the slack tongue clinic and you get this error

Error in buttonup handler: 
...pidemics\CorsixTH\Lua\humanoid_actions\seek_room.lua:110: attempt to index field 'hospital' (a nil value)
stack traceback:
	...pidemics\CorsixTH\Lua\humanoid_actions\seek_room.lua:110: in function 'action_seek_room_no_treatment_room_found'
	...pidemics\CorsixTH\Lua\humanoid_actions\seek_room.lua:287: in function '?'
	...imental-epidemics\CorsixTH\Lua\entities\humanoid.lua:551: in function 'Humanoid_startAction'
	...imental-epidemics\CorsixTH\Lua\entities\humanoid.lua:618: in function 'setNextAction'
	...orsixTH-experimental-epidemics\CorsixTH\Lua\room.lua:95: in function 'callback'
	...orsixTH-experimental-epidemics\CorsixTH\Lua\room.lua:808: in function 'deactivate'
	...orsixTH-experimental-epidemics\CorsixTH\Lua\room.lua:815: in function 'tryToEdit'
	...ixTH-experimental-epidemics\CorsixTH\Lua\game_ui.lua:520: in function <...ixTH-experimental-epidemics\CorsixTH\Lua\game_ui.lua:481>
	(tail call): ?
	(tail call): ?
	...CorsixTH-experimental-epidemics\CorsixTH\Lua\app.lua:740: in function <...CorsixTH-experimental-epidemics\CorsixTH\Lua\app.lua:735>

https://www.dropbox.com/s/2umrgixkwf81hkg/Autosave7.sav

there may be a connection to http://code.google.com/p/corsix-th/issues/detail?id=794, although with that issue it is usually diag rooms

**Comment by J-Shep** [comment] 2015-05-21 16:28
The problem was that a destroyed patient wasn't removed from this room's "humanoids_enroute" set because enroute patients aren't removed from this set when they are sent home or die. I will fix this later.

**Comment by TheCycoONE** [comment] 2015-06-10 12:48
Originally reported against v0.10 as seen in #497

**Comment by J-Shep** [comment] 2015-06-10 22:06
I will submit pull request with a fix by Saturday, I'm sorry didn't fix this 2 weeks ago when I had identified the cause of this problem.

**Comment by J-Shep** [comment] 2015-07-16 22:53
>> The problem was that a destroyed patient wasn't removed from this room's "humanoids_enroute" set because enroute patients aren't removed from this set when they are sent home or die.

I intend to submit a pull request with a fix for this tomorrow.

**Comment by J-Shep** [comment] 2015-07-19 18:46
Having dead and/or sent home patients in a room's humanoids_enroute list doesn't cause errors to occur when the room is edited. So I don't yet know what the cause of this issue is.

**Comment by J-Shep** [comment] 2015-07-20 11:02
I've found the root problem but I don't yet how it happens: in both the auto saves provided for #133 and #497 the patients in room.humanoids_enroute who have nil hospitals are patients who's last_room was the Research Room & the autopsy machine's use action queuing code is where the only "patient.hospital = nil" statement is located.

So patients who should have ceased to exist after using the autopsy machine have somehow ended  being referenced in the humanoids_enroute table for a treatment room they required and this problem has existed since 0.10.

**Comment by J-Shep** [comment] 2015-07-20 20:17
>> So patients who should have ceased to exist after using the autopsy machine have somehow ended being referenced in the humanoids_enroute table for a treatment room they required...

This happens when a new treatment room is made for the first time just as a patient requiring it has started using the autopsy machine and therefore can't abort this compulsory action to go to the new treatment room.

I intend to submit a pull request with a fix tonight or tomorrow.

**Closed** 2015-07-23 00:21 UTC
Labels: Priority-Medium, State-Fixed, Type-Game Error
