### ISSUE TITLE
Allow for choosing MIDI Devices

### ISSUE THREAD

**Issue by ryanedgewurth** [CorsixTH/CorsixTH#2180] opened 2022-05-30 10:46 UTC
### What feature or enhancement would you like to add?

The ability to select a MIDI Device that isn't the Microsoft GS Wavetable Synth would be nice.

### How would this feature benefit the gameplay of CorsixTH?

In Windows 8,8.1,10 and 11, there is no way to select a default midi mapper.

This means that even if an external MIDI Device (e.g SOUND-Canvas) or an internal MIDI Device (e.g SoundBlaster 16) is used, due to how Windows dynamically assigns IDs, and the fact that CorsixTH uses port 0 by default (i.e - the ever hated gm.dls), it would make sense for an option to be available so there is no need for an external app to be used.

### Was the feature in the original game?

Yes

### What version of CorsixTH are you using?

0.65.1

### Does this feature/enhancement relate to a current problem?

No

### Additional Information

The option **sort of** existed in Theme Hospital's original game.

Both when installing, and in <root>/SOUND/, there exists an application to set your sound device from a set of options, such as the SOUND-Canvas (MPU401) or SoundBlaster.

**Comment by TheCycoONE** [comment] 2022-05-30 20:41
Duplicate of #1236

**Closed by TheCycoONE** 2022-05-30 20:41 UTC
