### ISSUE TITLE
[Bug] Game gets stuck after hover over door

### ISSUE THREAD

**Issue by cewbdex** [CorsixTH/CorsixTH#2389] opened 2023-08-22 21:44 UTC
### Describe the issue

Game got stuck after hovering over bedroom door. I can't resume it and I can't resume from paused

### Steps to Reproduce

1. *Load save game attached to this ticket*

2. Hover over bedroom door.

How I managed to do this
1. Started game, paused, built the hospital, wanted to hire a nurse, selected a nurse to hire, when selecting where to place her, hover over bedroom door. The mouse got stuck, but I can call menus via keyboard, but not resume the game.

### Expected Behaviour

Not get stuck

### Save Game

Save game attached to report: Yes
[quicksave.zip](https://github.com/CorsixTH/CorsixTH/files/12413238/quicksave.zip)

### CorsixTH Version

0.67 fedora build

### Operating System

Fedora 38

### Theme Hospital Version

CD

**Comment by lewri** [comment] 2023-08-23 19:36
Reproduced -- to produce this bug the entire ward has to be created from start to finish while game is paused.

**Comment by cewbdex** [comment] 2023-08-24 08:30
Yes, I confirm I did it this way.

**Comment by lewri** [comment] 2023-09-02 15:58
The fix for this would be to disregard the 'slave' door's hover by mouse if it hasn't been associated yet with the 'master' door.
Or a deeper fix is assigning both doors to the room but would require a lot more code change.

**Comment by lewri** [comment] 2023-10-03 19:16
2 other replications in Discord server

**Comment by lewri** [comment] 2023-10-03 19:47
I don't know what the correct approach is for this.

_I'd like both side of the doors to be associated to the room at creation_ but I'm not sure if that's correct.
The easiest solution is this, but this might just be band-aiding:

```lua
-- Find the room associated with the current entity (Usually only applies to doors)
  if entity and not room then
    if entity.room then
      room = entity.room
    elseif entity.object_type and entity.object_type.id == "swing_door_left" and
        entity.master then
      -- Special case to catch the non-dominant side of a double-door
      -- However, if created while paused the double-doors aren't associated to each other
      room = entity.master.room
    end
  end
```

**Comment by Alberth289346** [comment] 2023-10-04 16:17
Construct the right door first in the world and then the left door.
At the point in time when you create the second door, the right-door constructor code has already run.

I suggested another solution in the chat while discussing this previously but it looks like it wasn't copied to this issue.  
Build one door only and skip building the other one. The latter door is instead created by the former door, so you get full control about existence of doors in the code and can safely create all needed links.

**Comment by lewri** [comment] 2023-10-04 17:23
> Construct the right door first in the world and then the left door

This is probably the easiest path to take

**Comment by Alberth289346** [comment] 2023-10-04 17:50
That's the bad order :p

Likely the map is walked in increasing index while creating objects for them, so depending on the side of the building doors are built in different order.

**Comment by tobylane** [comment] 2023-10-04 17:57
The right side is always the master/primary, https://github.com/CorsixTH/CorsixTH/blob/142513007e184fdedb62c1686833c3cb5c02f34c/CorsixTH/Lua/dialogs/edit_room.lua#L488

**Comment by Alberth289346** [comment] 2023-10-04 18:46
Yes, so building the right door first fails to make the connection.
By waiting one tick, you ensure all objects have been constructed, so the other door object must exist.

So basically waiting 1 tick is a way not to have to worry about build order.

**Comment by Alberth289346** [comment] 2023-10-05 13:55
"Proof" is mostly describing why your solution is a good solution. In other words, how did you reach the conclusion your change is ok?

If you don't know how to convince yourself (or us):

- Testing is one option. Extend the code that tries to connect the doors for testing with printing a result. In that way you can see what happens.
- More robust towards the future, `assert` that the connection is made. This is quite tricky if you try more than one time.
- Checking (and perhaps asserting) afterwards is also an option.
  It has to be a spot that is always happening, and happening after "build" is done, and before any potential use. Eg closing the build window, or pressing "done" or so, but there may be other useful spots (I am not much in favor of sticking these things in the UI because it makes the check dependent on how the room was constructed (loading a file would not do checking, for example).

If you test, try to be thorough. Test with doors in all orientations, and probably both for the entry door and the ward door, although I am not sure if these work in the same way wrt connecting.

**Comment by lewri** [comment] 2023-10-07 22:04
Was there a decision on if this requires a hotfix patch yet?

**Closed** 2023-12-11 12:14 UTC
Labels: P2 High, T:Regression, bug, S:Reproducible
