### ISSUE TITLE
Doctor will not come to room with one patient in queue

### ISSUE THREAD

**Issue by Glimmer-Man** [CorsixTH/CorsixTH#441] opened 2014-12-21 10:57 UTC
I choose to report this - there is one patient in queue, and doctor will not come... I have many doctor walking around and no one is called. If any other patient come (so it will be two patiens in queue), doctor will come too. But that one patient will wait very long time, if other patient not comming. Sometimes he waits until he die.

This is in all version of 0.40.
![screenshot6](https://cloud.githubusercontent.com/assets/9609391/5517919/70341aec-8908-11e4-8f00-8309dffedf54.jpg)

**Comment by Glimmer-Man** [comment] 2015-01-06 12:21
New game makes no difference - still patients dying or leaving angry beacause they waiting alone for room very, very long time.

The mystery is that expected zero even if patient heading to that room. There must be a situation, which is not running expected() function...

And as well there must be a situation which is not running unexpected() function for #444

**Comment by J-Shep** [comment] 2016-05-22 21:49
I will try to fix this issue.

**Comment by J-Shep** [comment] 2016-05-22 23:14
@Glimmer-Man Thanks for reporting this problem last year and providing us with lots of information to help us investigate it.

Having loaded the saved game you provided I can see that patient 3 isn't expected for room 1 in your screenshot because their "queue" action for this room has been started removing them from this room's list of expected patients and then setting their dynamic info to "Ve front pro GP's office": Czech for "patient queueing for...":

![image](https://cloud.githubusercontent.com/assets/6353342/15457103/309f1c04-207b-11e6-9ae7-805bd3e307ea.png)

**Comment by J-Shep** [comment] 2016-05-23 10:07
I've been able to reproduce this error using the saved game @Glimmer-Man provided and patient 3: having emptied the hospital of all humanoids except patient 3, I hired one doctor and then deleted the GP's office she was queuing for. When she goes to a different GP's office the one doctor in the hospital isn't called to it.

**Comment by J-Shep** [comment] 2016-05-23 12:22
The problem is that the doctor is called having the called assigned to staff.on_call and printed in his info dump but for some reason he never reacts to the call.

**Comment by J-Shep** [comment] 2016-05-23 13:35
Actually I had some how managed to accidentally delete the statement in _CallsDispatcher:callForStaffEachRoom(..)_ which sends staff to rooms when they are called so I've not managed to reproduce this error yet.

**Comment by J-Shep** [comment] 2016-05-26 19:37
I'm encountering problems with doctors not answering calls in a simple level 1 0.60 hospital I've made which just has 2 GP offices, 1 General Diagnosis and one idle doctor in the general diagnosis room with 2 patients waiting for doctors to attend each GP office:
1) Patient A is waiting for a doctor to attend GP office A, there are currently no doctors.
2) Patient B walks from reception to GP office B before they reach it I hire a doctor dropping him in the general diagnosis room, despite this room having no queue of patients this idle doctor does not go to GP office A to answer the first doctor call for patient A.
3) Patient B arrives at GP office B and the doctor still doesn't leave the general diagnosis room to answer this new staff call.

![image](https://cloud.githubusercontent.com/assets/6353342/15587533/980f1d04-2381-11e6-8bd2-39310b69563b.png)


I've used the ["Meld"](http://meldmerge.org/) file comparison program to compare the staff call related scripts (calls_dispatcher.lua, seek_room.lua & room.lua) from the trunk with the scripts from 0.40 and I can see that only a few very minor changes have been made to the code related to staff calls: removed white spaces, coding convention changes and one IF statement being used slightly differently to make the code in its parent function more readable.

**Comment by MarkL1961** [comment] 2016-05-26 19:40
Just to rule out something daft what is the staff policy regarding rooms and leaving them?

**Comment by J-Shep** [comment] 2016-05-26 21:48
Staff are aloud to leave rooms, I will fix that issue. I don't think it could have caused the problem @Glimmer-Man experienced because in his saved game he had idle doctors outside the staffroom and idle doctors not in rooms certainly do answer staff calls.

**Comment by J-Shep** [comment] 2016-05-26 22:37
I've realised what I thought was a problem must be an intentional decision: if a player puts a doctor/nurse in a room they will want them to stay there until they've treated at least one patient which is the case now - doctors in a room only check for calls to answer after they've dealt with a patient where as when they are outside a room they checks for staff calls to answer whenever they start a meander action.

**Comment by Lego3** [comment] 2016-05-27 05:25
That sounds unintentional to me actually. And hard for the player to understand what is going on. Good find! I propose that you let the doctor answer calls immediately on put-down.

**Comment by J-Shep** [comment] 2016-05-27 11:29
@Lego3 I've changed this in my new pull request: #1077

Regarding this issue @Glimmer-Man opened, having spent a lot of time investigating it I've still not been able to reproduce this problem he experienced in 0.40, using 0.60.

As I've mentioned in an earlier comment, I've used a file comparison program to compare the 0.60 scripts related to staff calls (calls_dispatcher.lua, meander.lua, room.lua and seek_room.lua) with their 0.40 earlier versions and no changes have been made to staff call related code besides white space removals, coding convention changes and one if statement having been modified to make its parent function more readable.

Having closely examined the staff calling code I can't find anything wrong with it to explain why the patient in @Glimmer-Man 's saved game has gone to an empty GP office  without the seek_room action they would have used calling a doctor to this room or if it didn't because there was a doctor in the room who then exited before patient 3 (see @Glimmer-Man 's screenshot) arrived: how Room:onHumanoidLeave(humanoid) failed to call a new doctor to this room.

Using the following debug script code I can see that the calls dispatcher has no queued call for this room (door entrance tile at 106, 74), I can see that there's no doctor with a queued action to bring them to this room and I can see that there's no doctor going somewhere who's last room was this room:

```
local dispatcher = TheApp.world.dispatcher
for object, queue in pairs(dispatcher.call_queue) do
  if class.is(object, Room)then
    local x, y = object:getEntranceXY()
    if x == 106 and y == 74 then
      print("==== FOUND Staff Call ==== \n\n")
    end
  end
end

for _, staff in ipairs(TheApp.world.entities) do
  if class.is(staff, Staff) and staff.humanoid_class == "Doctor" then
    for _, action in ipairs(staff.action_queue) do
      if action.name == "walk" and action.x == 106 and action.y == 74 then
        print("==== FOUND Enroute Doctor ==== \n\n")
      end
    end
  end
end

for _, staff in ipairs(TheApp.world.entities) do
  if class.is(staff, Staff) and staff.humanoid_class == "Doctor" then
    if staff.last_room and staff.last_room.x == 106 and staff.last_room.y == 74 then
      print("==== FOUND A Doctor Walking Away From This Room ==== \n\n")
    end
  end
end
```

When I make patient 3 go to another empty GP's office seek_room successfully calls for a doctor to attend this office.

**Comment by TheCycoONE** [comment] 2016-05-27 12:12
What happens if the doctor that was called when the patient arrives is diverted (fired or moved to another room)?

**Comment by J-Shep** [comment] 2016-05-27 14:57
>> What happens if the doctor that was called when the patient arrives is diverted (fired or moved to another room)?

Thanks for asking I hadn't considered this. The interrupt _CallsDispatcher:staffActionInterruptHandler()_ is setup when _CallsDispatcher:answerCall(humanoid) is called_: this creatse a new staff call if a staff member enroute to a room is fired, goes to a staffroom instead or is picked up and dropped in another room.

**Comment by mugmuggy** [comment] 2019-01-01 04:00
Took the save from the 2nd comment, and loaded in 0.62 with a few tweaks (the deterministic random changes) and can reproduce what I suspect is the scenario.

The issues stem from Room:tryToFindNearbyPatients, which calls Room:tryMovePatient.

My scenario has a patient enter the GP office, whilst the staff member is leaving, they sit in the chair then vacate the room. Patient receives instructions to reenter the room, and joins the end of the queue, (gets walk, use_object (bench), queue, walk (old room) at leat one patient is in front otherwise and they can't be 'stolen'.

This patient is then picked up as a candidate to move to another room. The patient receives the enter action for the new room and is Queue:expected for that door. Just before this the patient.next_room_to_visit has been updated to the new_room.

The patient has walk instruction to the old room at this stage, I guess that this walk instruction should be interrupted and replaced but doesn't necessarily occur as expected, thus when it does, the walk action unexpects the patient, but this is from the new room not the old one.

The patient still proceeds with the walk action to the new room. At this point though the Dr has finished with a patient, and checks if they can answer calls (checking Queue:getPatientSize() (in Room:onHumanoidLeave), but as the patient has unexpected again, against the new room, this results in the call for staff being skipped (no patients in queue and expected is zero).

**Comment by mugmuggy** [comment] 2019-12-30 11:23
#1567 should also help with patients entering when staff are leaving situation.

**Closed by mugmuggy** 2019-12-30 11:23 UTC
Labels: P2 High, S:Help wanted
