### ISSUE TITLE
[Bug] Can't close the "bench loop"

### ISSUE THREAD

**Issue by masterofobzene** [CorsixTH/CorsixTH#2680] opened 2024-10-18 15:51 UTC
### Describe the issue

Can't place the 2x2 bench layout. I was able to do this on the original TH.

### Steps to Reproduce

https://github.com/user-attachments/assets/bdc7566d-da8e-40c5-85a3-39515922536c

### Expected Behaviour

To be able to place the bench where the video shows, to close the "loop" of benches.
Seems dumb, but when filling the center with plants, it really helps with patient's happyness. This small strategy was used in original TH by myself back in the day.

### Have you enabled any current CorsixTH Experimental Features?

- [ ] Right mouse panning
- [ ] Falling actions

### Save Game

Save game attached to report: No

### CorsixTH Version

0.68

### Operating System

Windows 10 x64

### Theme Hospital Version

GOG.com

### Gamelog.txt

```yaml
Sorry, nothing in the log as the game (0.68) didn't generate the gamelog.txt file for me and I was left with 0.67 version log.
```

### Additional Information

0.68 not generating any new gamelog.txt files for me.

**Comment by MandrakeHorse** [comment] 2024-10-18 19:28
Both CorsixTH and Theme Hospital prevent the player from using corridor items to make sections of their own hospital inaccessible. However, it seems that CorsixTH takes a much stricter approach than Theme Hospital, as it detects that this bench layout will block off the 2x2 square inside and thus prevents the player from placing the final bench. Perhaps we should adjust how CorsixTH considers areas to be inaccessible.

(Sidenote: I noticed that if the player tries to place a corridor item which would make part of their hospital inaccessible, the Advisor doesn't appear to inform the player why they can't place that item. This will handled as a separate issue.)

**Comment by ARGAMX** [comment] 2024-10-18 20:30
I think the root of problem here is that CorsixTH don't have a 'support for blocking off areas of the hospital' feature (#826) yet. Theme Hospital have it.

So in general we are aware of this problem. But didn't resolved it yet...

The only workaround for it is to enable the 'ALLOW BLOCKING OFF AREAS' point in menu.

<img width="311" alt="Screenshot 2024-10-18 at 23 27 00" src="https://github.com/user-attachments/assets/535b4bb9-3d80-4745-8a5f-b2350d2a5170">

But to make 'Debug' menu part accessible we need to enable it in 'config.txt'.
(debug = true)

**Comment by TheCycoONE** [comment] 2024-10-19 03:40
Ckosing as duplicate of #826 

Encourage enabling that debug action and reporting any new bugs you see using it.

**Closed by TheCycoONE** 2024-10-19 03:40 UTC
Labels: bug
