### ISSUE TITLE
Typing vs shortcut keys / keypad "Enter"

### ISSUE THREAD

**Issue by juef17** [CorsixTH/CorsixTH#829] opened 2015-07-25 01:47 UTC
Greetings! I'm running CorsixTH Version 0.50 beta 2 for Windows and I encountered the following problem. When typing a filename to save a game, pressing 1 through 5 will alter the game speed as well as type the corresponding number in the textbox, which can be... disruptive of the gameplay as I name my savefiles after the date and time. Also, the "Enter" key on the numpad side of the keyboard does not, in fact, save and close the window: only the "main" Enter key does.

**Comment by TheCycoONE** [comment] 2015-07-25 02:42
Duplicate of #745

**Closed by TheCycoONE** 2015-07-25 02:42 UTC
Labels: State-Duplicate

**Comment by bobcanthelpyou** [comment] 2015-07-25 06:36
Maybe someone could add the Enter key of the numpad, it is called 'keypad enter'
```
if not handled and (char == "return" or char == "keypad enter") then
```
https://github.com/CorsixTH/CorsixTH/blob/master/CorsixTH/Lua/window.lua#L1040

**Comment by bobcanthelpyou** [comment] 2015-07-25 08:59
Added it with #831
