### ISSUE TITLE
Patients have wrong action state on info panel

### ISSUE THREAD

**Issue by lewri** [CorsixTH/CorsixTH#1609] opened 2020-05-16 18:26 UTC
#### Describe the issue
Patients are reporting they are waiting for a particular room when they are in fact in the queue for a different room completely. 

E.g. Female patient with 1/4 death skulls shows in info she is "Queueing for GPs office" with no diagnosis bar. When in fact she is in the queue for Pharmacy to receive treatment.

There is a second patient outside the Research Room door with 'EXIT' above head (i.e. leaving). Says he is "Queueing for General Diagnosis"

Unfortunately I think the thing that broke this to start with happened a long time ago.  I think it came doing this:
Deleted the staff room (wanted to move it, but knew about the editing bug). This caused the doctors in Operating Theatre to go into white labs and not accept patients (and another doctor to stay way past the staff rest level). Believe this one's a known problem. Fixed by dropping both doctors back in Operating Theatre.

I think the bug is causing a snowball effect on other patients. As it keeps cropping up for quite a while. Also to mentioned I do tend to move or rebuild rooms a lot throughout levels. Which is why it may relate to #969 

#### Steps to Reproduce
The two patients mentioned above are in this state. 

#### Save Game
https://www.dropbox.com/s/na2gcrdcg76zsrw/patientswronginfo.sav?dl=0

#### System Information
**CorsixTH Version:** 0.63

**Operating System:** W10

**Theme Hospital Version:** GOG

#### Gamelog.txt
Female patient (goto tile matches the pharmacy)
```
Clicked on:
humanoid - class: Standard Female Patient
Warmth: 0.317   Happiness: 0.997   Fatigue: 0.000  Thirst: 0.145  Toilet_Need: 0.542   Health: 0.170
Actions: [use_object - bench   must_happen, queue - Bench distance: 3 Standing: false   must_happen, walk - going to 23:31]
-----------------------------------

```

### Additional Info
I think this relates to #969 and #1602 and is breaking several things.
![image](https://user-images.githubusercontent.com/20030128/82127386-0d814980-97ab-11ea-9244-bcc13822f5a6.png)

**Comment by mugmuggy** [comment] 2020-05-17 00:12
Dupe of #1173. 969/1602 don't apply to this save at all.

**Closed** 2020-05-17 01:13 UTC
