### ISSUE TITLE
Nurse and patient are stuck in the cast remover room

### ISSUE THREAD

**Issue by l29ah** [CorsixTH/CorsixTH#1201] opened 2017-04-02 13:42 UTC
ea0e6df, GOG, Linux.
Save: https://dump.bitcheese.net/files/naxosap/megabug.sav
Not sure if related:
```
An error has occurred!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The timer handler.
A stack trace is included below, and the handler has been disconnected.
...s/CorsixTH/Lua/humanoid_actions/multi_use_object.lua:365: attempt to index field '?' (a nil value)
stack traceback:
	...s/CorsixTH/Lua/humanoid_actions/multi_use_object.lua:365: in function '?'
	/usr/share/games/CorsixTH/Lua/entities/humanoid.lua:578: in function 'Humanoid_startAction'
	/usr/share/games/CorsixTH/Lua/entities/humanoid.lua:670: in function 'finishAction'
	...r/share/games/CorsixTH/Lua/humanoid_actions/idle.lua:66: in function 'timer_function'
	/usr/share/games/CorsixTH/Lua/entity.lua:216: in function 'tick'
	/usr/share/games/CorsixTH/Lua/world.lua:1051: in function 'onTick'
	/usr/share/games/CorsixTH/Lua/app.lua:1005: in function </usr/share/games/CorsixTH/Lua/app.lua:1002>
	(tail call): ?
	/usr/share/games/CorsixTH/Lua/app.lua:906: in function </usr/share/games/CorsixTH/Lua/app.lua:901>

Warning: No event handler for timer
```

**Comment by TheCycoONE** [comment] 2017-04-04 12:07
Duplicate of #832 possibly others.

**Closed** 2017-04-04 12:08 UTC
Labels: State-Duplicate
