### ISSUE TITLE
How to specify midi output port to use an external synthesizer?

### ISSUE THREAD

**Issue by maferv** [CorsixTH/CorsixTH#1160] opened 2016-11-14 06:05 UTC
I'd like to use munt (software synthesizer which emulates the Roland MT32) to play the game midis. I checked the documentation and the config file but I can't find any references to specify the midi output port. 

I just compiled the latest git revision on GNU/Linux.

**Comment by TheCycoONE** [comment] 2016-11-14 13:43
SDL Mixer doesn't expose any midi device configuration unfortunately. There is nothing in the API for that library and I did a quick web search to see if there was any environment variable that could be used but I didn't find anything except some non-promising remarks about an older version: http://stackoverflow.com/questions/28182609/how-to-specify-device-using-sdl-mixer

If you can make it your system default midi device, CorsixTH should just use it.

**Comment by maferv** [comment] 2016-11-14 19:31
I ended up converting the XMI to midi with this software [1] and then to wav with Munt. Finally the wavs to mp3 and specificed the mp3 folder (and the right bitrate) in the config file.

[1] http://www.vgmpf.com/Wiki/index.php?title=XMI_to_MIDI

**Comment by MarkL1961** [comment] 2016-11-14 19:44
have you looked at this? (Plays the original files without conversion, but with improved quality)
https://github.com/CorsixTH/CorsixTH/wiki/Frequently-Asked-Questions#midi-music-is-too-loud-andor-volume-setting-is-ignored-ingame
I don't know whether this is just for windows or not

**Comment by lewri** [comment] 2020-06-09 14:27
Was a question, can be closed

**Comment by TheCycoONE** [comment] 2020-06-09 17:48
Duplicate of #1236

**Closed by TheCycoONE** 2020-06-09 17:48 UTC
