### ISSUE TITLE
Mouse button state stuck after clicking on drug casebook icon in patient info dialog when that disease is not in the drug casebook

### ISSUE THREAD

**Issue by daiscog** [CorsixTH/CorsixTH#1368] opened 2018-03-25 14:37 UTC
In the linked save game, invisibility is not in the drug casebook.  Patients with invisibility arrive via an emergency.  The patient details dialog for one of these patients shows the icon for the drug casebook.  Clicking on it does nothing, but the mouse button state seems to become stuck as no icons will now respond properly to being clicked.  Even pressing SHIFT-S and trying to save the game can't be done as the save dialog will not respond to clicks.

#### Steps to Reproduce
1. Load save game attached to this ticket

2. Click on an emergency patient

3. Click on the drug casebook icon in the patient details dialog.

4. Try clicking somewhere else.

#### Save Game
https://drive.google.com/file/d/18EyX-R0A9Cno30gnkS-PLGBfxgmEa7DC/view?usp=sharing

#### Expected Behavior
Clicking still works even after clicking the casebook icon.  Moreover, if the disease is not in the casebook, it should not be possible to receive an emergency for that disease.

#### System Information
**CorsixTH Version:** 0.61

**Operating System:** Linux Mint 17.1 (Cinnamon edition, 64-bit)

**Theme Hospital Version:** GOG.com

#### Gamelog.txt

```
Created game with savegame version 122.
Savegame version is 122 (v0.61), originally it was 122 (v0.61)
Savegame version is 122 (v0.61), originally it was 122 (v0.61)
Warning: Trying to remove nonexistant room build callback (function: 0x95c1600) from humanoid (table: 0x8f3d620).
Warning: Trying to remove nonexistant room remove callback (function: 0x923f8e0) from humanoid (table: 0x8f3d620).
Warning: Trying to remove nonexistant room build callback (function: 0x83c4a80) from humanoid (table: 0x83d2a30).
Warning: Trying to remove nonexistant room remove callback (function: 0x70c82d0) from humanoid (table: 0x83d2a30).
Warning: Trying to remove nonexistant room build callback (function: 0x9173a90) from humanoid (table: 0x84edfa0).
Warning: Trying to remove nonexistant room remove callback (function: 0x52599d0) from humanoid (table: 0x84edfa0).
Warning: Trying to remove nonexistant room build callback (function: 0x9fc12e0) from humanoid (table: 0x7bdbfa0).
Warning: Trying to remove nonexistant room remove callback (function: 0x86e3a90) from humanoid (table: 0x7bdbfa0).
Warning: Trying to remove nonexistant room build callback (function: 0x692eff0) from humanoid (table: 0x98bd580).
Warning: Trying to remove nonexistant room remove callback (function: 0x7eae3f0) from humanoid (table: 0x98bd580).
Savegame version is 122 (v0.61), originally it was 122 (v0.61)
Savegame version is 122 (v0.61), originally it was 122 (v0.61)
Savegame version is 122 (v0.61), originally it was 122 (v0.61)
Error in buttonup handler: 
.../../../CorsixTH/Lua/dialogs/fullscreen/drug_casebook.lua:151: attempt to index field '?' (a nil value)
stack traceback:
	.../../../CorsixTH/Lua/dialogs/fullscreen/drug_casebook.lua:151: in function 'updateIcons'
	.../../../CorsixTH/Lua/dialogs/fullscreen/drug_casebook.lua:139: in function 'selectDisease'
	.../../../CorsixTH/Lua/dialogs/fullscreen/drug_casebook.lua:92: in function 'constructor'
	...orsixTH-0.61/build/CorsixTH/../../CorsixTH/Lua/class.lua:74: in function 'UICasebook'
	...61/build/CorsixTH/../../CorsixTH/Lua/dialogs/patient.lua:322: in function 'callback'
	...rsixTH-0.61/build/CorsixTH/../../CorsixTH/Lua/window.lua:682: in function 'handleClick'
	...rsixTH-0.61/build/CorsixTH/../../CorsixTH/Lua/window.lua:1478: in function 'onMouseUp'
	...61/build/CorsixTH/../../CorsixTH/Lua/dialogs/patient.lua:228: in function 'onMouseUp'
	...rsixTH-0.61/build/CorsixTH/../../CorsixTH/Lua/window.lua:1462: in function 'onMouseUp'
	...s/CorsixTH-0.61/build/CorsixTH/../../CorsixTH/Lua/ui.lua:654: in function <...s/CorsixTH-0.61/build/CorsixTH/../../CorsixTH/Lua/ui.lua:641>
	(...tail calls...)
	.../CorsixTH-0.61/build/CorsixTH/../../CorsixTH/Lua/app.lua:909: in function <.../CorsixTH-0.61/build/CorsixTH/../../CorsixTH/Lua/app.lua:904>
```

### Screenshots

Invisibility is not in the drug casebook:

![no-invisibility-in-drug-casebook](https://user-images.githubusercontent.com/5968668/37876292-2ce2832a-3042-11e8-9461-2328494a30aa.png)

Clicking on the casebook icon in patient details dialog causes future clicks to become unresponsive:

![try-clicking-on-casebook-icon-in-patient-infobox](https://user-images.githubusercontent.com/5968668/37876294-3201df7c-3042-11e8-9185-b2000c1441b8.png)

**Comment by mugmuggy** [comment] 2018-03-26 07:49
dupe of #1156

**Closed** 2018-12-28 09:34 UTC
