### ISSUE TITLE
Last emergency patient being counted as dead

### ISSUE THREAD

**Issue by zheega** [CorsixTH/CorsixTH#1059] opened 2016-04-28 19:12 UTC
Almost every time the last emergency patient is cured I get the "booo" sound and he is counted as dead. But he survives and I get the full reward for the emergency.

#### Expected Behavior

There should be no "booo" sound and the patient not counted as dead in the death counter.

#### System Information

**CorsixTH Version: 0.60-beta2

**Operating System: Windows 10

**Theme Hospital Version: GOG.com

**Comment by TheCycoONE** [comment] 2016-04-28 19:17
Duplicate of #1050

**Closed by TheCycoONE** 2016-04-28 19:17 UTC
