### ISSUE TITLE
 use of undeclared variable 'buildTableAction2'

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#1179] opened 2016-12-15 01:29 UTC
#### Describe the issue
Some of my saves are crashing shortly after load with various operating theater errors. One I traced down was ```use of undeclared variable `buildTableAction2`

I did a git bisect and traced it to 8168bc5

#### Steps to Reproduce
1. *Load save game attached to this ticket*

2. Wait a few days

#### Save Game
https://www.dropbox.com/s/pcyfqjcjz0v9wpw/Before%20Emerg.sav?dl=0

#### Expected Behavior
No crash

#### System Information
**CorsixTH Version:** 8168bc5

**Operating System:** Windows 10

**Theme Hospital Version:** CD

#### Gamelog.txt
```
Savegame version changed from 111 (v0.60) to 115 (Trunk). The save was created using 111 (v0.60)
Error in timer handler: 
...elease\..\..\..\CorsixTH\Lua\rooms\operating_theatre.lua:300: use of undeclared variable 'buildTableAction2'
stack traceback:
	[C]: in function 'error'
	...4_2015\CorsixTH\Release\..\..\..\CorsixTH\Lua\strict.lua:43: in metamethod '__index'
	...elease\..\..\..\CorsixTH\Lua\rooms\operating_theatre.lua:300: in method 'loop_callback'
	...\Release\..\..\..\CorsixTH\Lua\humanoid_actions\idle.lua:92: in field '?'
	...ixTH\Release\..\..\..\CorsixTH\Lua\entities\humanoid.lua:578: in upvalue 'Humanoid_startAction'
	...ixTH\Release\..\..\..\CorsixTH\Lua\entities\humanoid.lua:670: in method 'finishAction'
	...\Release\..\..\..\CorsixTH\Lua\humanoid_actions\walk.lua:193: in local 'timer_function'
	...4_2015\CorsixTH\Release\..\..\..\CorsixTH\Lua\entity.lua:219: in field 'tick'
	...orsixTH\Release\..\..\..\CorsixTH\Lua\entities\staff.lua:149: in method 'tick'
	...64_2015\CorsixTH\Release\..\..\..\CorsixTH\Lua\world.lua:1055: in method 'onTick'
	..._x64_2015\CorsixTH\Release\..\..\..\CorsixTH\Lua\app.lua:1005: in function <..._x64_2015\CorsixTH\Release\..\..\..\CorsixTH\Lua\app.lua:1002>
	(...tail calls...)
	..._x64_2015\CorsixTH\Release\..\..\..\CorsixTH\Lua\app.lua:906: in function <..._x64_2015\CorsixTH\Release\..\..\..\CorsixTH\Lua\app.lua:901>
```

**Comment by Alberth289346** [comment] 2016-12-15 07:16
Looks like a duplicate of #1172 that points to https://github.com/CorsixTH/CorsixTH/blob/master/CorsixTH/Lua/rooms/operating_theatre.lua#L113

**Comment by TheCycoONE** [comment] 2016-12-15 13:46
Likely related, but not the same issue. That one has to do with saving the state, and this one has to do with the state after load (not during save).

**Comment by MarkL1961** [comment] 2016-12-15 19:34
May or may not be relevant, there is an extra r in operating twice just below line113 so it reads operatring

**Comment by TheCycoONE** [comment] 2016-12-16 01:03
For extra fun, those cannot be fixed ever :/

**Closed** 2016-12-16 13:48 UTC
Labels: Type-Game Crash
