### ISSUE TITLE
Startup Crash

### ISSUE THREAD

**Issue by nokaalma** [CorsixTH/CorsixTH#794] opened 2015-07-11 16:01 UTC
When I start the game is see this:

![unbenannt](https://cloud.githubusercontent.com/assets/13290237/8634361/33c250a0-27f6-11e5-9145-8325e61602d7.JPG)

The music still plays. Also tried with the demo, no difference.

CorsixTH 0.50 beta 1
Win 7 64-bit

**Comment by bobcanthelpyou** [comment] 2015-07-11 16:36
Duplicate of #775 

Should be fixed in CorsixTH 0.50 beta 2 (might be released tomorrow)

**Closed** 2015-07-12 10:21 UTC
Labels: State-Duplicate
