### ISSUE TITLE
Some errors while playing

### ISSUE THREAD

**Issue by carlosrd** [CorsixTH/CorsixTH#983] opened 2016-02-13 15:32 UTC
I had some issues while playing CorsixTH 0.50 at Windows 7 Home 64x. It was a Full Game, Normal dificulty, at Level 10 and 11.

First:
![sin titulo](https://cloud.githubusercontent.com/assets/2896275/13028380/bb523432-d26d-11e5-88f6-4bada05ea667.png)
![sin titulo2](https://cloud.githubusercontent.com/assets/2896275/13028384/dc16142c-d26d-11e5-97e7-ae6f937f616f.png)
![sin titulo3](https://cloud.githubusercontent.com/assets/2896275/13028390/03d11174-d26e-11e5-936c-f9a807b79dd1.png)
![sin titulo4](https://cloud.githubusercontent.com/assets/2896275/13028396/1cd9f384-d26e-11e5-94f5-3c7097c71e7f.png)

Second:
![sin titulo5](https://cloud.githubusercontent.com/assets/2896275/13028400/4c5f80e2-d26e-11e5-9efc-4c56e8c64ecd.png)

Cannot upload Saved Game before errors ocurred. I only have Saved Games after them.
By the way, Is it normal that in level 10 I only have epidemies and not urgencies?

If it's needed more information, let me know.

**Comment by sadger** [comment] 2016-02-13 18:56
Do you have a save game you can provide when these errors are about to occur? Any more information about when they occur? Is it caused by a doctor or a patient for example?

Epidemics and emergencies cannot happen at the same time because both use the timer, I think the later levels have a lot of contagious patients, so that is what might be causing it. Again a save might be useful in trying to balance this.

**Comment by TheCycoONE** [comment] 2016-02-13 19:11
Potential duplicate of #499 ?

Please keep separate issues separate or else they become difficult to manage.

**Comment by mugmuggy** [comment] 2020-01-14 09:55
Fixed with #1567

**Closed by mugmuggy** 2020-01-14 09:55 UTC
Labels: State-Needs 'before problem' Savegame
