### ISSUE TITLE
Game freeze when try to remove Inflator room

### ISSUE THREAD

**Issue by bobcanthelpyou** [CorsixTH/CorsixTH#780] opened 2015-07-03 13:52 UTC
I want to remove the Inflator room, when i try so the game freeze with the following error message:

```
An error has occured!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The buttonup handler.
A stack trace is included below, and the handler has been disconnected.
./Lua/dialogs/place_objects.lua:338: bad argument #1 to '(for generator)' (table expected, got nil)
stack traceback:
	[C]: in function '(for generator)'
	./Lua/dialogs/place_objects.lua:338: in function 'setActiveIndex'
	./Lua/dialogs/place_objects.lua:238: in function 'addObjects'
	./Lua/dialogs/edit_room.lua:607: in function 'returnToDoorPhase'
	./Lua/dialogs/edit_room.lua:191: in function 'callback'
	./Lua/window.lua:664: in function 'handleClick'
	./Lua/window.lua:1445: in function 'onMouseUp'
	./Lua/dialogs/place_objects.lua:453: in function <./Lua/dialogs/place_objects.lua:452>
	(tail call): ?
	./Lua/window.lua:1429: in function 'onMouseUp'
	./Lua/ui.lua:622: in function <./Lua/ui.lua:609>
	(tail call): ?
	(tail call): ?
	(tail call): ?
	./Lua/app.lua:777: in function <./Lua/app.lua:772>

Error in buttonup handler: 
./Lua/dialogs/place_objects.lua:338: bad argument #1 to '(for generator)' (table expected, got nil)
stack traceback:
	[C]: in function '(for generator)'
	./Lua/dialogs/place_objects.lua:338: in function 'setActiveIndex'
	./Lua/dialogs/place_objects.lua:238: in function 'addObjects'
	./Lua/dialogs/edit_room.lua:607: in function 'returnToDoorPhase'
	./Lua/dialogs/edit_room.lua:191: in function 'callback'
	./Lua/window.lua:664: in function 'handleClick'
	./Lua/window.lua:1445: in function 'onMouseUp'
	./Lua/dialogs/place_objects.lua:453: in function <./Lua/dialogs/place_objects.lua:452>
	(tail call): ?
	./Lua/window.lua:1429: in function 'onMouseUp'
	./Lua/ui.lua:622: in function <./Lua/ui.lua:609>
	(tail call): ?
	(tail call): ?
	(tail call): ?
	./Lua/app.lua:777: in function <./Lua/app.lua:772>
Warning: No event handler for buttonup
An error has occured!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The timer handler.
A stack trace is included below, and the handler has been disconnected.
./Lua/dialogs/place_objects.lua:584: attempt to index field 'orientations' (a nil value)
stack traceback:
	./Lua/dialogs/place_objects.lua:584: in function 'setBlueprintCell'
	./Lua/dialogs/place_objects.lua:784: in function 'onCursorWorldPositionChange'
	./Lua/dialogs/edit_room.lua:1284: in function 'onCursorWorldPositionChange'
	./Lua/window.lua:1295: in function <./Lua/window.lua:1291>
	(tail call): ?
	./Lua/game_ui.lua:664: in function 'onTick'
	./Lua/app.lua:878: in function <./Lua/app.lua:873>
	(tail call): ?
	./Lua/app.lua:777: in function <./Lua/app.lua:772>

Error in timer handler: 
./Lua/dialogs/place_objects.lua:584: attempt to index field 'orientations' (a nil value)
stack traceback:
	./Lua/dialogs/place_objects.lua:584: in function 'setBlueprintCell'
	./Lua/dialogs/place_objects.lua:784: in function 'onCursorWorldPositionChange'
	./Lua/dialogs/edit_room.lua:1284: in function 'onCursorWorldPositionChange'
	./Lua/window.lua:1295: in function <./Lua/window.lua:1291>
	(tail call): ?
	./Lua/game_ui.lua:664: in function 'onTick'
	./Lua/app.lua:878: in function <./Lua/app.lua:873>
	(tail call): ?
	./Lua/app.lua:777: in function <./Lua/app.lua:772>
Warning: No event handler for timer
An error has occured!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The motion handler.
A stack trace is included below, and the handler has been disconnected.
./Lua/dialogs/place_objects.lua:584: attempt to index field 'orientations' (a nil value)
stack traceback:
	./Lua/dialogs/place_objects.lua:584: in function 'setBlueprintCell'
	./Lua/dialogs/place_objects.lua:784: in function 'onCursorWorldPositionChange'
	./Lua/dialogs/edit_room.lua:1284: in function 'onCursorWorldPositionChange'
	./Lua/window.lua:1295: in function <./Lua/window.lua:1291>
	(tail call): ?
	./Lua/game_ui.lua:423: in function <./Lua/game_ui.lua:415>
	(tail call): ?
	(tail call): ?
	./Lua/app.lua:777: in function <./Lua/app.lua:772>

Error in motion handler: 
./Lua/dialogs/place_objects.lua:584: attempt to index field 'orientations' (a nil value)
stack traceback:
	./Lua/dialogs/place_objects.lua:584: in function 'setBlueprintCell'
	./Lua/dialogs/place_objects.lua:784: in function 'onCursorWorldPositionChange'
	./Lua/dialogs/edit_room.lua:1284: in function 'onCursorWorldPositionChange'
	./Lua/window.lua:1295: in function <./Lua/window.lua:1291>
	(tail call): ?
	./Lua/game_ui.lua:423: in function <./Lua/game_ui.lua:415>
	(tail call): ?
	(tail call): ?
	./Lua/app.lua:777: in function <./Lua/app.lua:772>
Warning: No event handler for motion
```

last screen:
![bildschirmfoto von 2015-07-03 14 56 59](https://cloud.githubusercontent.com/assets/4523264/8499641/254de866-2195-11e5-80bd-804517bbfa61.png)

savegame: http://www.xup.in/dl,43694783/crashinflator.sav/

**Comment by bobcanthelpyou** [comment] 2015-07-05 10:50
Maybe similar error with the Inflator room, without error message, i am stuck in the room menu.

```
Savegame version is 102 (Trunk), originally it was 102 (Trunk)
Warning: humanoid entering non-active room
An error has occured!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The buttonup handler.
A stack trace is included below, and the handler has been disconnected.
./Lua/dialogs/place_objects.lua:230: attempt to index field 'orientations' (a nil value)
stack traceback:
	./Lua/dialogs/place_objects.lua:230: in function <./Lua/dialogs/place_objects.lua:229>
	[C]: in function 'sort'
	./Lua/dialogs/place_objects.lua:229: in function 'addObjects'
	./Lua/dialogs/edit_room.lua:607: in function 'returnToDoorPhase'
	./Lua/dialogs/edit_room.lua:191: in function 'callback'
	./Lua/window.lua:664: in function 'handleClick'
	./Lua/window.lua:1445: in function 'onMouseUp'
	./Lua/dialogs/place_objects.lua:453: in function <./Lua/dialogs/place_objects.lua:452>
	(tail call): ?
	./Lua/window.lua:1429: in function 'onMouseUp'
	./Lua/ui.lua:622: in function <./Lua/ui.lua:609>
	(tail call): ?
	(tail call): ?
	(tail call): ?
	./Lua/app.lua:777: in function <./Lua/app.lua:772>

Error in buttonup handler: 
./Lua/dialogs/place_objects.lua:230: attempt to index field 'orientations' (a nil value)
stack traceback:
	./Lua/dialogs/place_objects.lua:230: in function <./Lua/dialogs/place_objects.lua:229>
	[C]: in function 'sort'
	./Lua/dialogs/place_objects.lua:229: in function 'addObjects'
	./Lua/dialogs/edit_room.lua:607: in function 'returnToDoorPhase'
	./Lua/dialogs/edit_room.lua:191: in function 'callback'
	./Lua/window.lua:664: in function 'handleClick'
	./Lua/window.lua:1445: in function 'onMouseUp'
	./Lua/dialogs/place_objects.lua:453: in function <./Lua/dialogs/place_objects.lua:452>
	(tail call): ?
	./Lua/window.lua:1429: in function 'onMouseUp'
	./Lua/ui.lua:622: in function <./Lua/ui.lua:609>
	(tail call): ?
	(tail call): ?
	(tail call): ?
	./Lua/app.lua:777: in function <./Lua/app.lua:772>
```

savegame: http://www.xup.in/dl,16318061/Autosave2.sav/

**Comment by TheCycoONE** [comment] 2015-07-07 17:01
Looks like a duplicate of #146

**Closed by TheCycoONE** 2015-07-07 17:01 UTC

**Comment by bobcanthelpyou** [comment] 2015-07-13 09:28
The first problem 'crashinflator.sav' seems to be fixed by https://github.com/CorsixTH/CorsixTH/pull/798

The second problem 'Autosave2.sav' now crashes with the following error (maybe it is a combination of the first problem and something else):

```
Will not check for updates since this is the Trunk version.
Savegame version is 102 (Trunk), originally it was 102 (Trunk)
An error has occured!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The timer handler.
A stack trace is included below, and the handler has been disconnected.
./Lua/humanoid_actions/seek_room.lua:143: attempt to compare nil with number
stack traceback:
	./Lua/humanoid_actions/seek_room.lua:143: in function 'action_seek_room_no_diagnosis_room_found'
	./Lua/humanoid_actions/seek_room.lua:292: in function '?'
	./Lua/entities/humanoid.lua:575: in function 'Humanoid_startAction'
	./Lua/entities/humanoid.lua:667: in function 'finishAction'
	./Lua/humanoid_actions/idle.lua:31: in function 'timer_function'
	./Lua/entity.lua:218: in function 'tick'
	./Lua/entities/staff.lua:149: in function 'tick'
	./Lua/world.lua:1121: in function 'onTick'
	./Lua/app.lua:878: in function <./Lua/app.lua:875>
	(tail call): ?
	./Lua/app.lua:779: in function <./Lua/app.lua:774>

Error in timer handler: 
./Lua/humanoid_actions/seek_room.lua:143: attempt to compare nil with number
stack traceback:
	./Lua/humanoid_actions/seek_room.lua:143: in function 'action_seek_room_no_diagnosis_room_found'
	./Lua/humanoid_actions/seek_room.lua:292: in function '?'
	./Lua/entities/humanoid.lua:575: in function 'Humanoid_startAction'
	./Lua/entities/humanoid.lua:667: in function 'finishAction'
	./Lua/humanoid_actions/idle.lua:31: in function 'timer_function'
	./Lua/entity.lua:218: in function 'tick'
	./Lua/entities/staff.lua:149: in function 'tick'
	./Lua/world.lua:1121: in function 'onTick'
	./Lua/app.lua:878: in function <./Lua/app.lua:875>
	(tail call): ?
	./Lua/app.lua:779: in function <./Lua/app.lua:774>
Warning: No event handler for timer
```

**Comment by TheCycoONE** [comment] 2015-07-13 12:08
Second error is a duplicate of #578
