### ISSUE TITLE
Ability to scale User Interface

### ISSUE THREAD

**Issue by retropwned** [CorsixTH/CorsixTH#2546] opened 2024-04-04 03:57 UTC
### What feature or enhancement would you like to add?

ability to scale UI: 125%, 150% etc.

### How would this feature benefit the gameplay of CorsixTH?

testing on 1440 and difficult to read what doctor is saying at bottom of screen etc.

### Was the feature in the original game?

Unsure

### What version of CorsixTH are you using?

0.67

### Does this feature/enhancement relate to a current problem?

Unsure

### Additional Information

Unsure if this topic was already discussed or if this feature already exists.

**Comment by lewri** [comment] 2024-04-04 06:36
Thank you for the submission. This is a duplicate of #1210 and still remains being looked into/help wanted.

For now only lowering your in game resolution can be used but with some lots to crispness.

**Closed by lewri** 2024-04-04 06:36 UTC
Labels: enhancement
