### ISSUE TITLE
Handymen trying to sweep outside litter

### ISSUE THREAD

**Issue by DS1992ds** [CorsixTH/CorsixTH#2014] opened 2021-07-14 15:21 UTC
hey - an annoying glitch to look into - how people queue, on the most up to date version its literally one person in and one person out with a pause in the middle - no matter the room. I currently have 32 people queuing for the ward despite there being available beds haha. its the same for the staff room - there's also a glitch on the map I have made where handymen get stuck but I'm not sure if this can be fixed, plus I don't fancy rebuilding my hospital haha

**Comment by tobylane** [comment] 2021-07-14 16:13
Please can you upload the files as a zip - the save, map and level.

**Comment by DS1992ds** [comment] 2021-07-14 16:16
[MAssive.zip](https://github.com/CorsixTH/CorsixTH/files/6817534/MAssive.zip)
hope this helps

**Comment by lewri** [comment] 2021-07-14 16:23
```lua
Error in timer handler: 
Lua\humanoid_actions\sweep_floor.lua:63: attempt to index a nil value (local 'hospital')
stack traceback:
	Lua\humanoid_actions\sweep_floor.lua:63: in field '?'
	Lua\entities\humanoid.lua:527: in upvalue 'Humanoid_startAction'
	Lua\entities\humanoid.lua:627: in method 'finishAction'
	Lua\humanoid_actions\walk.lua:187: in local 'timer_function'
	Lua\entity.lua:216: in field 'tick'
	Lua\entities\humanoids\staff.lua:122: in method 'tick'
	Lua\world.lua:1081: in method 'onTick'
	Lua\app.lua:1134: in function <Lua\app.lua:1131>
	(...tail calls...)
	Lua\app.lua:1034: in function <Lua\app.lua:1029>
Recovering from error in timer handler...
Error in timer handler: 
Lua\humanoid_actions\sweep_floor.lua:63: attempt to index a nil value (local 'hospital')
stack traceback:
	Lua\humanoid_actions\sweep_floor.lua:63: in field '?'
	Lua\entities\humanoid.lua:527: in upvalue 'Humanoid_startAction'
	Lua\entities\humanoid.lua:627: in method 'finishAction'
	Lua\humanoid_actions\walk.lua:187: in local 'timer_function'
	Lua\entity.lua:216: in field 'tick'
	Lua\entities\humanoids\staff.lua:122: in method 'tick'
	Lua\world.lua:1081: in method 'onTick'
	Lua\app.lua:1134: in function <Lua\app.lua:1131>
	(...tail calls...)
	Lua\app.lua:1034: in function <Lua\app.lua:1029>
```

**Comment by lewri** [comment] 2021-07-14 16:28
It appears the handymen want to sweep something outside the hospital
![image](https://user-images.githubusercontent.com/20030128/125658344-e7bda96a-d60e-4da9-89ff-06edb281c6f7.png)

**Comment by lewri** [comment] 2021-07-14 16:47
I think litter needs to run some more robust checks to make sure it's appeared in a hospital.
E.g.  ``Litter:setLitterType(anim_type, mirrorFlag)`` should be be automatically destroying litter if hospital is nil.

**Comment by tobylane** [comment] 2021-07-14 17:15
How did the litter get there? There is only one entrance door, so it was dropped by a patient on their way to reception. I think they shouldn't litter until after reception or door or near a vending machine?

16 handymen are on the litter, did any of them cause an error before this one?

**Comment by DS1992ds** [comment] 2021-07-14 17:17
is there litter there ??

**Comment by lewri** [comment] 2021-07-14 17:23
> 
> 
> is there litter there ??

The litter is there yes.
After some debugging I've found that ``litter`` knows about ``hospital``.... so why are we asking world to give us the hospital if litter already knows?
```lua
local hospital = litter.world:getHospital(litter.tile_x, litter.tile_y)
```

```lua
function Litter:Litter(hospital, object_type, x, y, direction, etc)
  local th = TH.animation()
  self:Entity(th)
  self.ticks = object_type.ticks
  self.object_type = object_type
  self.hospital = hospital
  self.world = hospital.world
  self:setTile(x, y)
end
```

**Comment by lewri** [comment] 2021-07-14 17:34
Tobylane the only other error of potential interest is this, but looks like an independent error to above.

```lua
Error in timer handler: 
Lua\calls_dispatcher.lua:442: call to be executed is still assigned
stack traceback:
	[C]: in function 'assert'
	Lua\calls_dispatcher.lua:442: in method 'executeCall'
	Lua\entities\humanoids\staff\handyman.lua:173: in method 'assignHandymanTask'
	Lua\entities\humanoids\staff\handyman.lua:120: in method 'searchForHandymanTask'
	Lua\calls_dispatcher.lua:340: in method 'answerCall'
	Lua\humanoid_actions\answer_call.lua:33: in field '?'
	Lua\entities\humanoid.lua:527: in upvalue 'Humanoid_startAction'
	Lua\entities\humanoid.lua:627: in method 'finishAction'
	Lua\humanoid_actions\walk.lua:187: in local 'timer_function'
	Lua\entity.lua:216: in field 'tick'
	Lua\entities\humanoids\staff.lua:122: in method 'tick'
	Lua\world.lua:1081: in method 'onTick'
	Lua\app.lua:1134: in function <Lua\app.lua:1131>
	(...tail calls...)
	Lua\app.lua:1034: in function <Lua\app.lua:1029>
Recovering from error in timer handler...
```

**Comment by lewri** [comment] 2021-07-14 17:44
Looks like sweep_floor was forgotten about during https://github.com/CorsixTH/CorsixTH/pull/1768/
So it was still asking world for a hospital even though the code in litter changed it so.

**Comment by mugmuggy** [comment] 2021-07-14 22:44
I raised the sweep_floor issue on #1563. The other reason is that the map has the parcel set outside the hospital and those tiles are accessible by the patients and appear to be within the bounds of the walls (by setting a parcel number)
![image](https://user-images.githubusercontent.com/8009292/125701412-1cfdaef4-9e47-4dfe-b06f-b2236f05cdbe.png)

They should stop vomiting if the parcel is removed. They could still then have the issue where they vomit with the despawn action and that would then trigger the above still. But I'm hoping most of those are fixed now. We also fixed our included maps with #1532 and a couple of others older ones.

**Comment by Alberth289346** [comment] 2021-07-18 11:01
I had this crash in the first campaign level:
![Screenshot from 2021-07-18 12-54-57](https://user-images.githubusercontent.com/3254232/126064659-7f2f763c-b0bf-43c4-8b7d-4484fd88645a.png)

Stack-trace is the same as at the top of this issue.
There is no hospital parcel there.

**Comment by Alberth289346** [comment] 2021-07-18 11:05
There also is no vomit there at the start of the level.

**Comment by DS1992ds** [comment] 2021-07-18 17:07
thanks for looking into that, what about the issue with the long queues to get into rooms ?

**Comment by Alberth289346** [comment] 2021-07-18 20:35
As the game crashed, it took down pretty much everything, the game is likely beyond any rescue I am afraid.

**Comment by lewri** [comment] 2021-07-19 08:00
> I had this crash in the first campaign level:
> ![Screenshot from 2021-07-18 12-54-57](https://user-images.githubusercontent.com/3254232/126064659-7f2f763c-b0bf-43c4-8b7d-4484fd88645a.png)

But why are there pond tiles in your photo?

**Comment by Alberth289346** [comment] 2021-07-19 09:34
They are in the map afaik, and since they are not visible normally, I guess the designer just kept them there. (On that note, we can still get them if you follow a patient walking home, maybe th at shoul dbe changed.)

**Comment by TheCycoONE** [comment] 2021-07-28 02:30
@lewri I'm not convinced #2015 addresses this, at least not properly. Merged because I think the change is fitting with Albert's changes from earlier.

**Comment by TheCycoONE** [comment] 2021-07-28 02:50
It looks like we need to tweak our check for where litter/vomit is allowed. We already have the proper checks for placing objects.

https://github.com/CorsixTH/CorsixTH/blob/76522412f2d646bb95ac6b38feed3c5e5ecebfc7/CorsixTH/Lua/entities/humanoids/patient.lua#L870
https://github.com/CorsixTH/CorsixTH/blob/76522412f2d646bb95ac6b38feed3c5e5ecebfc7/CorsixTH/Lua/entities/humanoids/patient.lua#L347

**Comment by lewri** [comment] 2021-07-28 07:12
You're right by the way #2015 was just to prevent crashing. While a fix is made.

**Comment by mugmuggy** [comment] 2021-07-28 21:01
I assume the vomit on the pond occured with a patient on the way to hospital, rather than leaving - as they normally occur on  the edge due to the action queue reordering. Ie canPeeOrPuke runs whilst patient is in hospital on their current tile, then the action queue is changed and the action runs at the end of that despawn walk, so the VomitAction could just 'finish' without performing anything, or the VomitAction takes x and y and if its different abort etc.

For incoming patients in CorsixTH, its a little different as they appear to vomit sooner and more often than TH. Likewise TH spawns them closer to the hospital so they would never get to these edge tiles

**Comment by mugmuggy** [comment] 2021-07-28 21:05
> 
> 
> thanks for looking into that, what about the issue with the long queues to get into rooms ?

We can consider this a dupe of #1825 just there is a few things different with toilets than ward. The issue is that your patients are dealt with too soon and we may need to look at adjusting priorities for rooms with multiple patients.

**Comment by TheCycoONE** [comment] 2021-07-29 01:23
Those pond tiles wouldn't be eligable if we included the check that the tile is part of the patient's hospital before allowing litter/vomit; they have no parcel.

**Closed** 2022-01-20 19:00 UTC
Labels: S:Accepted, P4 Low, bug, C:Map Editor
