### ISSUE TITLE
Pixel scaling of game UI

### ISSUE THREAD

**Issue by Richard-L** [CorsixTH/CorsixTH#1630] opened 2020-06-01 22:33 UTC
On higher DPI screens, the game menus are shrinking to unusable size when using native resolutions. Consider adding a pixel scaler in the settings.

This is how OpenRCT2 does it: ![ufwtIMUQ7v](https://user-images.githubusercontent.com/4934209/83461436-09228500-a469-11ea-8edf-354b632cbe64.gif)

It's very nice btw how this problem can already be remedied with the main map through the mousewheel.

**Comment by TheCycoONE** [comment] 2020-06-01 22:36
Duplicate of #1210

**Closed by TheCycoONE** 2020-06-01 22:36 UTC
