### ISSUE TITLE
CorsixTH fails on launch "Lua\app.lua:291: use of undeclared variable 'UIDirectoryBrowser'"

### ISSUE THREAD

**Issue by MVOverdijk** [CorsixTH/CorsixTH#1434] opened 2018-07-30 13:49 UTC
#### Steps to Reproduce
1. Execute CorsixTH.exe

2. Error is displayed;
_An error has occured in CorsixTH:
Lua\app.lua:291: use of undeclared variable 'UIDirectoryBrowser'
stack traceback:
[C]: in function 'error'
Lua\strict.lua:43: in meta.method '__index'
Lua\app.lua:291: in method 'init'
CorsixTH.lua:136: in main chunk
[C:] in ?_

3. Exit

#### Save Game
N/A

#### Expected Behavior
I'm expecting CorsixTH to run

#### System Information
**CorsixTH Version:** 0.62

**Operating System:** Windows 10 Enterprise Preview 17711

**Theme Hospital Version:** GOG.com

#### Gamelog.txt
N/A
### Additional Info

![screenshot](https://user-images.githubusercontent.com/16686979/43401050-be628a28-93fe-11e8-98dd-93d8281f0908.png)

**Comment by TheCycoONE** [comment] 2018-07-30 15:53
Was this installed with the Windows Installer?

**Comment by TheCycoONE** [comment] 2018-07-30 16:02
Could you add `print(path)` to CorsixTH/Lua/app.lua line 1264 and `print(file)` to CorsixTH/Lua/app.lua line 1266.
https://github.com/CorsixTH/CorsixTH/blob/master/CorsixTH/Lua/app.lua#L1264
https://github.com/CorsixTH/CorsixTH/blob/master/CorsixTH/Lua/app.lua#L1266

Then paste the full output.

**Comment by MVOverdijk** [comment] 2018-07-30 19:08
@TheCycoONE Thanks for replying! 

Yes, I've used the installer.
Installed @ D:\SteamLibrary\CorsixTH
Theme Hospital (GOG version) is installed @ D:\SteamLibrary\Theme Hospital

Added the extra code to the app.lua file 
![image](https://user-images.githubusercontent.com/16686979/43417826-60e9d520-943c-11e8-8539-c37c0eeb3c85.png)

Then ran again and here's the output;

þ╣üÚ½öõ©¡µûç    function: 000001AEDD3C3700
ita     function: 000001AEDD0B16F0
zh(s)   function: 000001AEDD2C91A0
chinese (traditional)   function: 000001AEDD3C3700
zh(t)   function: 000001AEDD3C3700
italiano        function: 000001AEDD0B16F0
zho(t)  function: 000001AEDD3C3700
chi(t)  function: 000001AEDD3C3700
chi(s)  function: 000001AEDD2C91A0
kor     function: 000001AEDD16B3E0
ðáÐâÐüÐüð║ð©ð╣  function: 000001AEDD2CA320
rus     function: 000001AEDD2CA320
italian function: 000001AEDD0B16F0
it      function: 000001AEDD0B16F0
þ«Çõ¢ôõ©¡µûç    function: 000001AEDD2C91A0
korean  function: 000001AEDD16B3E0
ru      function: 000001AEDD2CA320
Ýò£ÛÁ¡ýû┤       function: 000001AEDD16B3E0
russian function: 000001AEDD2CA320
ko      function: 000001AEDD16B3E0
original_strings        function: 000001AEDD16AEA0
chinese (simplified)    function: 000001AEDD2C91A0
zho(s)  function: 000001AEDD2C91A0
Language 'english' could not be found. Reverting to English.
An error has occurred in CorsixTH:
Lua\strings.lua:301: Language 'English' could not be found. Please verify your installation.
stack traceback:
        [C]: in function 'error'
        Lua\strings.lua:301: in method '_loadPrivate'
        Lua\strings.lua:275: in method 'load'
        Lua\app.lua:411: in method 'initLanguage'
        Lua\app.lua:231: in method 'init'
        CorsixTH.lua:136: in main chunk
        [C]: in ?

![image](https://user-images.githubusercontent.com/16686979/43417878-90ce8ae2-943c-11e8-9bb3-2805d3e46db4.png)

**Comment by TheCycoONE** [comment] 2019-01-29 01:14
Sorry, newlines before the additions Curious there's no path information printed, but I'm guessing the change caused an error.

(Sorry I missed your update)

**Comment by TheCycoONE** [comment] 2020-01-14 11:54
Closing because this isn't currently actionable and we can't reproduce.

**Closed by TheCycoONE** 2020-01-14 11:54 UTC
