### ISSUE TITLE
Money bar broken with Russian or Dutch lanuage

### ISSUE THREAD

**Issue by ruPaladin** [CorsixTH/CorsixTH#1193] opened 2017-01-28 09:12 UTC
#### Describe the issue
Money bar broken http://i.imgur.com/IS7DRYb.png

#### Steps to Reproduce
1. Start game with Russian or Dutch language.

#### System Information
**CorsixTH Version:** 0.6

**Operating System:** Windows 10

**Theme Hospital Version:** GOG.com

#### Gamelog.txt
*For information about where to find gamelog.txt see:
https://github.com/CorsixTH/CorsixTH/wiki/Frequently-Asked-Questions#where-do-i-find-the-configuration-or-the-gamelog-file*

**Comment by Alberth289346** [comment] 2017-01-30 18:04
![numbers](https://cloud.githubusercontent.com/assets/3254232/22434964/7f3d4bdc-e71e-11e6-9005-a0011e46a62d.png)

It's hard to see what is happening, so I enlarged the numbers a bit. I hope you added the red line, at least I don't know where that could come from otherwise.

You can see clearly that the font of the digits are too small, two numbers fit in one wheel.
Perhaps you are using a font that cannot provide digits of the right size?

What font do you use, and what happens if you try another font?

**Comment by MarkL1961** [comment] 2017-01-30 19:08
@Alberth289346  I wondered whether the red line is from reputation, but when I changed languages yesterday I got what you did and that was small numbers only.
Are numbers the same in all languages?  If they are could we just use the default font from TH here?

**Comment by TheCycoONE** [comment] 2017-01-30 22:11
Digits are not the same in all languages. The CJK languages use different digits as does Arabic (which we do not support) off the top of my head. That said we likely use ansi digits regardless. I didn't find any conversion for numbers. Alternatively we could use one text box per digit for this display.

**Comment by ruPaladin** [comment] 2017-02-09 13:29
Sorry for inconvenience. The problem is only with numbers. Red line was added in GIMP. I use Windows and didn't change default settings.

**Comment by PenguiN560** [comment] 2017-03-08 21:42
I also have this problem. Is there some recommendation which font is better to used for different languages for normal display?

**Comment by TheCycoONE** [comment] 2017-03-09 13:56
No unfortunately there is no known workaround for this issue. Regression bisects and/or patches are appreciated. Otherwise I'll try to get this fixed before the next major version.

**Comment by PenguiN560** [comment] 2017-03-09 16:13
@TheCycoONE oh, ok, thank you, we will hope on it. 

Also some messages on Russian language go away from message boxes and some others written over others text
![screenshot_20170309_190535](https://cloud.githubusercontent.com/assets/816595/23758838/610b5452-0504-11e7-80a9-cc7a0bc7f531.png)

**Comment by MarkL1961** [comment] 2017-03-09 20:16
I think the problem here are that the spaces in most cases were designed with only English in mind.  Often the translations are much longer as with English we have a greater variety of words that mean the same thing.
One solution I can think of is leaving these things in English and having an option where the hover text is in your chosen language.  Hover texts expand around the text so would grow to the required size.
If this was something that could be turned on and off so the player could decide which they prefer.  As there are already hover texts it could perhaps be hover + Ctrl for translation.

Is this something that could be added?  @TheCycoONE  @Alberth289346

**Comment by PenguiN560** [comment] 2017-03-10 09:46
@MarkL1961 I think you're right, but there are russian localization for Theme Hospital without this problem(I'll check it some late after work and paste screens here).

**Comment by MarkL1961** [comment] 2017-03-10 15:58
If there was a Russian version this is not mentioned in the language file.  It should be possible to add  `  Inherit("original_strings", 0)  ` to our language file.  Replace the ` 0 ` with the relevant number and the game then only uses our file for missing or new strings.

**Comment by PenguiN560** [comment] 2017-03-11 09:35
It can be nice, but CorsixTH don't work with Rus version =( it hold on first loading screen.
![th](https://cloud.githubusercontent.com/assets/816595/23822139/7ee80e5a-065f-11e7-871b-588bc98f304e.png)

**Comment by TheCycoONE** [comment] 2017-03-12 14:29
Could you open a new ticket about that?

**Comment by tiriana** [comment] 2017-05-04 12:19
Maybe it possible to add some flag like: ```use_custom_font_for_numbers```, or ```use_default_font_for_numbers``` to config? 

I'm pretty new to this project - please let me know who's actively developing it, so I can mention them.

**Comment by cwlee0223** [comment] 2018-01-21 02:06
This also happened when I used Korean language. ( : Money bar broken http://i.imgur.com/IS7DRYb.png)
I remember this bug did not occur when I used previous version of corsixTH (like 0.4).
I hope this can be fixed on next version. Thx :)

**Comment by lewri** [comment] 2020-07-29 17:01
Dutch appears to be displaying fine now.

Russian is still causing this error. It does appear for the money bar we shouldn't be using the given font in the config files.

**Comment by TheCycoONE** [comment] 2020-07-30 00:42
I believe the fix for this is to draw each digit as it's own independent text area.

**Comment by lewri** [comment] 2020-07-30 10:00
I have a more aesthetic but not ideally coded solution for this now. Since it's the only place where the bitmap font is a better fit than the language file it might be okay:

![image](https://user-images.githubusercontent.com/20030128/88910103-da037680-d253-11ea-88fd-0e72b761e4a4.png)

**Comment by TheCycoONE** [comment] 2020-08-01 17:57
Now the original font is used fixing the graphic glitch but possibly breaking i18n. Keeping open for now.

**Comment by hacker-cat** [comment] 2020-08-09 07:49
I'm using Simp Chinese language. I try to build the latest code, and the money bar looks good when starting a new game. However, when I load or continue a game from the main menu, the money bar is still broken.

**Comment by lewri** [comment] 2020-08-09 13:50
That may be a persistence problem that needs sorting I'm guessing. @TheCycoONE ?

**Comment by lewri** [comment] 2020-08-11 06:20
@hacker-cat just pushed an update for this. If you have time did you want to see if the moneybar is fixed?

**Comment by hacker-cat** [comment] 2020-08-12 12:27
It works when I load a previous game (saved before the update). However, if I load a game which is saved after the update, the money bar is still broken. I've tried both clean build and incremental build, they have the same problem.

**Comment by hacker-cat** [comment] 2020-08-12 12:41
[test000.sav.gz](https://github.com/CorsixTH/CorsixTH/files/5062671/test000.sav.gz)
Attach the savefile which is saved at the very beginning of a game by latest Trunk. @lewri

**Comment by TheCycoONE** [comment] 2020-08-12 20:49
@lewri just make the patch do it every time instead of based off save version. I'll have to look into how this is persisted later.

**Comment by lewri** [comment] 2020-08-12 21:46
Replicated. I'll patch this now.

**Comment by tobylane** [comment] 2023-11-04 13:35
The problem in part is that unicode numbers are thinner than latin, and will be a few pixels left of where we want them. This is Arial. 
![Screen 2023-11-04 at 09 55 20](https://github.com/CorsixTH/CorsixTH/assets/552285/00b50fae-bb65-41bd-b1df-fdd8c04ae7e6)

**Closed** 2024-03-16 13:05 UTC
Labels: P4 Low, T:Regression, C:Graphical
