### ISSUE TITLE
ghost images while lifting up staff

### ISSUE THREAD

**Issue by xuancong84** [CorsixTH/CorsixTH#680] opened 2015-02-08 07:00 UTC
On Linux/Ubuntu, newest version CorsixTH/CorsixTH master branch up to date 2015.2.8.
To reproduce, right click and lift up any staff, {scroll mouse to zoom} or {move your mouse for some time}, say 5s; then ghost images of the staff starts to appear with screen flickering black and white, with duplicate staff icons along the cursor trajectory.

![bug](https://cloud.githubusercontent.com/assets/10172392/6095678/d7abc6a6-afa1-11e4-81a0-e1057b3184c2.jpg)

The bug lies in Lua/dialogs/place_staff.lua : line 88
canvas:scale(zoom)

The bug can be worked around by disabling the 'if' block with scaling canvas:
if canvas:scale(zoom) then
      local x, y = self.ui:WorldToScreen(self.tile_x, self.tile_y)
      self.anim:draw(canvas, x / zoom, y / zoom)
      canvas:scale(1)
else
So that lifted-up staff is not scaled.
I suspect that is a SDL library bug, similar to Clipping bug in issue #646, because the release 0.40-rc3 also scaled the canvas, no such issue.

**Comment by pwaller** [comment] 2015-02-08 18:39
I think this may be related to or the same as #370 and #616.

**Comment by xuancong84** [comment] 2015-02-09 01:50
I confirm that it is identical to  #370
So did you encounter the same problem? And how to solve the problem?

**Comment by TheCycoONE** [comment] 2015-02-09 02:35
Closing as a duplicate of #370

**Closed by TheCycoONE** 2015-02-09 02:35 UTC
