### ISSUE TITLE
Handyman walking issue

### ISSUE THREAD

**Issue by knoedel001** [CorsixTH/CorsixTH#1457] opened 2018-09-05 11:20 UTC
Hello folks, thanks for the awesome work on the game! Maybe I found a bug:

#### Describe the issue
A message box appears, saying that an error occured. This happens when a handyman enters the inflator room and closes the door. From that point on he is unable to move. Rebuilding the room didn't fix the issue.

#### Save Game
Savegame here: [https://wiesel.de/zeug/bug.sav](https://wiesel.de/zeug/bug.sav)

#### Steps to Reproduce
1. *Load save game attached to this ticket*

2. Remove the handyman Mr. Meiermann from the inflator room and fire him. Employ a new handyman and place him next to the inflator room.

3. The newly employed handyman will walk into the inflator room to fix the machine and the error occurs just after he closes the door.

#### Edit:
In order to get my savegame working again I just removed the inflator room without rebuilding it, fired the handyman and employed a new one. The new handyman walked straight through the wall into the fracture clinic, fixed the cast removing machine and exited the fracture clinic through the wall. Video: https://www.youtube.com/watch?v=KSJk-v891nQ

#### Expected Behavior
No error should occur.

#### System Information
**CorsixTH Version:** 0.62

**Operating System:** Win10 64 Prof

**Theme Hospital Version:** ISO file from archive.org

#### Gamelog.txt
Created game with savegame version 127.
Warning: Trying to remove nonexistant room build callback (function: 000001C9B13653E0) from humanoid (table: 000001C9C2B6E560).
Warning: Trying to remove nonexistant room remove callback (function: 000001C9C29E1800) from humanoid (table: 000001C9C2B6E560).
Warning: Trying to remove nonexistant room build callback (function: 000001C9B134DBC0) from humanoid (table: 000001C9AA9DE2E0).
Warning: Trying to remove nonexistant room remove callback (function: 000001C9B0F414B0) from humanoid (table: 000001C9AA9DE2E0).
Error in timer handler: 
Lua\room.lua:313: Handyman arrived is on call but not arriving to the designated room
stack traceback:
	[C]: in function 'assert'
	Lua\room.lua:313: in method 'onHumanoidEnter'
	Lua\humanoid_actions\walk.lua:383: in local 'on_next_tile_set'
	Lua\humanoid_actions\walk.lua:232: in function <Lua\humanoid_actions\walk.lua:178>
	(...tail calls...)
	Lua\entity.lua:216: in field 'tick'
	Lua\entities\staff.lua:149: in method 'tick'
	Lua\world.lua:1036: in method 'onTick'
	Lua\app.lua:1014: in function <Lua\app.lua:1011>
	(...tail calls...)
	Lua\app.lua:915: in function <Lua\app.lua:910>
Recovering from error in timer handler...
Savegame version is 127 (v0.62), originally it was 127 (v0.62)
Error in timer handler: 
Lua\room.lua:313: Handyman arrived is on call but not arriving to the designated room
stack traceback:
	[C]: in function 'assert'
	Lua\room.lua:313: in method 'onHumanoidEnter'
	Lua\humanoid_actions\walk.lua:383: in local 'on_next_tile_set'
	Lua\humanoid_actions\walk.lua:232: in function <Lua\humanoid_actions\walk.lua:178>
	(...tail calls...)
	Lua\entity.lua:216: in field 'tick'
	Lua\entities\staff.lua:149: in method 'tick'
	Lua\world.lua:1036: in method 'onTick'
	Lua\app.lua:1014: in function <Lua\app.lua:1011>
	(...tail calls...)
	Lua\app.lua:915: in function <Lua\app.lua:910>

**Comment by TheCycoONE** [comment] 2018-09-05 14:17
This is a duplicate of #624

**Closed by TheCycoONE** 2018-09-05 14:17 UTC
