### ISSUE TITLE
Error: CorsixTH/Lua/entities/humanoid.lua:665: Can only finish current action

### ISSUE THREAD

**Issue by hnsl** [CorsixTH/CorsixTH#1233] opened 2017-07-23 21:45 UTC
#### Describe the issue

Running: The timer handler.
A stack trace is included below, and the handler has been disconnected.
CorsixTH/Lua/entities/humanoid.lua:665: Can only finish current action
stack traceback:
        [C]: in function 'assert'
        CorsixTH/Lua/entities/humanoid.lua:665: in method 'finishAction'
        CorsixTH/Lua/rooms/general_diag.lua:68: in field 'after_use'
        CorsixTH/Lua/humanoid_actions/multi_use_object.lua:316: in local 'timer_function'
        CorsixTH/Lua/entity.lua:216: in method 'tick'
        CorsixTH/Lua/world.lua:1051: in method 'onTick'
        CorsixTH/Lua/app.lua:1005: in function <CorsixTH/Lua/app.lua:1002>
        (...tail calls...)
        CorsixTH/Lua/app.lua:906: in function <CorsixTH/Lua/app.lua:901>

Warning: No event handler for timer

#### System Information
**CorsixTH Version:** 6a079fd02bc456be7410e4394d7661308e86b3bf

**Operating System:** Arch Linux 4.10.13-1-ARCH

**Theme Hospital Version:** CD

### Additional Info

Happened when I was tearing down a psychiatrists office that had a long queue.

**Comment by TheCycoONE** [comment] 2017-07-26 02:39
https://github.com/CorsixTH/CorsixTH/blob/6a079fd02bc456be7410e4394d7661308e86b3bf/CorsixTH/Lua/entities/humanoid.lua#L665 is the assert. No relevant information in that method.

https://github.com/CorsixTH/CorsixTH/blob/6a079fd02bc456be7410e4394d7661308e86b3bf/CorsixTH/Lua/rooms/general_diag.lua#L68 is more interesting.

It seems that between when the staff was assigned the idle action while the patient used the trolly, and when the patient finished the staff had already been assigned another action. I'm not sure whether tearing down the other room had any impact.

**Comment by TheCycoONE** [comment] 2017-07-26 02:43
It would be helpful for diagnosing if that assert gave a little more information about the state of the action queue; or if we had a state dump -

@hnsl is the issue reproducible or was it a one time thing?

**Comment by hnsl** [comment] 2017-07-31 15:42
Hi, I was in the middle of a game. I just kept playing, didn't try to reproduce anything. Sorry!

**Comment by bacon1986** [comment] 2017-08-04 23:13
**Describe the issue**
I had the same error occur in the middle of a game during an Earthquake in Festering-on-the-Wold. I was not interacting with any rooms at the time.

`An error has occurred!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The timer handler.
A stack trace is included below, and the handler has been disconnected.
C:\Program Files\CorsixTH\Lua\entities\humanoid.lua:667: Can only finish current action
stack traceback:
        [C]: in function 'assert'
        C:\Program Files\CorsixTH\Lua\entities\humanoid.lua:667: in method 'finishAction'
        C:\Program Files\CorsixTH\Lua\rooms\general_diag.lua:75: in field 'after_use'
        ...Files\CorsixTH\Lua\humanoid_actions\multi_use_object.lua:264: in local 'timer_function'
        C:\Program Files\CorsixTH\Lua\entity.lua:219: in method 'tick'
        C:\Program Files\CorsixTH\Lua\world.lua:1075: in method 'onTick'
        C:\Program Files\CorsixTH\Lua\app.lua:1000: in function <C:\Program Files\CorsixTH\Lua\app.lua:997>
        (...tail calls...)
        C:\Program Files\CorsixTH\Lua\app.lua:901: in function <C:\Program Files\CorsixTH\Lua\app.lua:896>

Warning: No event handler for timer`

**System Information**

CorsixTH Version: v0.60 launched through Steam.
Operating System: Windows 10 Enterprise
Theme Hospital Version: GOG.com

Additional Info
After the error my general diagnosis room is showing a glitch (see attached image). I tried to edit the room and the member of staff left but the patient didn't. I tried to send them home from their info window but they won't leave.

![thbug](https://user-images.githubusercontent.com/7498263/28990197-e76532ec-7972-11e7-9d33-2ec7fb9c7ca2.png)

**Comment by mugmuggy** [comment] 2019-01-01 23:52
Similar issues #500, #362, #858 and #650 and can be symptomatic as shown in #1104.

Cardio and General Diag both have multi use object 'controlled' by patient. Both very much the same.

https://github.com/CorsixTH/CorsixTH/blob/9de46b728c61fedf96cd1120a8040af328a55fa8/CorsixTH/Lua/rooms/cardiogram.lua#L87-L97

The last part of the code above is queuing the walk to screen and setIsLeaving(true), also a UseScreen with setIsLeaving(true) to get dressed again.

setIsLeaving(true) will allow the staff member in the room to be seen by isIdle() in particular circumstances as idle, this leads to CallDispatcher when CallDispatcher:enqueue runs to findSuitableStaff which picks up this doctor as being idle. Below snippet already assumes the staff is in a room.

https://github.com/CorsixTH/CorsixTH/blob/9de46b728c61fedf96cd1120a8040af328a55fa8/CorsixTH/Lua/entities/staff.lua#L781-L796

I wonder if removing that for loop and only checking room:getPatient():getCurrentAction():isLeaving() would be enough, the difference is, 'is leaving' or 'will be leaving'. Tested that change on save from https://github.com/CorsixTH/CorsixTH/issues/500#issuecomment-111854603 running on 0.5 and the call is passed to a different doctor and this doctor meanders in the room, as there are no other calls they are suitable for. I haven't yet replicated myself on something newer (fairly sure I've hit the issue though before but knew of the issues), but there is evidence it may occur still.

**Comment by mugmuggy** [comment] 2019-01-02 01:15
To replicate is a bit of hassle.

Must have a gowned patient in the room you want to break and meeting the requirements to hit that for loop. Doctor must receive a call to another room before using the trolley, easiest way is to edit and finish an adjacent room with waiting patients.

The doctor should pick up that call, and start leaving.

To get the issue you need another humanoid, naturally a handyman is most obvious to be using the door, when the doctor is about to leave, place a handyman that should leave immediately and they reserve and uses the door, the doctor then will need to 'queue' creating an idle action at the start of the action queue.

Multi use object action will start 'incorrectly'. Resulting in the patient crashing, and the doctor can leave and other doctors can leave and enter the room but it remains unfunctional unless you to attempt to recover it.

**Comment by mugmuggy** [comment] 2020-01-14 09:57
Fixed with #1567

**Closed by mugmuggy** 2020-01-14 09:57 UTC
