### ISSUE TITLE
[Bug] Demo Level freeze (dead patient enters for treatment)

### ISSUE THREAD

**Issue by kettenfett** [CorsixTH/CorsixTH#2278] opened 2022-10-26 21:01 UTC
### Describe the issue

I played with the demo and the demo-level froze at some point, when I had almost 1000 patients cured (I don't remember exactly how many) and a very crowded hospital (see screenshot below)..

Interestingly, the game could still be saved. If you load the sav, you will see my hospital (very crowded) and you can still move the view and click on people to get the info popup for them, but nothing more.

It should be noted, that the game did not go "game over" as I'm still fairly within the green spectrum of reputation.

### Steps to Reproduce

1. *Load save game attached to this ticket*

2. ???

3. Profit

### Expected Behaviour

Don't freeze.

### Save Game

Save game attached to report: Yes
[Autosave8.zip](https://github.com/CorsixTH/CorsixTH/files/9873731/Autosave8.zip)

Wait ~1 min and the game will freeze.

### CorsixTH Version

0.66

### Operating System

Windows 10

### Theme Hospital Version

Demo

### Gamelog.txt

```bash
Compiled with api_version: 2682, arch: x64, audio: true, os: windows
SDL renderer: direct3d
Lua 5.4 run with api version: 2682, game version: v0.66, savegame version: 170
Created game with savegame version 170.
Audio:playSound - Warning: File not found in sound archive: reqd021.wav
Warning: Trying to remove nonexistent room build callback (function: 0000019A4A866D20) from humanoid (table: 0000019A4F4BF770).
Warning: Trying to remove nonexistent room remove callback (function: 0000019A59164180) from humanoid (table: 0000019A4F4BF770).
Warning: Trying to remove nonexistent staff callback (function: 0000019A4A867F20) from humanoid (table: 0000019A4F4BF770).
Warning: Trying to remove nonexistent room build callback (function: 0000019A520A2A50) from humanoid (table: 0000019A59656550).
Warning: Trying to remove nonexistent room remove callback (function: 0000019A5852A8D0) from humanoid (table: 0000019A59656550).
Warning: Trying to remove nonexistent staff callback (function: 0000019A520A17F0) from humanoid (table: 0000019A59656550).
Warning: Trying to remove nonexistent room build callback (function: 0000019A53124C70) from humanoid (table: 0000019A58CAFDF0).
Warning: Trying to remove nonexistent room remove callback (function: 0000019A577C8990) from humanoid (table: 0000019A58CAFDF0).
Warning: Trying to remove nonexistent staff callback (function: 0000019A53124970) from humanoid (table: 0000019A58CAFDF0).
Warning: Trying to remove nonexistent room build callback (function: 0000019A5311C030) from humanoid (table: 0000019A59490720).
Warning: Trying to remove nonexistent room remove callback (function: 0000019A577CE330) from humanoid (table: 0000019A59490720).
Warning: Trying to remove nonexistent staff callback (function: 0000019A53118850) from humanoid (table: 0000019A59490720).
Warning: Trying to remove nonexistent room build callback (function: 0000019A59BEB220) from humanoid (table: 0000019A5957F430).
Warning: Trying to remove nonexistent room remove callback (function: 0000019A4E047E30) from humanoid (table: 0000019A5957F430).
Warning: Trying to remove nonexistent staff callback (function: 0000019A59BE6A80) from humanoid (table: 0000019A5957F430).
Warning: Trying to remove nonexistent room build callback (function: 0000019A59BF6560) from humanoid (table: 0000019A58CAE1B0).
Warning: Trying to remove nonexistent room remove callback (function: 0000019A53CA4B50) from humanoid (table: 0000019A58CAE1B0).
Warning: Trying to remove nonexistent staff callback (function: 0000019A59BF4280) from humanoid (table: 0000019A58CAE1B0).
Warning: Trying to remove nonexistent room build callback (function: 0000019A59BECCC0) from humanoid (table: 0000019A4F7D0C30).
Warning: Trying to remove nonexistent room remove callback (function: 0000019A53DF3340) from humanoid (table: 0000019A4F7D0C30).
Warning: Trying to remove nonexistent staff callback (function: 0000019A59BEAD40) from humanoid (table: 0000019A4F7D0C30).
Warning: Trying to remove nonexistent room build callback (function: 0000019A59C06EE0) from humanoid (table: 0000019A59E3CB70).
Warning: Trying to remove nonexistent room remove callback (function: 0000019A53DD4B50) from humanoid (table: 0000019A59E3CB70).
Warning: Trying to remove nonexistent staff callback (function: 0000019A59C06E80) from humanoid (table: 0000019A59E3CB70).
Warning: Trying to resolve door deadlock at (50, 72)
Warning: Trying to resolve door deadlock at (58, 74)
Warning: Trying to resolve door deadlock at (58, 74)
Warning: Trying to remove nonexistent room build callback (function: 0000019A59BE8F40) from humanoid (table: 0000019A539C74F0).
Warning: Trying to remove nonexistent room remove callback (function: 0000019A5A4A31F0) from humanoid (table: 0000019A539C74F0).
Warning: Trying to remove nonexistent staff callback (function: 0000019A59BE7E00) from humanoid (table: 0000019A539C74F0).
Warning: Trying to resolve door deadlock at (54, 74)
Warning: Trying to resolve door deadlock at (73, 68)
Warning: Trying to resolve door deadlock at (51, 74)
Warning: Trying to resolve door deadlock at (61, 72)
Warning: Trying to resolve door deadlock at (55, 65)
Warning: Trying to resolve door deadlock at (58, 74)
Warning: Trying to resolve door deadlock at (51, 65)
Warning: Trying to resolve door deadlock at (81, 76)
Warning: Trying to resolve door deadlock at (81, 76)
Warning: Trying to resolve door deadlock at (80, 72)
Warning: Trying to resolve door deadlock at (80, 72)
Warning: Trying to resolve door deadlock at (78, 75)
Warning: Trying to remove nonexistent room build callback (function: 0000019A5311E4F0) from humanoid (table: 0000019A5D1B0050).
Warning: Trying to remove nonexistent room remove callback (function: 0000019A53E0A1E0) from humanoid (table: 0000019A5D1B0050).
Warning: Trying to remove nonexistent staff callback (function: 0000019A5311C330) from humanoid (table: 0000019A5D1B0050).
Warning: Trying to remove nonexistent room build callback (function: 0000019A5CD7A400) from humanoid (table: 0000019A58A8B690).
Warning: Trying to remove nonexistent room remove callback (function: 0000019A596B1E80) from humanoid (table: 0000019A58A8B690).
Warning: Trying to remove nonexistent staff callback (function: 0000019A5CD79320) from humanoid (table: 0000019A58A8B690).
Warning: Trying to remove nonexistent room build callback (function: 0000019A5CD80A00) from humanoid (table: 0000019A4F4CBAB0).
Warning: Trying to remove nonexistent room remove callback (function: 0000019A4E03B8F0) from humanoid (table: 0000019A4F4CBAB0).
Warning: Trying to remove nonexistent staff callback (function: 0000019A5CD80220) from humanoid (table: 0000019A4F4CBAB0).
Warning: Trying to remove nonexistent room build callback (function: 0000019A5CD7A340) from humanoid (table: 0000019A59468330).
Warning: Trying to remove nonexistent room remove callback (function: 0000019A53E15C10) from humanoid (table: 0000019A59468330).
Warning: Trying to remove nonexistent staff callback (function: 0000019A5CD79E00) from humanoid (table: 0000019A59468330).
Warning: Trying to remove nonexistent room build callback (function: 0000019A5311AAD0) from humanoid (table: 0000019A5C74C520).
Warning: Trying to remove nonexistent room remove callback (function: 0000019A591679C0) from humanoid (table: 0000019A5C74C520).
Warning: Trying to remove nonexistent staff callback (function: 0000019A53116090) from humanoid (table: 0000019A5C74C520).
Warning: Trying to resolve door deadlock at (80, 67)
Warning: Trying to resolve door deadlock at (50, 72)
Warning: Trying to resolve door deadlock at (81, 76)
Error in timer handler: 
Lua\entities\humanoid.lua:472: assertion failed!
stack traceback:
	[C]: in function 'assert'
	Lua\entities\humanoid.lua:472: in method 'startAction'
	Lua\entities\humanoid.lua:577: in method 'finishAction'
	Lua\room.lua:162: in method 'dealtWithPatient'
	Lua\rooms\pharmacy.lua:93: in field 'after_use'
	Lua\humanoid_actions\multi_use_object.lua:316: in local 'timer_function'
	Lua\entity.lua:216: in field 'tick'
	Lua\entities\humanoids\staff.lua:126: in method 'tick'
	Lua\world.lua:1085: in method 'onTick'
	Lua\app.lua:1130: in function <Lua\app.lua:1127>
	(...tail calls...)
	Lua\app.lua:1030: in function <Lua\app.lua:1025>
Recovering from error in timer handler...
Error in timer handler: 
Lua\entities\humanoid.lua:908: Action queue was empty. This should never happen.
humanoid - class: Standard Female Patient
Warmth: 0.328   Happiness: 1.000   Fatigue: 0.000  Thirst: 0.475  Toilet_Need: 0.539   Health: 0.000   Service Quality: 0.000
Actions: []
stack traceback:
	[C]: in function 'error'
	Lua\entities\humanoid.lua:908: in method 'getCurrentAction'
	Lua\hospital.lua:717: in method 'countSittingStanding'
	Lua\hospitals\player_hospital.lua:163: in method 'dailyAdviceChecks'
	Lua\hospitals\player_hospital.lua:457: in method 'onEndDay'
	Lua\world.lua:1046: in method 'onTick'
	Lua\app.lua:1130: in function <Lua\app.lua:1127>
	(...tail calls...)
	Lua\app.lua:1030: in function <Lua\app.lua:1025>
Savegame version is 170 (v0.66), originally it was 170 (v0.66).
Audio:playSound - Warning: File not found in sound archive: sack008.wav
Error in timer handler: 
Lua\entities\humanoid.lua:908: Action queue was empty. This should never happen.
humanoid - class: Standard Female Patient
Warmth: 0.328   Happiness: 1.000   Fatigue: 0.000  Thirst: 0.475  Toilet_Need: 0.539   Health: 0.000   Service Quality: 0.000
Actions: []
stack traceback:
	[C]: in function 'error'
	Lua\entities\humanoid.lua:908: in method 'getCurrentAction'
	Lua\hospital.lua:717: in method 'countSittingStanding'
	Lua\hospitals\player_hospital.lua:163: in method 'dailyAdviceChecks'
	Lua\hospitals\player_hospital.lua:457: in method 'onEndDay'
	Lua\world.lua:1046: in method 'onTick'
	Lua\app.lua:1130: in function <Lua\app.lua:1127>
	(...tail calls...)
	Lua\app.lua:1030: in function <Lua\app.lua:1025>
```

### Additional Information

![grafik](https://user-images.githubusercontent.com/23098362/198136143-91cfef62-3ac6-4ba7-ab31-4e6f18b449a9.png)

**Comment by lewri** [comment] 2022-10-26 21:13
An assertion failed for some reason, which then starting affecting action queues by the look of it. Not sure if the cause yet. Did you manage to still have an autosave from the month before the error?

**Comment by lewri** [comment] 2022-10-26 21:30
A quick dive looks like the patient was sent to go home... so in `Humanoid:_handleEmptyActionQueue()` we exit prematurely without trying to give an action to cover ourselves.

**Comment by lewri** [comment] 2022-10-26 21:34
As easy fix is just to give them a kick anyway if going home. I think changes coming to 0.67 will still let the patient be cured even in treatment.
https://github.com/CorsixTH/CorsixTH/blob/16de53805cda44e76410e51e3289f96c086a0889/CorsixTH/Lua/entities/humanoid.lua#L599-L601

```lua
  if class.is(self, Patient) and self.going_home then
    self:goHome("kicked")
    return
  end
```

**Comment by kettenfett** [comment] 2022-10-26 21:38
more autosaves:
[Autosaves.zip](https://github.com/CorsixTH/CorsixTH/files/9873905/Autosaves.zip)

**Comment by mugmuggy** [comment] 2022-10-26 21:47
I can't find the other issue where this scenario occurs, but the patients health drops to 0 and they get the die actions queued after the current actions, which is on the end of the enter room action, but they end up entering the room anyway and it wipes the additional die actions, which hits this issue from memory. You can see patients health is 0. Then as they are marked as going_home it trips up in dealtWithPatient.

**Comment by lewri** [comment] 2022-10-26 22:12
I was pretty sure we were meant to guard death if in their cure room. It must still be slipping stuff through.

**Comment by lewri** [comment] 2022-10-27 20:13
Checking autosave 7, the patient actually dies, gets up, then sits back down.

**Comment by lewri** [comment] 2022-10-27 21:11
In an attempt to fix by setting a position on `self:queueAction(DieAction())` to `1` in `Patient:die()` appears to have just added more weirdness -- it stops the patient from trying to find a suitable place to die and they just fall on the spot, even through walls (which I don't remember happening normally).

But mugmuggy is right, the issue seems to be all other actions of the patient don't get trumped by dying. Whereas the die should *nicely* take precedence if not in the cure room.

**Comment by lewri** [comment] 2022-11-02 19:40
This is the action queue of the problematic patient at the point they die:
```
humanoid - class: Standard Female Patient
Warmth: 0.328   Happiness: 1.000   Fatigue: 0.000  Thirst: 0.475  Toilet_Need: 0.539   Health: 0.000   Service Quality: 0.000
Actions: [use_object - bench   must_happen, queue - Bench distance: 0 Standing: false   must_happen, walk - going to 80:67   must_happen, meander, die]
```

**Comment by lewri** [comment] 2022-11-02 22:54
It looks like the root issue of the patient not dying is because they couldn't find a suitable tile to die on (where the patient is it does look pretty swamped with patients).
I deleted the operating theatre there, and the patients then would die as normal.

**Comment by lewri** [comment] 2022-12-02 13:14
Another one. Patient dies near top pharmacy and then sits on bench. This is in full game mode.
[tyrins.zip](https://github.com/CorsixTH/CorsixTH/files/10141330/tyrins.zip)

**Comment by lewri** [comment] 2022-12-02 13:15
Ping @tirinkun

**Comment by lewri** [comment] 2023-02-10 20:30
I'm not entirely sure where the actual root cause is still yet. However, the below commit allows a 'clean' death without seemingly triggering other problems. I haven't factored it properly or cleaned anything up, so it's just conceptual really. But maybe it will help direct a path towards a correct solution.

https://github.com/lewri/CorsixTH/commit/3d6430805f125e7116376fb2e5e83b1261ebb3c5

**Comment by mugmuggy** [comment] 2023-02-11 09:02
@lewri my comment on the #2305 doesn't appear to apply here, regarding the bench. From what I can gleam, we have already dealt with this particular scenario, potentially an edge case still as we don't have all the info.

```lua
  -- it's not looking good
  elseif self.attributes["health"] > 0.00 and self.attributes["health"] < 0.01 then
    self.attributes["health"] = 0.0
  -- is there time to say a prayer
  elseif self.attributes["health"] == 0.0 then
    if not self:getRoom() and not self:getCurrentAction().is_leaving then
      self:setMood("sad6", "deactivate")
      self:die()
    end
    -- Patient died, will die when the leave the room, will be cured, or is leaving
    -- the hospital. Regardless we do not need to adjust any other attribute
    return
  end
```

The snippet above from Patient:tickDay allows a day at 0 health. They die on the day after they hit zero health. When this happens, if they are using the door its too late - they shouldn't die from a quick look. If they are about to finish the walk to the door use tile, they maybe able to enter the room, as particular actions start even if they are to be interrupted.

**Comment by lewri** [comment] 2023-02-11 09:48
I'm pretty sure the problem that leads up to this is before the dead patient enters the room.

If a patient dies on the bench they can get up then sit back down again. That seems to be what then causes the actual crash in the room. The dealtWithPatient function is called, but exited prematurely because the function sees the going_home flag. After that, we fall into the emptyActionQueue handler that then also sees they are going home, so no action is assigned. After that, the assert following it fails and crashes.

**Comment by mugmuggy** [comment] 2023-02-11 11:50
So I loaded the tryins save. That particular scenario is same symptoms as https://github.com/CorsixTH/CorsixTH/issues/1439#issuecomment-413843963y
Reviewed everything and #2086 reverted the change for #1439, I had left a comment on #2086 indicating the regression impact when I first picked it up.

**Comment by lewri** [comment] 2023-02-12 17:23
Just to add about the dying on the bench -- the patient calls the queue action again when in front of the door. Patients at benches not in such a position don't have this happen.

I don't know how much it helps though. But assumptions are they if a dead patient is sat on a bench adjacent to their target door, the code is interpreting them in some other way as if they need to rejoin the queue (or something).

**Comment by mugmuggy** [comment] 2023-02-13 07:26
When the patient decides to go to the drinks machine, after they started walking to the destination room. The interrupted walk was re-queued with must_happen = true (instead of false/not set). When patients in this state die, the actions interrupt process from setNextAction, leaves anything that is must_happen to be interrupted. As a walk is left on the queue with must_happen, the patient is actually initiating a walk into the room. If it was must_happen = false, it would be stripped from the action_queue instead. That's what my fix did for #1439 addressed, restoring the original 'must_happen'.

This then leads to the same scenarios, we've seen and I've mentioned about patients 'walking' through walls, or the sliding whilst vomiting. The same reason why cabinet (in the blocked areas bug) animation teleports to the doctor etc. Especially when another setNextAction is called, as any interrupted action on the queue, has its interrupt handler removed the first time through and then the 2nd time, just calls finishAction.

What your must stand is doing, is moving the patient an extra tile away right? The actions are injected before the queue action. Which allows the must_happen walk into the room to be interrupted, after the first tile transition (it has to start due to must_happen etc) and finish transiting. When they use the bench in tryins they are walking from the tile in front of the door to inside the room, so when it starts, the action re-queues them, as thats what navigateDoor in the walk action does.

And from the save attached to your comment:
```
humanoid - class: Standard Female Patient
Warmth: 0.328   Happiness: 1.000   Fatigue: 0.000  Thirst: 0.473  Toilet_Need: 0.539   Health: 0.000   Service Quality: 0.000
Actions: [use_object - bench   must_happen, queue - Bench distance: 0 Standing: false   must_happen, walk - going to 80:67   must_happen, meander, die]
```
And the above is consistent with that issue. You can change the patients action queue walk to must_happen = false as soon as its loaded, and when they die, they leave.

**Comment by lewri** [comment] 2023-02-13 08:31
I see. Thank you mugmuggy! I didn't realise it went even further back than what I thought. 
Do you know specifically if there's a change that can be brought back toaccount for 1453, without breaking anything else in 2086?

**Comment by mugmuggy** [comment] 2023-02-13 11:26
should just be reinstating logic like so, around the requeue_action:setMustHappen or something.
```lua
if current_action.saved_must_happen ~= nil then
  requeue_action.must_happen = current_action.saved_must_happen
end
```
From memory there are some edge cases where the Walk Action goes the idle part in action_walk_start and never sets the saved value, in those cases we don't set it. However that probably could be dealt with in the setMustHappen and constructor of the Walk action itself avoiding any logic here.

**Comment by lewri** [comment] 2023-02-13 21:37
> should just be reinstating logic like so, around the requeue_action:setMustHappen or something.
> 
> ```lua
> if current_action.saved_must_happen ~= nil then
>   requeue_action.must_happen = current_action.saved_must_happen
> end
> ```
> 
> From memory there are some edge cases where the Walk Action goes the idle part in action_walk_start and never sets the saved value, in those cases we don't set it. However that probably could be dealt with in the setMustHappen and constructor of the Walk action itself avoiding any logic here.

Did try to get this one working myself, but it appears where I inserted it (after`requeue_action:setMustHappen(current_action.must_happen)` it causes patients to continually meander when they die.

**Closed** 2023-02-25 20:54 UTC
Labels: P2 High, S:Investigating

**Comment by lewri** [comment] 2023-06-25 15:52
Unpinning ahead of 0.67
