### ISSUE TITLE
Big earthquake and sudden errors

### ISSUE THREAD

**Issue by lorz** [CorsixTH/CorsixTH#792] opened 2015-07-11 11:24 UTC
Sometimes earthquakes are so long that destroys all machines in hospital. Then suddenly game crashes:

Created game with savegame version 91.
Warning: Trying to remove nonexistant room build callback (function: 0x11677518) from humanoid (table: 0x0a07de10).
Warning: Trying to remove nonexistant room remove callback (function: 0x16aef340) from humanoid (table: 0x0a07de10).
Warning: Trying to remove nonexistant room build callback (function: 0x09ec1430) from humanoid (table: 0x16a4f020).
Warning: Trying to remove nonexistant room remove callback (function: 0x16a7de00) from humanoid (table: 0x16a4f020).
Warning: Trying to remove nonexistant room build callback (function: 0x16a42670) from humanoid (table: 0x11662848).
Warning: Trying to remove nonexistant room remove callback (function: 0x116b4ca0) from humanoid (table: 0x11662848).
Warning: Trying to remove nonexistant room build callback (function: 0x11511380) from humanoid (table: 0x04df5720).
Warning: Trying to remove nonexistant room remove callback (function: 0x111569c8) from humanoid (table: 0x04df5720).
Savegame version is 91 (0.40), originally it was 91 (0.40)
Savegame version is 91 (0.40), originally it was 91 (0.40)
Warning: Trying to remove nonexistant room build callback (function: 0x11e05248) from humanoid (table: 0x12af9150).
Warning: Trying to remove nonexistant room remove callback (function: 0x11e051d0) from humanoid (table: 0x12af9150).
Savegame version is 91 (0.40), originally it was 91 (0.40)
Savegame version is 91 (0.40), originally it was 91 (0.40)
Savegame version is 91 (0.40), originally it was 91 (0.40)
Error in timer handler: 
K:\CorsixTH\Lua\humanoid_actions\walk.lua:227: attempt to index field 'queue' (a nil value)
stack traceback:
	K:\CorsixTH\Lua\humanoid_actions\walk.lua: in function 'action_walk_raw'
	K:\CorsixTH\Lua\humanoid_actions\walk.lua:187: in function 'timer_function'
	K:\CorsixTH\Lua\entity.lua:215: in function 'tick'
	K:\CorsixTH\Lua\world.lua:1103: in function 'onTick'
	K:\CorsixTH\Lua\app.lua:852: in function 'dispatch'
	K:\CorsixTH\Lua\app.lua:753: in function <K:\CorsixTH\Lua\app.lua:748>

**Comment by TheCycoONE** [comment] 2015-07-13 01:16
Duplicate of #352

**Closed** 2015-07-13 01:16 UTC
Labels: State-Duplicate
