### ISSUE TITLE
macOS: Filebrowser missing [+] items

### ISSUE THREAD

**Issue by iAmRenzo** [CorsixTH/CorsixTH#1495] opened 2019-01-27 09:33 UTC
I saved my game data in the application support folder in my library. But there isn't always a [+]  sign before the folders. Sometimes when restarting [+] are there and others are gone.
<img width="189" alt="schermafbeelding 2019-01-27 om 10 32 00" src="https://user-images.githubusercontent.com/1183790/51799199-0681a100-221f-11e9-9489-ca07d734f5f3.png">

**Comment by MarkL1961** [comment] 2019-01-27 10:20
Are there other folders in application support?  the + usually means there are and when there isn't one it means there are no other folders, just files.

**Comment by colinjmatt** [comment] 2019-01-27 10:34
This sounds like it may be https://github.com/CorsixTH/CorsixTH/issues/1460.

If you start the game using Terminal and recreate the issue, there should be an error generated in Terminal relating to "Too many open files".

To start the game using Terminal:
`cd /Applications/CorsixTH.app/Contents/MacOS`
`./CorsixTH`

**Comment by TheCycoONE** [comment] 2019-01-29 01:07
@iAmRenzo please add version information, and try colinjmatt's suggestion.

**Comment by TheCycoONE** [comment] 2019-03-26 00:54
No new information, and it sounds like a duplicate of #1460 ; closing.

**Closed by TheCycoONE** 2019-03-26 00:54 UTC
Labels: State-Needs Info
