### ISSUE TITLE
Can't build on custom maps in 0.60

### ISSUE THREAD

**Issue by voodoo-burger** [CorsixTH/CorsixTH#1080] opened 2016-05-31 12:08 UTC
#### Describe the issue
I created a custom map with the built-in in Map Editor in 0.60 and assigned all the indoor and some of the outdoor area (including the helipad) as parcel 1, but when I try to play it the game won't let me build anywhere.

#### Steps to Reproduce
Check the .map I attached and try to play it. It won't let you place any rooms, objects or staff members anywhere.

Map: https://drive.google.com/open?id=0B1z_KXLTgDplLXpLVjJNeTh4Mmc
Level: https://drive.google.com/open?id=0B1z_KXLTgDplTGRtWHdwVUpDNFE

#### Expected Behavior
I should be able to build on parcel 1.

#### System Information
CorsixTH 0.60 on Windows 10.

#### Gamelog.txt
There is nothing in the gamelog except "savegame version 111"

**Comment by TheCycoONE** [comment] 2016-05-31 14:05
Duplicate of #1044. I guess that confirms that this does happen in 0.60, but it does not happen when I make maps. Can you explain how you created the map in that issue (perhaps it's the order things were done that matters)?

**Closed by TheCycoONE** 2016-05-31 14:05 UTC

**Comment by voodoo-burger** [comment] 2016-05-31 18:04
This is what I did:

- Placed helipad
- Placed walkway to where the front door will be
- Placed floor
- Placed walls and doors
- Drew parcel

As I said in #1044 the issue seems to be that you need to place the parcel first and then the floor.
