### ISSUE TITLE
Game Crashes at End of the Year Awards

### ISSUE THREAD

**Issue by misslolab** [CorsixTH/CorsixTH#650] opened 2015-01-31 14:11 UTC
I played the first couple of levels fine. But now on Dec 31st when the awards should pop up the screen goes black and crashes. Please help! ;)

**Comment by sadger** [comment] 2015-01-31 14:34
Do you have any output in your gamelog.txt when that happens? It's found in the same place as your config file.

**Comment by misslolab** [comment] 2015-01-31 15:15
This is what the game log says: reated game with savegame version 91.
Savegame version is 91 (0.40), originally it was 91 (0.40)
Warning: Trying to remove nonexistant room build callback (function: 0x12165b80) from humanoid (table: 0x0b775908).
Warning: Trying to remove nonexistant room remove callback (function: 0x1247e378) from humanoid (table: 0x0b775908).
Warning: Trying to remove nonexistant room build callback (function: 0x0b71e0d8) from humanoid (table: 0x0ff6efc8).
Warning: Trying to remove nonexistant room remove callback (function: 0x0b71df30) from humanoid (table: 0x0ff6efc8).
Warning: Trying to remove nonexistant room build callback (function: 0x12194f68) from humanoid (table: 0x120771a8).
Warning: Trying to remove nonexistant room remove callback (function: 0x044f7098) from humanoid (table: 0x120771a8).
Warning: Trying to remove nonexistant room build callback (function: 0x0c75fa48) from humanoid (table: 0x0b777690).
Warning: Trying to remove nonexistant room remove callback (function: 0x0c75fa08) from humanoid (table: 0x0b777690).
Warning: Trying to remove nonexistant room build callback (function: 0x12212188) from humanoid (table: 0x12131a60).
Warning: Trying to remove nonexistant room remove callback (function: 0x0b6456f8) from humanoid (table: 0x12131a60).
Warning: Trying to remove nonexistant room build callback (function: 0x12391e90) from humanoid (table: 0x12475e30).
Warning: Trying to remove nonexistant room remove callback (function: 0x0b6bfd48) from humanoid (table: 0x12475e30).
Warning: Trying to remove nonexistant room build callback (function: 0x12283040) from humanoid (table: 0x045d5068).
Warning: Trying to remove nonexistant room remove callback (function: 0x0b9dd628) from humanoid (table: 0x045d5068).
Warning: Trying to remove nonexistant room build callback (function: 0x122e7f48) from humanoid (table: 0x0ba49588).
Warning: Trying to remove nonexistant room remove callback (function: 0x0b982f00) from humanoid (table: 0x0ba49588).
Warning: Trying to remove nonexistant room build callback (function: 0x0b9cc220) from humanoid (table: 0x1235beb0).
Warning: Trying to remove nonexistant room remove callback (function: 0x0b790d10) from humanoid (table: 0x1235beb0).
Warning: Trying to remove nonexistant room build callback (function: 0x0fe6e080) from humanoid (table: 0x12152d60).
Warning: Trying to remove nonexistant room remove callback (function: 0x0b7fc078) from humanoid (table: 0x12152d60).
Warning: Trying to remove nonexistant room build callback (function: 0x0c7383d8) from humanoid (table: 0x0b66f448).
Warning: Trying to remove nonexistant room remove callback (function: 0x0b98da98) from humanoid (table: 0x0b66f448).
Warning: Trying to remove nonexistant room build callback (function: 0x0b9cc3d8) from humanoid (table: 0x045cfea8).
Warning: Trying to remove nonexistant room remove callback (function: 0x06d4af20) from humanoid (table: 0x045cfea8).
Warning: Trying to remove nonexistant room build callback (function: 0x0b9b28c0) from humanoid (table: 0x0ba43090).
Warning: Trying to remove nonexistant room remove callback (function: 0x1224f608) from humanoid (table: 0x0ba43090).
Warning: Trying to remove nonexistant room build callback (function: 0x0b78d3b8) from humanoid (table: 0x12484a28).
Warning: Trying to remove nonexistant room remove callback (function: 0x0b7bba00) from humanoid (table: 0x12484a28).
Warning: Trying to remove nonexistant room build callback (function: 0x0b71ba90) from humanoid (table: 0x0c701a80).
Warning: Trying to remove nonexistant room remove callback (function: 0x1203fa10) from humanoid (table: 0x0c701a80).
Warning: Trying to remove nonexistant room build callback (function: 0x124ca4e0) from humanoid (table: 0x0c75f190).
Warning: Trying to remove nonexistant room remove callback (function: 0x0b85d778) from humanoid (table: 0x0c75f190).
Warning: Trying to remove nonexistant room build callback (function: 0x0c753810) from humanoid (table: 0x121dd2b8).
Warning: Trying to remove nonexistant room remove callback (function: 0x083f7ec8) from humanoid (table: 0x121dd2b8).
Savegame version is 91 (0.40), originally it was 91 (0.40)
Warning: Trying to remove nonexistant room build callback (function: 0x0ff74550) from humanoid (table: 0x12fc6980).
Warning: Trying to remove nonexistant room remove callback (function: 0x13036540) from humanoid (table: 0x12fc6980).
Warning: Trying to remove nonexistant room build callback (function: 0x0c2634c0) from humanoid (table: 0x0ffb3078).
Warning: Trying to remove nonexistant room remove callback (function: 0x0fc7cb20) from humanoid (table: 0x0ffb3078).
Warning: Trying to remove nonexistant room build callback (function: 0x1304e0b8) from humanoid (table: 0x0d368f90).
Warning: Trying to remove nonexistant room remove callback (function: 0x066d3cb8) from humanoid (table: 0x0d368f90).
Warning: Trying to remove nonexistant room build callback (function: 0x0c552318) from humanoid (table: 0x0fcb2880).
Warning: Trying to remove nonexistant room remove callback (function: 0x12feb170) from humanoid (table: 0x0fcb2880).
Error in timer handler: 
C:\Program Files\CorsixTH\Lua\humanoid_actions\walk.lua:304: Humanoid (Stripped Female Patient) without door animations trying to walk through door (from cardiogram to corridor)
stack traceback:
	[C]: in function 'error'
	C:\Program Files\CorsixTH\Lua\humanoid_actions\walk.lua:304: in function 'action_walk_raw'
	C:\Program Files\CorsixTH\Lua\humanoid_actions\walk.lua:187: in function 'timer_function'
	C:\Program Files\CorsixTH\Lua\entity.lua:215: in function 'tick'
	C:\Program Files\CorsixTH\Lua\world.lua:1103: in function 'onTick'
	C:\Program Files\CorsixTH\Lua\app.lua:852: in function 'dispatch'
	C:\Program Files\CorsixTH\Lua\app.lua:753: in function <C:\Program Files\CorsixTH\Lua\app.lua:748>
Recovering from error in timer handler...
Warning: Trying to remove nonexistant room build callback (function: 0x0f9da098) from humanoid (table: 0x0fc672e0).
Warning: Trying to remove nonexistant room remove callback (function: 0x0fab7df8) from humanoid (table: 0x0fc672e0).
Warning: Trying to remove nonexistant room build callback (function: 0x03ad1918) from humanoid (table: 0x0fbb6b08).
Warning: Trying to remove nonexistant room remove callback (function: 0x0fbcb610) from humanoid (table: 0x0fbb6b08).
Warning: Trying to remove nonexistant room build callback (function: 0x0cc05768) from humanoid (table: 0x0c571ff8).
Warning: Trying to remove nonexistant room remove callback (function: 0x0c419870) from humanoid (table: 0x0c571ff8).
Warning: Trying to remove nonexistant room build callback (function: 0x0fd30c30) from humanoid (table: 0x0fe39ca0).
Warning: Trying to remove nonexistant room remove callback (function: 0x0facabe8) from humanoid (table: 0x0fe39ca0).
Warning: Trying to remove nonexistant room build callback (function: 0x0fea0000) from humanoid (table: 0x0c094960).
Warning: Trying to remove nonexistant room remove callback (function: 0x1306ff68) from humanoid (table: 0x0c094960).
Warning: Trying to remove nonexistant room build callback (function: 0x0c500250) from humanoid (table: 0x0c4f4150).
Warning: Trying to remove nonexistant room remove callback (function: 0x0c070bc0) from humanoid (table: 0x0c4f4150).
Warning: Trying to remove nonexistant room build callback (function: 0x0c25eba0) from humanoid (table: 0x0feb7cc8).
Warning: Trying to remove nonexistant room remove callback (function: 0x0c25eb60) from humanoid (table: 0x0feb7cc8).
Warning: Trying to remove nonexistant room build callback (function: 0x0ff3a200) from humanoid (table: 0x0fc4e448).
Warning: Trying to remove nonexistant room remove callback (function: 0x0fdf6378) from humanoid (table: 0x0fc4e448).
Warning: Trying to remove nonexistant room build callback (function: 0x0fba5d68) from humanoid (table: 0x0d37eb00).
Warning: Trying to remove nonexistant room remove callback (function: 0x13013558) from humanoid (table: 0x0d37eb00).
Warning: Trying to remove nonexistant room build callback (function: 0x0fa042d8) from humanoid (table: 0x0fbde480).
Warning: Trying to remove nonexistant room remove callback (function: 0x0fa028c8) from humanoid (table: 0x0fbde480).
Warning: Trying to remove nonexistant room build callback (function: 0x0fedab90) from humanoid (table: 0x0d348780).
Warning: Trying to remove nonexistant room remove callback (function: 0x0fedab50) from humanoid (table: 0x0d348780).
Error in timer handler: 
C:\Program Files\CorsixTH\Lua\entities\humanoid.lua:659: Can only finish current action
stack traceback:
	[C]: in function 'assert'
	C:\Program Files\CorsixTH\Lua\entities\humanoid.lua:659: in function 'finishAction'
	C:\Program Files\CorsixTH\Lua\rooms\cardiogram.lua:94: in function 'after_use'
	...Files\CorsixTH\Lua\humanoid_actions\multi_use_object.lua:264: in function 'timer_function'
	C:\Program Files\CorsixTH\Lua\entity.lua:215: in function 'tick'
	C:\Program Files\CorsixTH\Lua\world.lua:1103: in function 'onTick'
	C:\Program Files\CorsixTH\Lua\app.lua:852: in function 'dispatch'
	C:\Program Files\CorsixTH\Lua\app.lua:753: in function <C:\Program Files\CorsixTH\Lua\app.lua:748>


However I don't know if it records it. 
here is a save file: https://www.dropbox.com/s/cneb41935udbdqe/2.sav?dl=0

**Comment by misslolab** [comment] 2015-01-31 20:53
Any ideas?

**Comment by sadger** [comment] 2015-01-31 21:34
Seems it's something to do with the walk animations from the log you have provided. Needs investigation I think.

**Comment by awong728** [comment] 2015-02-04 02:07
I have a similar bug. When it is supposed to show the end of year awards, somehow I fail and the game plays the failed movie, but results in a black screen and it crashes.
Gamelog: https://www.dropbox.com/s/ofs11204xb66r3f/gamelog.txt?dl=0
Autosave: https://www.dropbox.com/s/co74fqmev5ud32u/Autosave12.sav?dl=0

**Comment by bobcanthelpyou** [comment] 2015-07-16 14:31
@misslolab and @awong728 could you reproduce your issues with the latest v0.50 beta release of CorsixTH?

**Comment by Alberth289346** [comment] 2015-10-27 19:17
Neither 2.sav nor 12.sav crash with trunk.
2.sav displays a fail message with or without movies
12.sav displays a fail message or tries display a movie if enabled (which doesn't work at my system very well), but doesn't crash either way.

**Comment by Alberth289346** [comment] 2015-10-27 19:33
Black screen may be due to the game playing a movie and fail

**Comment by mugmuggy** [comment] 2020-05-08 10:00
Issues in the log fixed with #1567

**Closed by mugmuggy** 2020-05-08 10:00 UTC
