### ISSUE TITLE
key_mapping.txt should apply to shortcuts and movement, not textboxes

### ISSUE THREAD

**Issue by Sebvandenbrink** [CorsixTH/CorsixTH#1438] opened 2018-08-09 08:53 UTC
#### Description
When saving a game using the save dialog box, and entering a title for your save game, during typing the text pointer keeps jumping a place, resulting in strange texts.

No workaround has been found so far.

#### Steps to Reproduce
1. Start a game.

2. Save the game with manually entering a title for the savegame.

#### Save Game
It does this regardless of a save game itself.

#### Expected Behavior
Typing regularly, ie: Pressing a letter makes it appear to the right of the previous typed letter.

#### System Information
**CorsixTH Version:** 0.62

**Operating System:** Mac OS X 10.13.6

**Theme Hospital Version:** GOG.com version

#### Gamelog.txt
n/a

### Additional Info
Typing "cabbagevale": 
![screen shot 2018-08-09 at 10 41 10](https://user-images.githubusercontent.com/29941777/43888411-e536420a-9bc1-11e8-8819-e05c4e9d113e.png)

Typing "Avatar":
![screen shot 2018-08-09 at 10 47 38](https://user-images.githubusercontent.com/29941777/43888549-3f6dca68-9bc2-11e8-9c87-f0f6b4be6979.png)

Typing a random text, spaces work. Sometimes the text pointer does not jump and will allow you to type a word - if you're quick.
![screen shot 2018-08-09 at 10 50 14](https://user-images.githubusercontent.com/29941777/43888568-49e078ec-9bc2-11e8-806a-017e7797b8ee.png)

**Comment by TheCycoONE** [comment] 2018-08-09 13:28
Since I cannot reproduce this myself, are you able to add a line at https://github.com/CorsixTH/CorsixTH/blob/47b9ed6c3402f0bd9d63eb177ae6e7126237b6c1/CorsixTH/Lua/window.lua#L1005

`print('keypress: char: ' .. char .. ' cursor_pos: ' .. self.cursor_pos[1] .. ', ' .. self.cursor_pos[2])`

Then paste the resulting log of typing a word and having the cursor move on you.

**Comment by Sebvandenbrink** [comment] 2018-08-09 14:10
Not sure if I did this right, I did
`local ui = self.panel.window.ui and print('keypress: char: ' .. char .. ' cursor_pos: ' .. self.cursor_pos[1] .. ', ' .. self.cursor_pos[2]) `
(I am unfamiliar with Lua.)

Anyway, that did produce this result:
`Created game with savegame version 127.
Error in keydown handler: 
...ications/CorsixTH.app/Contents/Resources//Lua/window.lua:1138: attempt to index a nil value (local 'ui')
stack traceback:
	...ications/CorsixTH.app/Contents/Resources//Lua/window.lua:1138: in method 'keyInput'
	/Applications/CorsixTH.app/Contents/Resources//Lua/ui.lua:543: in field 'onKeyDown'
	...cations/CorsixTH.app/Contents/Resources//Lua/game_ui.lua:289: in function <...cations/CorsixTH.app/Contents/Resources//Lua/game_ui.lua:288>
	(...tail calls...)
	/Applications/CorsixTH.app/Contents/Resources//Lua/app.lua:915: in function </Applications/CorsixTH.app/Contents/Resources//Lua/app.lua:910>
`

**Comment by TheCycoONE** [comment] 2018-08-09 15:14
sorry, I meant to put that on the previous (or following) line, not as an `and` to the assignment expression.

**Comment by Sebvandenbrink** [comment] 2018-08-09 17:00
Ah. Okay, but that doesn't produce any results in the log.

But I found the reason:
I had uncommented the key_remaps in the key_mapping.txt
Not that it helped as it did nothing to activate the WASD keys for camera movement, but it _did_ screw up entering text in the save game dialog.

**Comment by TheCycoONE** [comment] 2018-08-09 17:38
Ah! Ok. I'm not surprised our handling of key_mapping has bit rotted over time.

**Comment by Thorworx** [comment] 2018-09-04 05:17
It looks like this same issue is a **huge** problem when trying to enter a custom resolution.

It was impossible to enter 1440 for my height. Arrow keys for cursor movement and forward delete keys do NOT behave as expected.

**Comment by TheCycoONE** [comment] 2018-09-04 17:38
@Thorworx what was your use case for remapping number keys?

**Comment by Thorworx** [comment] 2018-09-05 14:30
I did not remap any keys at all, or change any settings.
On first launch of game, first thing I did was went to settings to set resolution.
Cursor position and key behavior is just very strange in height and width boxes.

**Comment by TheCycoONE** [comment] 2019-01-18 01:54
Fixed by #1486 - entirely new hotkey mechanism.

**Closed by TheCycoONE** 2019-01-18 01:54 UTC
Labels: Component-UI, State-Accepted, Type-Unexpected behavior
