### ISSUE TITLE
Unable to load saved game after curing the first patient in Level 7

### ISSUE THREAD

**Issue by xuancong84** [CorsixTH/CorsixTH#599] opened 2015-01-04 09:15 UTC
I did not experience this bug in earlier levels, however, at higher levels, more bugs start to emerge. I cannot proceed from this point anymore because saved game cannot be loaded anymore. I keep getting:
<LocalisedString> Current value:Error while loading game: ./Lua/persistance.lua:234: sync fail after 1252 objects (54040 bytes)

To reproduce the bug, please download the save file at http://www.comp.nus.edu.sg/~g0801784/02.sav
After curing the first patient in psychiatry, you save the game. And then that saved game cannot be loaded. Even if you restart the level, after curing the 1st patient, your saved game cannot be loaded anymore.

I wonder have you guys played through all levels?

**Comment by MarkL1961** [comment] 2015-01-04 09:56
Yes we have played all the levels!
I can't download your save though

**Comment by xuancong84** [comment] 2015-01-04 12:40
the save file.

**Comment by xuancong84** [comment] 2015-01-04 12:41
Try to copy and paste the link text, don't click on the link.

**Comment by MarkL1961** [comment] 2015-01-04 13:20
works for me!
I create a save once patient is cured and I can load it afterwards.
Perhaps you have a corrupted file somewhere.
Try uninstall and reinstall to see if that helps

**Comment by xuancong84** [comment] 2015-01-05 03:50
What OS are you running?
I have played the same game in both Windows and Ubuntu 14.04, saved the game in one OS and loaded the game from the other OS and continue playing. Maybe that's the cause. The saved game might be slightly different in different OS, causing data corruption.

**Comment by MarkL1961** [comment] 2015-01-05 12:10
Windows 7

**Comment by J-Shep** [comment] 2015-01-10 22:57
@xuancong84 Thanks for reporting this problem. I've not experienced your problem in Windows 8.1. I will try to reproduce your problem on a Ubuntu 14.04 PC tomorrow.

>> The saved game file might be slightly different in different OS...

The contents of a saved game is not affected by the OS it was saved in.

**Comment by xuancong84** [comment] 2015-01-11 14:10
Hi, thanks!

I have solved the problem. It does not seem to be an OS compatibility problem. I feel that it is like a game crash has corrupted the game binary file in Ubuntu. After that, the game has problem in saving and loading. Reinstalling CorsixTH solves the issue.

**Comment by Lego3** [comment] 2015-01-11 17:32
Great. :-) I'll close this issue then.

**Closed by Lego3** 2015-01-11 17:32 UTC
