### ISSUE TITLE
Game crash when dying patient sent home

### ISSUE THREAD

**Issue by ms609** [CorsixTH/CorsixTH#623] opened 2015-01-23 17:46 UTC
I discharged a near-death patient (100% grey skull icon).  When they walk off the edge of the map, the game crashes.  I can recreate this error from a savegame - it's not a one-off.

**Comment by TheCycoONE** [comment] 2015-01-23 18:49
I think this is a duplicate of #347 - Can you confirm?

**Closed** 2015-07-19 22:53 UTC
Labels: State-Duplicate
