### ISSUE TITLE
Error with patient leaving general diagnosis

### ISSUE THREAD

**Issue by uwmyuan** [CorsixTH/CorsixTH#1419] opened 2018-06-10 18:44 UTC
#### Steps to Reproduce
1. [*Load save game attached to this ticket*](https://drive.google.com/open?id=10g5JlloM5CfXPPGGTcD5iWygGCJSlmFa)

2. load the saved game and it would popup error notice. Buttons are unusable.

#### System Information
**CorsixTH Version:** *0.61*

**Operating System:** *Windows 10*

**Theme Hospital Version:** *GOG.com*

#### [Gamelog.txt](https://drive.google.com/open?id=1gohg-BjaLxnHom75h2oDv2w--9iTpZ35)

```

---------------------------------------------------------------

Welcome to CorsixTH v0.61!

---------------------------------------------------------------

This window will display useful information if an error occurs.

---------------------------------------------------------------

Checking for CorsixTH updates...
You are running the latest version of CorsixTH.
An error has occurred!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The timer handler.
A stack trace is included below, and the handler has been disconnected.
D:\Program Files (x86)\CorsixTH\Lua\entities\humanoid.lua:675: attempt to index a nil value (field '?')
stack traceback:
        D:\Program Files (x86)\CorsixTH\Lua\entities\humanoid.lua:675: in method 'isLeaving'
        D:\Program Files (x86)\CorsixTH\Lua\room.lua:868: in method 'makeHumanoidDressIfNecessaryAndThenLeave'
        D:\Program Files (x86)\CorsixTH\Lua\rooms\general_diag.lua:98: in method 'makeHumanoidLeave'
        D:\Program Files (x86)\CorsixTH\Lua\entities\humanoid.lua:520: in upvalue 'Humanoid_startAction'
        D:\Program Files (x86)\CorsixTH\Lua\entities\humanoid.lua:670: in method 'finishAction'
        ... (x86)\CorsixTH\Lua\humanoid_actions\call_checkpoint.lua:40: in field '?'
        D:\Program Files (x86)\CorsixTH\Lua\entities\humanoid.lua:578: in upvalue 'Humanoid_startAction'
        D:\Program Files (x86)\CorsixTH\Lua\entities\humanoid.lua:670: in local 'timer_function'
        D:\Program Files (x86)\CorsixTH\Lua\entity.lua:216: in field 'tick'
        D:\Program Files (x86)\CorsixTH\Lua\entities\staff.lua:149: in method 'tick'
        D:\Program Files (x86)\CorsixTH\Lua\world.lua:1051: in method 'onTick'
        D:\Program Files (x86)\CorsixTH\Lua\app.lua:1008: in function <D:\Program Files (x86)\CorsixTH\Lua\app.lua:1005>
        (...tail calls...)
        D:\Program Files (x86)\CorsixTH\Lua\app.lua:909: in function <D:\Program Files (x86)\CorsixTH\Lua\app.lua:904>

Warning: No event handler for timer
An error has occurred!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The timer handler.
A stack trace is included below, and the handler has been disconnected.
D:\Program Files (x86)\CorsixTH\Lua\entities\staff.lua:780: attempt to index a nil value (field '?')
stack traceback:
        D:\Program Files (x86)\CorsixTH\Lua\entities\staff.lua:780: in method 'isIdle'
        D:\Program Files (x86)\CorsixTH\Lua\calls_dispatcher.lua:490: in function <D:\Program Files (x86)\CorsixTH\Lua\calls_dispatcher.lua:489>
        (...tail calls...)
        D:\Program Files (x86)\CorsixTH\Lua\calls_dispatcher.lua:312: in method 'findSuitableStaff'
        D:\Program Files (x86)\CorsixTH\Lua\calls_dispatcher.lua:291: in method 'enqueue'
        D:\Program Files (x86)\CorsixTH\Lua\calls_dispatcher.lua:73: in method 'callForStaffEachRoom'
        D:\Program Files (x86)\CorsixTH\Lua\calls_dispatcher.lua:59: in method 'callForStaff'
        D:\Program Files (x86)\CorsixTH\Lua\room.lua:580: in field 'onHumanoidLeave'
        D:\Program Files (x86)\CorsixTH\Lua\rooms\gp.lua:199: in method 'onHumanoidLeave'
        ...ogram Files (x86)\CorsixTH\Lua\humanoid_actions\walk.lua:379: in field 'on_next_tile_set'
        ...ogram Files (x86)\CorsixTH\Lua\humanoid_actions\walk.lua:191: in function <...ogram Files (x86)\CorsixTH\Lua\humanoid_actions\walk.lua:178>
        (...tail calls...)
        D:\Program Files (x86)\CorsixTH\Lua\entity.lua:216: in field 'tick'
        D:\Program Files (x86)\CorsixTH\Lua\entities\staff.lua:149: in method 'tick'
        D:\Program Files (x86)\CorsixTH\Lua\world.lua:1051: in method 'onTick'
        D:\Program Files (x86)\CorsixTH\Lua\app.lua:1008: in function <D:\Program Files (x86)\CorsixTH\Lua\app.lua:1005>
        (...tail calls...)
        D:\Program Files (x86)\CorsixTH\Lua\app.lua:909: in function <D:\Program Files (x86)\CorsixTH\Lua\app.lua:904>

An error has occurred!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The timer handler.
A stack trace is included below, and the handler has been disconnected.
D:\Program Files (x86)\CorsixTH\Lua\entities\staff.lua:780: attempt to index a nil value (field '?')
stack traceback:
        D:\Program Files (x86)\CorsixTH\Lua\entities\staff.lua:780: in method 'isIdle'
        D:\Program Files (x86)\CorsixTH\Lua\calls_dispatcher.lua:490: in function <D:\Program Files (x86)\CorsixTH\Lua\calls_dispatcher.lua:489>
        (...tail calls...)
        D:\Program Files (x86)\CorsixTH\Lua\calls_dispatcher.lua:312: in method 'findSuitableStaff'
        D:\Program Files (x86)\CorsixTH\Lua\calls_dispatcher.lua:291: in method 'enqueue'
        D:\Program Files (x86)\CorsixTH\Lua\calls_dispatcher.lua:73: in method 'callForStaffEachRoom'
        D:\Program Files (x86)\CorsixTH\Lua\calls_dispatcher.lua:59: in method 'callForStaff'
        ... Files (x86)\CorsixTH\Lua\humanoid_actions\seek_room.lua:113: in upvalue 'action_seek_room_goto_room'
        ... Files (x86)\CorsixTH\Lua\humanoid_actions\seek_room.lua:252: in field '?'
        D:\Program Files (x86)\CorsixTH\Lua\entities\humanoid.lua:578: in upvalue 'Humanoid_startAction'
        D:\Program Files (x86)\CorsixTH\Lua\entities\humanoid.lua:670: in method 'finishAction'
        ...ogram Files (x86)\CorsixTH\Lua\humanoid_actions\walk.lua:193: in function <...ogram Files (x86)\CorsixTH\Lua\humanoid_actions\walk.lua:178>
        (...tail calls...)
        D:\Program Files (x86)\CorsixTH\Lua\entity.lua:216: in method 'tick'
        D:\Program Files (x86)\CorsixTH\Lua\world.lua:1051: in method 'onTick'
        D:\Program Files (x86)\CorsixTH\Lua\app.lua:1008: in function <D:\Program Files (x86)\CorsixTH\Lua\app.lua:1005>
        (...tail calls...)
        D:\Program Files (x86)\CorsixTH\Lua\app.lua:909: in function <D:\Program Files (x86)\CorsixTH\Lua\app.lua:904>

An error has occurred!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The timer handler.
A stack trace is included below, and the handler has been disconnected.
D:\Program Files (x86)\CorsixTH\Lua\entities\staff.lua:780: attempt to index a nil value (field '?')
stack traceback:
        D:\Program Files (x86)\CorsixTH\Lua\entities\staff.lua:780: in method 'isIdle'
        D:\Program Files (x86)\CorsixTH\Lua\calls_dispatcher.lua:490: in function <D:\Program Files (x86)\CorsixTH\Lua\calls_dispatcher.lua:489>
        (...tail calls...)
        D:\Program Files (x86)\CorsixTH\Lua\calls_dispatcher.lua:312: in method 'findSuitableStaff'
        D:\Program Files (x86)\CorsixTH\Lua\calls_dispatcher.lua:291: in method 'enqueue'
        D:\Program Files (x86)\CorsixTH\Lua\calls_dispatcher.lua:73: in method 'callForStaffEachRoom'
        D:\Program Files (x86)\CorsixTH\Lua\calls_dispatcher.lua:59: in method 'callForStaff'
        D:\Program Files (x86)\CorsixTH\Lua\room.lua:580: in field 'onHumanoidLeave'
        D:\Program Files (x86)\CorsixTH\Lua\rooms\ward.lua:197: in method 'onHumanoidLeave'
        ...ogram Files (x86)\CorsixTH\Lua\humanoid_actions\walk.lua:379: in field 'on_next_tile_set'
        ...ogram Files (x86)\CorsixTH\Lua\humanoid_actions\walk.lua:191: in function <...ogram Files (x86)\CorsixTH\Lua\humanoid_actions\walk.lua:178>
        (...tail calls...)
        D:\Program Files (x86)\CorsixTH\Lua\entity.lua:216: in field 'tick'
        D:\Program Files (x86)\CorsixTH\Lua\entities\staff.lua:149: in method 'tick'
        D:\Program Files (x86)\CorsixTH\Lua\world.lua:1051: in method 'onTick'
        D:\Program Files (x86)\CorsixTH\Lua\app.lua:1008: in function <D:\Program Files (x86)\CorsixTH\Lua\app.lua:1005>
        (...tail calls...)
        D:\Program Files (x86)\CorsixTH\Lua\app.lua:909: in function <D:\Program Files (x86)\CorsixTH\Lua\app.lua:904>

An error has occurred!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The timer handler.
A stack trace is included below, and the handler has been disconnected.
D:\Program Files (x86)\CorsixTH\Lua\entities\staff.lua:780: attempt to index a nil value (field '?')
stack traceback:
        D:\Program Files (x86)\CorsixTH\Lua\entities\staff.lua:780: in method 'isIdle'
        D:\Program Files (x86)\CorsixTH\Lua\calls_dispatcher.lua:490: in function <D:\Program Files (x86)\CorsixTH\Lua\calls_dispatcher.lua:489>
        (...tail calls...)
        D:\Program Files (x86)\CorsixTH\Lua\calls_dispatcher.lua:312: in method 'findSuitableStaff'
        D:\Program Files (x86)\CorsixTH\Lua\calls_dispatcher.lua:291: in method 'enqueue'
        D:\Program Files (x86)\CorsixTH\Lua\calls_dispatcher.lua:73: in method 'callForStaffEachRoom'
        D:\Program Files (x86)\CorsixTH\Lua\calls_dispatcher.lua:59: in method 'callForStaff'
        D:\Program Files (x86)\CorsixTH\Lua\room.lua:580: in method 'onHumanoidLeave'
        ...ogram Files (x86)\CorsixTH\Lua\humanoid_actions\walk.lua:379: in field 'on_next_tile_set'
        ...ogram Files (x86)\CorsixTH\Lua\humanoid_actions\walk.lua:191: in function <...ogram Files (x86)\CorsixTH\Lua\humanoid_actions\walk.lua:178>
        (...tail calls...)
        D:\Program Files (x86)\CorsixTH\Lua\entity.lua:216: in field 'tick'
        D:\Program Files (x86)\CorsixTH\Lua\entities\staff.lua:149: in method 'tick'
        D:\Program Files (x86)\CorsixTH\Lua\world.lua:1051: in method 'onTick'
        D:\Program Files (x86)\CorsixTH\Lua\app.lua:1008: in function <D:\Program Files (x86)\CorsixTH\Lua\app.lua:1005>
        (...tail calls...)
        D:\Program Files (x86)\CorsixTH\Lua\app.lua:909: in function <D:\Program Files (x86)\CorsixTH\Lua\app.lua:904>

An error has occurred!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The buttonup handler.
A stack trace is included below, and the handler has been disconnected.
...ogram Files (x86)\CorsixTH\Lua\humanoid_actions\walk.lua:102: attempt to call a nil value (local 'timer_function')
stack traceback:
        ...ogram Files (x86)\CorsixTH\Lua\humanoid_actions\walk.lua:102: in local 'on_interrupt'
        D:\Program Files (x86)\CorsixTH\Lua\entities\humanoid.lua:641: in method 'setNextAction'
        ...rogram Files (x86)\CorsixTH\Lua\dialogs\staff_dialog.lua:312: in local 'callback'
        D:\Program Files (x86)\CorsixTH\Lua\window.lua:682: in method 'handleClick'
        D:\Program Files (x86)\CorsixTH\Lua\window.lua:1478: in field 'onMouseUp'
        ...rogram Files (x86)\CorsixTH\Lua\dialogs\staff_dialog.lua:268: in method 'onMouseUp'
        D:\Program Files (x86)\CorsixTH\Lua\window.lua:1462: in field 'onMouseUp'
        D:\Program Files (x86)\CorsixTH\Lua\ui.lua:654: in function <D:\Program Files (x86)\CorsixTH\Lua\ui.lua:641>
        (...tail calls...)
        D:\Program Files (x86)\CorsixTH\Lua\app.lua:909: in function <D:\Program Files (x86)\CorsixTH\Lua\app.lua:904>

Warning: No event handler for buttonup
```

**Comment by TheCycoONE** [comment] 2018-06-10 23:53
Thank you for the report

**Comment by TheCycoONE** [comment] 2018-06-11 01:13
https://github.com/CorsixTH/CorsixTH/blob/61f0f7c2e71bc9e39f551769c61d5976b3530bab/CorsixTH/Lua/entities/humanoid.lua#L675

It appears that the line that failed failed because a patient didn't have anything in their action queue, which is an illegal state. Unfortunately the stack trace doesn't tell us what caused that.

**Comment by uwmyuan** [comment] 2018-06-11 02:49
Thanks for the quick response.

**Comment by lewri** [comment] 2020-08-30 11:41
I can't reproduce this in 0.64 now in loading the save. Something tells me we must've applied something that fixed it somewhere down the line.

**Comment by ARGAMX** [comment] 2024-10-14 18:01
I can't reproduce this in 0.66.0 too.
May be we can close this issue?

**Closed** 2024-10-14 18:47 UTC
Labels: bug
