### ISSUE TITLE
operating sal - bug

### ISSUE THREAD

**Issue by viktorcech** [CorsixTH/CorsixTH#1092] opened 2016-06-17 13:17 UTC
#### Steps to Reproduce
[saves.zip](https://github.com/CorsixTH/CorsixTH/files/320531/saves.zip)
1. *Load save game attached to this ticket*

**CorsixTH Version:** *e.g. 0.60*

**Operating System:** *e.g. Windows 10*

**Theme Hospital Version:** *CD, GOG.com, Origin, or Demo*

people can go to the operating sal... i dont know why..

**Comment by MarkL1961** [comment] 2016-06-17 14:29
It looks like the door is being reserved by someone and as a result no one else can use it.

Pick up the staff and place them outside then edit the room back to the blueprint stage.  This cleared the reservation for me

**Comment by viktorcech** [comment] 2016-06-17 14:31
editing room is not a fix.. this is a bug.. then must be fixed .. source code..

**Comment by TheCycoONE** [comment] 2016-06-17 14:32
We know, Mark was suggesting a workaround in the mean time. We're aware of door reserve bugs.

**Comment by TheCycoONE** [comment] 2016-06-17 14:40
Duplicate of #68 / #1087 then?

**Comment by Alberth289346** [comment] 2016-06-17 14:59
@viktorcech  source code is right here in this project, make a fork, and create a proper patch. We will be most happy with it.

**Comment by viktorcech** [comment] 2016-06-17 15:55
im not a developer.. people how making this project must fixing bugs

**Comment by MarkL1961** [comment] 2016-06-17 15:56
@TheCycoONE 
I reckon so

**Closed by MarkL1961** 2016-06-17 15:56 UTC
