### ISSUE TITLE
Radiators heating diagonally instead of around?

### ISSUE THREAD

**Issue by tmarplatt** [CorsixTH/CorsixTH#1421] opened 2018-06-14 16:51 UTC
#### Describe the issue
In the map view the heat from radiators is shown covering a diagonal area originating from the radiator, instead of a circle with the radiator in its center. Is this a bug?

I've attached a savegame. 

I'll try reproducing it if you confirm it's a bug.

#### Save Game

[radiators.zip](https://github.com/CorsixTH/CorsixTH/files/2103253/radiators.zip)
![radiators](https://user-images.githubusercontent.com/16073344/41426309-98eaf1de-6fd9-11e8-9c94-1871242679b2.png)

Notice the one in the middle of the hallway, only heating NW of its position. Is it windy inside the hospital? Haha.

#### System Information
**CorsixTH Version:** 0.61

**Operating System:** Windows 7

**Theme Hospital Version:** CD

**Comment by TheCycoONE** [comment] 2018-06-14 16:55
Duplicate of #1338

**Closed by TheCycoONE** 2018-06-14 16:55 UTC
