### ISSUE TITLE
Handyman tries to enter exploded room, gets stuck

### ISSUE THREAD

**Issue by TheMatia** [CorsixTH/CorsixTH#1065] opened 2016-05-02 15:18 UTC
#### Describe the issue
After a room explodes, sometimes a handyman tries to enter it and gets stuck at the door. I can click on him but not pick him up, and firing him will mark him as fired but won't unstick him. I think this occurs when the machine was marked for repairing before it explodes.

#### Steps to Reproduce
(During an earthquake is best for this)
1. Click the Page Handyman to Repair button on a machine's interface.

2. Allow the machine to explode before a handyman reaches the room

3. Watch the handyman when he reaches the door

#### Expected Behavior
Handyman should probably abandon his quest when he reaches the door and sees the exploded room(?)

#### System Information
**CorsixTH Version:** *0.60-rc1*

**Operating System:** *Windows 10*

**Theme Hospital Version:** *CD*

#### Gamelog.txt

---------------------------------------------------------------

Welcome to CorsixTH v0.60-rc1!

---------------------------------------------------------------

This window will display useful information if an error occurs.

---------------------------------------------------------------

Checking for CorsixTH updates...
You are running the latest version of CorsixTH.
An error has occurred!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The timer handler.
A stack trace is included below, and the handler has been disconnected.
D:\Program Files\CorsixTH\Lua\humanoid_actions\walk.lua:228: attempt to index a nil value (field 'queue')
stack traceback:
        D:\Program Files\CorsixTH\Lua\humanoid_actions\walk.lua:228: in function <D:\Program Files\CorsixTH\Lua\humanoid_actions\walk.lua:210>
        (...tail calls...)
        D:\Program Files\CorsixTH\Lua\humanoid_actions\walk.lua:188: in local 'timer_function'
        D:\Program Files\CorsixTH\Lua\entity.lua:219: in field 'tick'
        D:\Program Files\CorsixTH\Lua\entities\staff.lua:149: in method 'tick'
        D:\Program Files\CorsixTH\Lua\world.lua:1059: in method 'onTick'
        D:\Program Files\CorsixTH\Lua\app.lua:1000: in function <D:\Program Files\CorsixTH\Lua\app.lua:997>
        (...tail calls...)
        D:\Program Files\CorsixTH\Lua\app.lua:901: in function <D:\Program Files\CorsixTH\Lua\app.lua:896>

Warning: No event handler for timer

**Comment by TheCycoONE** [comment] 2016-05-03 12:07
Duplicate of #508

**Closed by TheCycoONE** 2016-05-03 12:07 UTC
