### ISSUE TITLE
[Bug] String Dumps break language change

### ISSUE THREAD

**Issue by lewri** [CorsixTH/CorsixTH#2059] opened 2021-09-22 16:53 UTC
#### Describe the issue
When dumping strings in another language, switching the language back causes an error should a string not be translated/missing.

#### Steps to Reproduce
1. Open game and set game to another language (probably not Czech at the moment as that's complete)

2. Continue a game and dump strings

3. Exit the game to main menu then try to change language again

#### Expected Behavior
Allow the language change.

#### System Information
**CorsixTH Version:** 163 (after 0.65)

**Operating System:** Windows 10

**Theme Hospital Version:** GOG

#### Gamelog.txt

From 163
```
An error has occurred!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The buttonup handler.
A stack trace is included below, and the handler has been disconnected.
Non-existent string: crazy_off_cheat
stack traceback:
        [C]: in function 'error'
        Lua\strings.lua:143: in function <Lua\strings.lua:135>
        [C]: in metamethod 'index'
        [string "local reload, all_proxies, _ = ......"]:4: in main chunk
        [C]: in field 'reload'
        Lua\app.lua:457: in method 'initLanguage'
        Lua\dialogs/resizables\options.lua:258: in field 'callback'
        Lua\dialogs/resizables\dropdown.lua:80: in method 'selectItem'
        Lua\dialogs/resizables\dropdown.lua:61: in local 'callback'
        Lua\window.lua:699: in method 'handleClick'
        Lua\window.lua:1661: in method 'onMouseUp'
        Lua\window.lua:1645: in method 'onMouseUp'
        Lua\window.lua:1645: in field 'onMouseUp'
        Lua\ui.lua:922: in function <Lua\ui.lua:909>
        (...tail calls...)
        Lua\app.lua:1024: in function <Lua\app.lua:1019>
```
From #2055 
```
An error has occurred!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The buttonup handler.
A stack trace is included below, and the handler has been disconnected.
Non-existent string: very_bad
stack traceback:
        [C]: in function 'error'
        Lua\strings.lua:143: in function <Lua\strings.lua:135>
        [C]: in ?
        [C]: in metamethod 'index'
        [string "local reload, all_proxies, _ = ......"]:4: in main chunk
        [C]: in field 'reload'
        Lua\app.lua:452: in method 'initLanguage'
        Lua\dialogs/resizables\options.lua:258: in field 'callback'
        Lua\dialogs/resizables\dropdown.lua:80: in method 'selectItem'
        Lua\dialogs/resizables\dropdown.lua:61: in local 'callback'
        Lua\window.lua:699: in method 'handleClick'
        Lua\window.lua:1661: in method 'onMouseUp'
        Lua\window.lua:1645: in method 'onMouseUp'
        Lua\window.lua:1645: in field 'onMouseUp'
        Lua\ui.lua:922: in function <Lua\ui.lua:909>
        (...tail calls...)
        Lua\app.lua:1019: in function <Lua\app.lua:1014>
```

### Additional Info
Workaround appears to be closing the game completely after a dump.

**Comment by TheCycoONE** [comment] 2021-10-06 02:24
This is a long standing issue - actually surprised it wasn't filed already.

**Comment by TheCycoONE** [comment] 2021-10-06 02:24
It was, duplicate of #848

**Closed by TheCycoONE** 2021-10-06 02:24 UTC
Labels: bug
