### ISSUE TITLE
DirectX-mode: Cursor is filickering.

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#489] opened 2014-12-24 00:33 UTC
_From [maartenp...@hotmail.nl](https://code.google.com/u/103280305005036074093/) on April 11, 2012 16:18:38_

What steps will reproduce the problem? 1.Start CorsixTH with CorsixTH_DirectX.exe 
2.You can see that in the menu and in the game the cursors flickers when you move it. What is the expected output? What do you see instead? Flickering cursor.

What version of CorsixTH are you using (e.g. "Beta 2", "SVN r123 ")?
0.0.1 What operating system / compile settings are you using? Windows 7

What level was this on (e.g. "Demo level", "Full game level 12")?
- Attach a saved game file (preferably an autosave from before the error) if you have one and it is relevant. - Please provide any additional information below.

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=1213_

**Comment by Lego3** [comment] 2015-01-13 19:51
I'll close this now. I can't reproduce, and so much has happened since the last comment.

**Closed by Lego3** 2015-01-13 19:51 UTC
Labels: P4 Low, Googlecode, C:Graphical
