### ISSUE TITLE
Game crashes when patient with epidemic enters auto-autopsy machine

### ISSUE THREAD

**Issue by ms609** [CorsixTH/CorsixTH#612] opened 2015-01-17 20:08 UTC
When a contagious patient is sent to the research lab, the game consistently crashes once the patient has entered the a-a machine.

**Comment by mugmuggy** [comment] 2019-03-28 11:01
Can't reproduce anything specific with a contagious patient and nothing else to go by, closing.

**Closed by mugmuggy** 2019-03-28 11:01 UTC
