### ISSUE TITLE
Some crashes while playing

### ISSUE THREAD

**Issue by Stefan1200-de** [CorsixTH/CorsixTH#911] opened 2015-10-17 20:11 UTC
Today I played a long session CorsixTH 0.50 (Windows 10) on the included free game map Finisham. Two times the game crash, so I had to load an auto save game.

One time a surgeon was outside of the hospital, another time a patient was unable to leave a room. From the last time, where a patient tried to run trough a wall I have two log files. Unfortunately I can only attach images here.

Download link: www.stefan1200.de/downloads/CorsixTH-crashlogs.zip

**Comment by TheCycoONE** [comment] 2015-10-18 20:41
Pasting contents of logs here:
```
Created game with savegame version 105.
Warning: Trying to remove nonexistant room build callback (function: 000000C7852D7820) from humanoid (table: 000000C7849C9420).
Warning: Trying to remove nonexistant room remove callback (function: 000000C794216380) from humanoid (table: 000000C7849C9420).
Warning: Trying to remove nonexistant room build callback (function: 000000C7846FA9C0) from humanoid (table: 000000C785F0CA70).
Warning: Trying to remove nonexistant room remove callback (function: 000000C79B1AEDD0) from humanoid (table: 000000C785F0CA70).
Warning: Trying to remove nonexistant room build callback (function: 000000C785D2BB30) from humanoid (table: 000000C7849C9420).
Warning: Trying to remove nonexistant room remove callback (function: 000000C785B080E0) from humanoid (table: 000000C7849C9420).
Warning: Trying to remove nonexistant room build callback (function: 000000C7846DD4A0) from humanoid (table: 000000C793C17850).
Warning: Trying to remove nonexistant room remove callback (function: 000000C7845E41D0) from humanoid (table: 000000C793C17850).
Warning: Trying to remove nonexistant room build callback (function: 000000C7846F4C00) from humanoid (table: 000000C785232EA0).
Warning: Trying to remove nonexistant room remove callback (function: 000000C79B2A23D0) from humanoid (table: 000000C785232EA0).
Savegame version is 105 (0.50), originally it was 105 (0.50)
Warning: Trying to remove nonexistant room build callback (function: 000000F8B64CC3B0) from humanoid (table: 000000F8A6B9D5F0).
Warning: Trying to remove nonexistant room remove callback (function: 000000F8A7818760) from humanoid (table: 000000F8A6B9D5F0).
Warning: Trying to remove nonexistant room build callback (function: 000000F8B64D0D90) from humanoid (table: 000000F8A6887390).
Warning: Trying to remove nonexistant room remove callback (function: 000000F8A7534720) from humanoid (table: 000000F8A6887390).
Warning: Trying to remove nonexistant room build callback (function: 000000F8B6A17C30) from humanoid (table: 000000F8A6CC2920).
Warning: Trying to remove nonexistant room remove callback (function: 000000F8A55CA530) from humanoid (table: 000000F8A6CC2920).
Warning: Trying to remove nonexistant room build callback (function: 000000F8B6A12E90) from humanoid (table: 000000F8A6EF7740).
Warning: Trying to remove nonexistant room remove callback (function: 000000F8B4E4C410) from humanoid (table: 000000F8A6EF7740).
Error in timer handler: 
D:\Spiele\CorsixTH\Lua\humanoid_actions\walk.lua:174: Suspected infinite loop
stack traceback:
	[C]: in function 'error'
	D:\Spiele\CorsixTH\Lua\app.lua:797: in hook '?'
	D:\Spiele\CorsixTH\Lua\humanoid_actions\walk.lua:174: in function <D:\Spiele\CorsixTH\Lua\humanoid_actions\walk.lua:137>
	(...tail calls...)
	D:\Spiele\CorsixTH\Lua\entity.lua:218: in method 'tick'
	D:\Spiele\CorsixTH\Lua\world.lua:1121: in method 'onTick'
	D:\Spiele\CorsixTH\Lua\app.lua:878: in function <D:\Spiele\CorsixTH\Lua\app.lua:875>
	(...tail calls...)
	D:\Spiele\CorsixTH\Lua\app.lua:779: in function <D:\Spiele\CorsixTH\Lua\app.lua:774>
```

```
Welcome to CorsixTH 0.50!

---------------------------------------------------------------

This window will display useful information if an error occurs.

---------------------------------------------------------------

Checking for CorsixTH updates...
You are running the latest version of CorsixTH.
An error has occured!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The timer handler.
A stack trace is included below, and the handler has been disconnected.
D:\Spiele\CorsixTH\Lua\hospital.lua:1559: attempt to index a nil value (field '?')
stack traceback:
        D:\Spiele\CorsixTH\Lua\hospital.lua:1559: in method 'getTreatmentPrice'
        D:\Spiele\CorsixTH\Lua\hospital.lua:1543: in method 'receiveMoneyForTreatment'
        D:\Spiele\CorsixTH\Lua\room.lua:176: in method 'dealtWithPatient'
        D:\Spiele\CorsixTH\Lua\rooms\operating_theatre.lua:199: in field 'after_use'
        ...piele\CorsixTH\Lua\humanoid_actions\multi_use_object.lua:264: in local 'timer_function'
        D:\Spiele\CorsixTH\Lua\entity.lua:218: in field 'tick'
        D:\Spiele\CorsixTH\Lua\entities\staff.lua:149: in method 'tick'
        D:\Spiele\CorsixTH\Lua\world.lua:1121: in method 'onTick'
        D:\Spiele\CorsixTH\Lua\app.lua:878: in function <D:\Spiele\CorsixTH\Lua\app.lua:875>
        (...tail calls...)
        D:\Spiele\CorsixTH\Lua\app.lua:779: in function <D:\Spiele\CorsixTH\Lua\app.lua:774>

Warning: No event handler for timer
An error has occured!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The timer handler.
A stack trace is included below, and the handler has been disconnected.
D:\Spiele\CorsixTH\Lua\hospital.lua:1559: attempt to index a nil value (field '?')
stack traceback:
        D:\Spiele\CorsixTH\Lua\hospital.lua:1559: in method 'getTreatmentPrice'
        D:\Spiele\CorsixTH\Lua\hospital.lua:1543: in method 'receiveMoneyForTreatment'
        D:\Spiele\CorsixTH\Lua\room.lua:176: in method 'dealtWithPatient'
        D:\Spiele\CorsixTH\Lua\rooms\operating_theatre.lua:199: in field 'after_use'
        ...piele\CorsixTH\Lua\humanoid_actions\multi_use_object.lua:264: in local 'timer_function'
        D:\Spiele\CorsixTH\Lua\entity.lua:218: in field 'tick'
        D:\Spiele\CorsixTH\Lua\entities\staff.lua:149: in method 'tick'
        D:\Spiele\CorsixTH\Lua\world.lua:1121: in method 'onTick'
        D:\Spiele\CorsixTH\Lua\app.lua:878: in function <D:\Spiele\CorsixTH\Lua\app.lua:875>
        (...tail calls...)
        D:\Spiele\CorsixTH\Lua\app.lua:779: in function <D:\Spiele\CorsixTH\Lua\app.lua:774>

Warning: Proper idle not in action_queue
An error has occured!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The timer handler.
A stack trace is included below, and the handler has been disconnected.
D:\Spiele\CorsixTH\Lua\humanoid_actions\walk.lua:174: Suspected infinite loop
stack traceback:
        [C]: in function 'error'
        D:\Spiele\CorsixTH\Lua\app.lua:797: in hook '?'
        D:\Spiele\CorsixTH\Lua\humanoid_actions\walk.lua:174: in function <D:\Spiele\CorsixTH\Lua\humanoid_actions\walk.lua:137>
        (...tail calls...)
        D:\Spiele\CorsixTH\Lua\entity.lua:218: in method 'tick'
        D:\Spiele\CorsixTH\Lua\world.lua:1121: in method 'onTick'
        D:\Spiele\CorsixTH\Lua\app.lua:878: in function <D:\Spiele\CorsixTH\Lua\app.lua:875>
        (...tail calls...)
        D:\Spiele\CorsixTH\Lua\app.lua:779: in function <D:\Spiele\CorsixTH\Lua\app.lua:774>

Warning: Proper idle not in action_queue
```

**Comment by TheCycoONE** [comment] 2015-10-18 20:50
Generally the infinite loop in the walk handler issue happens when part of the hospital is unreachable. This shouldn't happen, but there are a couple cases where you can build a room in an unreachable area, or block a door with a radiator.

The other issue is new to this ticket. Could you link a save game to reproduce the issue?

**Comment by Stefan1200-de** [comment] 2015-10-19 16:33
Well, unfortunately I don't have a save game of it just before it happens. But I have the current save game of that game (game continued running after clicking away that error message and loading a save game again). And I guess I know the guy producing that error message. Because I have one guy in my hospital, which is not moving since years (in hospital time). See the following screenshot (of course the big red arrow was added by me ;)):
![corsixth-0 50_ direct3d lua5 3 64bit](https://cloud.githubusercontent.com/assets/15168351/10583837/89d38076-768f-11e5-87c6-b3c9a3d84826.png)

**Comment by Alberth289346** [comment] 2016-05-11 18:27
The first (infinite recursion due to non-reachable area) should have its own issue (can't find it currently, but we have a plan somewhere to resolve it).

Payments have been completely rewritten with the price impact, making the second issue obsolete.

Closing this issue, as there is nothing here to do anymore

**Closed by Alberth289346** 2016-05-11 18:27 UTC
