### ISSUE TITLE
Rendering order issue

### ISSUE THREAD

**Issue by phobos2077** [CorsixTH/CorsixTH#1215] opened 2017-04-23 16:37 UTC
#### Describe the issue
Walls are rendered over the objects.

![Screenshot](https://1.downloader.disk.yandex.ru/disk/5da4f49962ba668eaac30efb9dc9e2ad5ac9c62b47575e520758b2dd626763c9/58fd1074/0Mb7cljwE6RVQ56yJkHXptvR-xPmvJJ3wYegKyvsdy2CetmyQ_kKuCyfHKanZFzB8vKV-6fFjpCbjp4Wej40rQ%3D%3D?uid=0&filename=2017-04-23_23-36-23.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&fsize=481733&hid=6b9a81f6940cbf213bd4d0fc3aabbf6e&media_type=image&tknv=v2&etag=31ea5b3a122f77cdbac63d33b72263ee)

#### Steps to Reproduce
1. *Load save game attached to this ticket*

2. See chairs in the training room (southern block).

#### Save Game
https://yadi.sk/d/IC8bO2Sv3HGS69

#### Expected Behavior
All chairs should be fully visible.

#### System Information
**CorsixTH Version:** *e.g. 0.60*

**Operating System:** *e.g. Windows 7*

**Theme Hospital Version:** *GOG.com*

**Comment by TheCycoONE** [comment] 2017-04-24 18:44
Duplicate of #475

**Closed by TheCycoONE** 2017-04-24 18:44 UTC
Labels: Component-Graphical
