### ISSUE TITLE
Crash:  CorsixTH\Lua\world.lua:1804

### ISSUE THREAD

**Issue by KeeperSt** [CorsixTH/CorsixTH#1246] opened 2017-09-15 16:04 UTC
#### Describe the issue

Welcome to CorsixTH v0.60!

---------------------------------------------------------------

This window will display useful information if an error occurs.

---------------------------------------------------------------

Checking for CorsixTH updates...
You are running the latest version of CorsixTH.
An error has occurred!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The timer handler.
A stack trace is included below, and the handler has been disconnected.
F:\Archivos de programa\CorsixTH\Lua\world.lua:1804: bad argument #2 to 'findObject' (number expected, got nil)
stack traceback:
        [C]: in method 'findObject'
        F:\Archivos de programa\CorsixTH\Lua\world.lua:1804: in method 'findObjectNear'
        F:\Archivos de programa\CorsixTH\Lua\entities\staff.lua:186: in method 'tick'
        F:\Archivos de programa\CorsixTH\Lua\world.lua:1075: in method 'onTick'
        F:\Archivos de programa\CorsixTH\Lua\app.lua:1000: in function <F:\Archivos de programa\CorsixTH\Lua\app.lua:997>
        (...tail calls...)
        F:\Archivos de programa\CorsixTH\Lua\app.lua:901: in function <F:\Archivos de programa\CorsixTH\Lua\app.lua:896>

Warning: No event handler for timer

#### System Information
**CorsixTH Version:** 0.60

**Operating System:** Windows 10*

**Theme Hospital Version:** CD

### Additional Info
![med general15](https://user-images.githubusercontent.com/31771827/30492286-46ca6f84-9a40-11e7-94a6-c9ad65438842.jpg)

**Comment by TheCycoONE** [comment] 2017-09-16 00:54
duplicate of #1195

**Closed by TheCycoONE** 2017-09-16 00:54 UTC
