### ISSUE TITLE
Game crash without stack trace

### ISSUE THREAD

**Issue by bobcanthelpyou** [CorsixTH/CorsixTH#752] opened 2015-06-14 16:23 UTC
I am running a trunk version (master branch) of CorsixTH and sometimes the game crashes suddenly

The following message is shown but the stack trace is missing
```
An error has occured!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The frame handler.
A stack trace is included below, and the handler has been disconnected.
```

Is there something that i missed and should be enabled to show the stack trace?

**Comment by TheCycoONE** [comment] 2015-06-15 14:11
Duplicate of #327 
I've seen this myself, though never when I was able to grab sufficient debugging information.

**Closed by TheCycoONE** 2015-06-15 14:11 UTC
Labels: State-Duplicate
