### ISSUE TITLE
0.64 RC1 Installer doesn't allow ISO choice

### ISSUE THREAD

**Issue by Richard-L** [CorsixTH/CorsixTH#1628] opened 2020-06-01 22:19 UTC
With the new v0.64 RC1, the Windows installer prompts for a TH installation and does not offer the alternative of pointing to an ISO of the original game. Would be a nice addition.

~~Potentially even pointing to the demo version of TH could be something to consider, if possible.~~

Many thanks.

**Comment by TheCycoONE** [comment] 2020-06-02 01:57
I am able to choose the path to the ISO if I paste it directly into the box instead of clicking the ... browse button.

I wasn't able to find a dialog for NSIS installers for selecting a file or a directory, so that might be all we can do for now.

**Comment by lewri** [comment] 2020-06-02 09:23
I also noticed that the TH Data selector in the settings menu of the game is missing any prompts about using an ISO. It still alludes to selecting a folder rather than an ISO

![image](https://user-images.githubusercontent.com/20030128/83503496-0fd9e800-a4bb-11ea-8ef0-37e8c68bcf1f.png)

![image](https://user-images.githubusercontent.com/20030128/83503442-f769cd80-a4ba-11ea-915f-e55e418a4af1.png)

**Comment by TheCycoONE** [comment] 2020-06-02 11:06
Separate issue, and easy for anyone to pick up. Those prompts are in english.lua

**Comment by TheCycoONE** [comment] 2020-06-03 02:44
For what it's worth, I'm working on the installer. I had to move from InstallOptions to nsDialogs to get more control of the dialog, and I will need to add a radio button for selecting ISO or Directory.

There won't be time for translations. All in all I'm not sure I want it to land in 0.64.

**Comment by Richard-L** [comment] 2020-06-03 08:48
It's necessary to extract the game files, whether they stem from a cd image rip or demo self-extractor, correct? You cannot point to the ISO file itself?

Since there are so many different cd image formats beyond ISO, and since I presume corsix TH only needs select files, I would instruct the user to either mount their image and point to it, or copy all of its contents to a temporary directory they can delete after. Most archiving apps today (ie 7zip) can extract image files, meaning you wouldn't need to initiate a virtual drive. Some people might prefer this second way of doing it.

In what physical ways does the demo come? I presume a self-extractor? I'd imagine it has to be extracted too and the installer pointed to those files. So it's essentially the same as copying from a CD.

Thus the radio buttons during this step of the installer would be:

1) Point to an inserted CD of Theme Hospital (whether actually physical or virtual is up to the user)

2) Point to the game files copied from the Theme Hospital CD or Demo version (if the user chooses this option you could notify them this temporary directory "can now be deleted" after import)

3) Point to the install directory of Theme Hospital if the game is already installed the legacy way.

The last option I think will likely never happen to any people stumbling upon the project and wanting to try it out. You could get rid of it if you ask me. Corsix-TH should create its own independent environment of asset files based on the first two options.

**Comment by mugmuggy** [comment] 2020-06-03 10:20
Yes, just the iso file will do. Standard ISO9660 compliant iso files. I think TheCycoOne indicated movies don't work though. I've done all 3 those options, having Origin installed copy of Theme Hospital and normally run Corsix referring to that install location.

I think you'll find this 3rd/default option is deliberate as this prevents you making a 'copy'

**Comment by TheCycoONE** [comment] 2020-06-03 10:48
We don't pollute the existing directory in any way so I don't know why we would copy any assets.

https://github.com/CorsixTH/CorsixTH/wiki/Getting-Started

**Comment by TheCycoONE** [comment] 2020-06-03 11:05
The 0.64 ISO support adds one more option - the game has built in support for the ISO filesystem so it can read files directly off the image without mounting the image in your operating system. This is just one way to run CorsixTH and frankly not one I expect many people to use - but there was a half functional implementation in the code for years and given the choice of cleaning it up or dropping it I chose to clean it up, so if someone happens to have an ISO collection of their old CD games they could point and go.

I see the first install experience on Windows didn't quite facilitate that as per this issue. I will fix that soon, targetting 0.65 because it needs new translations to toggle between the directory selection vs ISO file selection.

Everything else is out of scope of this issue.

**Comment by TheCycoONE** [comment] 2020-06-03 11:09
I will clarify in the release notes.

**Comment by Richard-L** [comment] 2020-06-03 12:24
Like I said, you copy because my image is CCD and BIN, for example. You'll find people with MDX, etc.

So I wouldn't insist on ISO and instead offer the option to read extracted/copied files from a user-defined folder.

Issues that tackle very specific aspects of a bug in the traditional sense are rare. So please allow some general discussion. We can then create more orderly issues as you see fit.

**Comment by tobylane** [comment] 2020-06-03 12:54
The ISO I made (macos Disk Utility) came out as a .dmg, I renamed it .iso and it was accepted.

Switching to the real disc caused CorsixTH to disappear for ~8 seconds, which was surprising. Is it worth adding a message or confirm dialog for such slow media?

**Comment by TheCycoONE** [comment] 2020-06-03 18:03
@Richard-L we have the ability to read from an extracted/copied user-defined folder. We've always had that ability. There is no plan to insist on an ISO. I don't see how it's helpful for us to copy an existing filesystem on behalf of the user, when they can do that with a few keypresses in the file manager of their choice.

**Comment by TheCycoONE** [comment] 2020-06-03 18:06
@tobylane - yes, I wouldn't expect CorsixTH to disappear between the boot screen and the files being loaded from media. I don't think that's particular to ISO?

**Comment by lewri** [comment] 2021-05-18 17:43
Looking into this again it looks like part of the issue is down to the kind of selector dialog you use (folder browse).
However, I'm sure in the past if you use the `file selector` version instead you should have an open to choose folders too (though not many installers etc seem to use it).

**Comment by lewri** [comment] 2021-05-18 17:45
Alternatively, you can add into the installer another page of asking user to choose how they want to use the game files... then present the appropriate picker on the next page.

**Comment by Alberth289346** [comment] 2021-05-19 09:24
Perhaps merge these? Point at a folder means "check the folder". Point at a file means "check for iso file." Don't think there can be confusion unless you can also point at files in a folder to state the data file location.

"Set later" is a bit of a non-option, you cannot run the program without it (maybe with demo files, but even those need to be supplied I guess?)

**Comment by TheCycoONE** [comment] 2021-05-20 00:55
The installer uses standard controls. I don't have a lot of options here. I'm pretty sure I made a PR at one point.

**Comment by TheCycoONE** [comment] 2021-05-20 01:01
Now that this has come up again. I think I'll go ahead with dropping it from the installer. The first run auto detection is friendlier and the installer gets no attention.

**Closed** 2021-05-21 22:52 UTC
