### ISSUE TITLE
Suspected infinite loop crashed the game

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#563] opened 2014-12-24 12:45 UTC
_From [Joachim....@googlemail.com](https://code.google.com/u/109318962023481909085/) on July 26, 2013 01:40:17_

CorsixTH 0.21, Win7 x64

load 12-4 crash.sav, it is the last level of TH. And I am already out of debt earlier than ever before _wohoo_.
Maybe use my AppData\Roaming\CorsixTH\confix.txt
I am watching the training room how one of the doctors stands up.
No need to click anything.
Then the game will stop responding.
gamelog.txt is vom 19th, so it may not contain newer entries or did not write anything during crash.

Have fun to analyse! I'll try an older autosave to check whether it repeats there too. Hail Autosave!

**Attachment:** [12-4 crash.sav config.txt gamelog.txt](http://code.google.com/p/corsix-th/issues/detail?id=1672)

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=1672_

**Comment by Alberth289346** [comment] 2016-12-02 12:50
Savegame is not available anymore (googlecode fails to get the page of the http address)

**Comment by MarkL1961** [comment] 2016-12-02 16:17
I have a save with that name so likely to be from this issue @Alberth289346 

https://www.dropbox.com/s/9o9qqgrcjasj6q0/12-4%20crash.sav?dl=0

**Comment by mugmuggy** [comment] 2017-10-27 14:30
Duplicate of #1105. Taken the save that MarkL1961 has, let it run it goes into infinite loop. Put the 'fix' in that I have in [1105 comment](https://github.com/CorsixTH/CorsixTH/issues/1105#issuecomment-339650049), and immediately pause game, build and move an object, resume game no infinite loop.

Dodgy tile here is 68,76 in the SW corner of general diagnosis

**Comment by MarkL1961** [comment] 2017-10-27 14:34
I'll close it then

**Closed by MarkL1961** 2017-10-27 14:34 UTC
Labels: P3 Medium, Googlecode
