### ISSUE TITLE
warning no event handler for timer

### ISSUE THREAD

**Issue by babalzac** [CorsixTH/CorsixTH#1497] opened 2019-02-18 20:35 UTC
Hello, the game crashed in the last level, i've just finished all the objectives... The game just freeze,  I can do everything but time doesn't run... I'm stuck in the same day and people don't move !
Someone can help ?

what the app says ->

n your firewall.
An error has occurred!
Almost anything can be the cause, but the detailed information below can help th
e developers find the source of the error.
Running: The timer handler.
A stack trace is included below, and the handler has been disconnected.
Lua\entities\humanoid.lua:868: Action queue was empty. This should never happen.

humanoid - class: Standard Male Patient
Warmth: 0.238   Happiness: 1.000   Fatigue: 0.000  Thirst: 0.132  Toilet_Need: 0
.606   Health: 0.000
Actions: []
stack traceback:
        [C]: in function 'error'
        Lua\entities\humanoid.lua:868: in method 'getCurrentAction'
        Lua\hospital.lua:690: in method 'countSittingStanding'
        Lua\hospital.lua:720: in method 'checkFacilities'
        Lua\hospital.lua:974: in method 'onEndDay'
        Lua\world.lua:998: in method 'onTick'
        Lua\app.lua:1014: in function <Lua\app.lua:1011>
        (...tail calls...)
        Lua\app.lua:915: in function <Lua\app.lua:910>

Warning: No event handler for timer

sorry for my poor english !!! and thank you for your help !

**Comment by TheCycoONE** [comment] 2019-02-19 00:10
I believe this is a duplicate of #1439 
As a workaround, there is a male patient, probably sitting (near / in toilet), that is dying. If you load an earlier save and keep them up / outside the room when they die you shouldn't get the crash.

**Closed by TheCycoONE** 2019-02-19 00:10 UTC
