### ISSUE TITLE
Error with button up handler

### ISSUE THREAD

**Issue by MarkL1961** [CorsixTH/CorsixTH#1156] opened 2016-11-11 20:16 UTC
Accepted an emergency for slack tongue which I can treat, but it has not been discovered yet!

Load the save and accept the emergency.
As patients arrive open patient dialogue and click on casebook icon
Normally this would then open the casebook with the diagnosed illness selected.

Because of the way this has played out and due to a lack of funds I have discovered and built a treatment room for something yet to be discovered.  If I had the funds to build an x-ray I may then discover slack tongue.
Perhaps it should not be possible to have an emergency for something you have not discovered.
Patients with slack tongue have been arriving for sometime, but as I can't diagnose it yet I can only send them home (which I think is correct)

https://www.dropbox.com/sh/5pc51vpf1vcgsfs/AADTcwdeFKr_Eb1hsyDkf8Tca?dl=0

**Comment by MarkL1961** [comment] 2016-11-16 19:58
Level 6 and accepted an emergency for invisibility which I have not discovered yet but can apparently treat

Error in buttonup handler: 
...ds\CorsixTH (6)\Lua\dialogs\fullscreen\drug_casebook.lua:151: attempt to index a nil value (field '?')
stack traceback:
	...ds\CorsixTH (6)\Lua\dialogs\fullscreen\drug_casebook.lua:151: in method 'updateIcons'
	...ds\CorsixTH (6)\Lua\dialogs\fullscreen\drug_casebook.lua:139: in method 'selectDisease'
	...ds\CorsixTH (6)\Lua\dialogs\fullscreen\drug_casebook.lua:92: in local 'constructor'
	C:\Users\Mark\Downloads\CorsixTH (6)\Lua\class.lua:74: in global 'UICasebook'
	...sers\Mark\Downloads\CorsixTH (6)\Lua\dialogs\patient.lua:322: in local 'callback'
	C:\Users\Mark\Downloads\CorsixTH (6)\Lua\window.lua:682: in method 'handleClick'
	C:\Users\Mark\Downloads\CorsixTH (6)\Lua\window.lua:1478: in field 'onMouseUp'
	...sers\Mark\Downloads\CorsixTH (6)\Lua\dialogs\patient.lua:228: in method 'onMouseUp'
	C:\Users\Mark\Downloads\CorsixTH (6)\Lua\window.lua:1462: in field 'onMouseUp'
	C:\Users\Mark\Downloads\CorsixTH (6)\Lua\ui.lua:650: in function <C:\Users\Mark\Downloads\CorsixTH (6)\Lua\ui.lua:637>
	(...tail calls...)
	C:\Users\Mark\Downloads\CorsixTH (6)\Lua\app.lua:906: in function <C:\Users\Mark\Downloads\CorsixTH (6)\Lua\app.lua:901>

https://www.dropbox.com/s/38u6qujdgv8d3jy/Level%20six.sav?dl=0

As clicking on the casebook icon from patient menu should open casebook on that patients illness, perhaps the solution for when you have not discovered it (emergencies) is for it to open on General Practice or better still disable the button as you would normally. i.e. when someone has not been diagnosed yet

**Comment by MarkL1961** [comment] 2016-11-17 19:12
One possible solution is to amend dialogs\patient.lua from line 321 that stops the button being clicked on if it is an undiscovered disease

function UIPatient:viewDiseases()
  local patient = self.patient
  if patient.hospital.disease_casebook[patient.disease.id].discovered then
  local dlg = UICasebook(self.ui, self.patient.diagnosed and self.patient.disease.id or nil)
  self.ui:addWindow(dlg)
  end
end

**Comment by Alberth289346** [comment] 2016-11-18 08:04
You shouldn't be able to build anything you haven't discovered, or get any emergencies for undiscovered diseases, I think. At least it doesn't make much sense to me to allow that. What do you think?

**Comment by MarkL1961** [comment] 2016-11-18 15:55
Look at level 1 for example, inflation room is there from the start and you discover bloaty head later in the game.  There are other levels where you have the cure before you have the disease.
I think we had this discussion several years ago.  These are the original levels and no matter how you set things up and the times you want them to appear there will always be a player who by chance gets things out of order like I did. 
I agree on the logic for an emergency, but who can predict which patients turn up and in sufficient volume for you to discover what they have before a scheduled emergency?  There are some diseases you can't discover until you have the right diagnostic machine built.  If you set your research priorities to drugs ahead of other things you can skew any timetable the mapmaker may have intended.

I think its best to expect such things might happen and make sure they don't cause an error

**Comment by Alberth289346** [comment] 2016-11-18 16:23
Level 1 doesn't really count, as you don't have research there afaik, it's an introducory level into the mechanics.

I agree there should not be an error, but I also don't know what should happen with an emergency. Do you know what the original game does? Did we write these decisions down somewhere?
I don't even have any idea what's in a level file too :(

**Comment by MarkL1961** [comment] 2016-11-18 17:30
If I am reading the level file correctly the emergency for invisibility comes in year one between month 8 and 12 and you need the scanner to diagnose it which you don't get until month 14. They would be around the hospital from around month 5, but you could not discover what they have early enough for the emergency unless you concentrated research towards diagnostic machines and got the scanner earlier than planned.
There are other levels where you can cure something before it is discovered and where you can build the cure room before you know what the room is for.  The game is mad like that, the same as it is mad that when you move up a level you forget everything you discovered at your previous hospital.

**Comment by Lego3** [comment] 2016-11-19 00:08
I remember that at some point illnesses from emergencies were (supposed to be) automatically discovered, so this sounds like a regression.

**Comment by MarkL1961** [comment] 2016-11-19 09:34
That sounds like a better option @Lego3

**Comment by TheCycoONE** [comment] 2017-01-06 13:34
Related to #506

**Comment by TheCycoONE** [comment] 2017-01-06 13:37
It looks like we never addressed this. We did investigate the original game and found that emergencies for undiscovered diseases were simply skipped there, as per the discussion in #506. Resolving #506 will resolve this as well.

**Comment by lewri** [comment] 2020-09-24 22:18
It still looks like this is still broken somewhat. I'm not sure if Alberth's fix was implemented from #506 .

While you can now accept a fax for an unknown disease and treat patients with the disease (despite it being missing from the casebook)... and not killing people(?!); trying to check their drug casebook still causes a break.

I would probably rather go with no auto-discovering the disease. I would rather run a check in createEmergency to make sure we choose a disease that we know about. If there are (probably in rare cases) no diseases available then we abort the emergency.

**Comment by Alberth289346** [comment] 2020-09-27 06:34
I have no memory of getting that fix implemented, so I am guessing it's still broken.

I agree that not getting such patients is the better direction. However rather than picking a known disease, I'd say don't send an emergency. In that way, the player gets less benefits if not researching fast enough.

Another option is to get them, but without a known disease you cannot just cure them. Instead they have to go through the entire disease triaging system, quite likely killing them in the process. Seems like an option for the "make it really hard" difficulty level :)

**Closed** 2020-11-24 13:39 UTC
Labels: Accepted, Reproducible, bug
