### ISSUE TITLE
Scanner room frozen with doctor and patient

### ISSUE THREAD

**Issue by Towncivilian** [CorsixTH/CorsixTH#160] opened 2014-02-01 23:32 UTC
What steps will reproduce the problem?
1. Load save file
2. Attempt to pick up doctor in scanner room (since the patient seems to be 'stuck' in the room)
3. Doctor disappears and mouse is "stuck"; can't select anything or right click/left click, can expand menu items by just hovering over them and not needing to hold down left mouse button

What is the expected output? What do you see instead?
Expected doctor to be picked up; doctor disappears instead and mouse is "stuck" unable to select anything other than menu options

Firing the doctor to get him to leave the room results in the doctor being stuck outside the room's door and the patient also remaining stuck; a prompt notifying me of an error pops up as well.

What version of CorsixTH are you using (e.g. "0.21", "SVN r123")?
r2628 SDL

What operating system / compile settings are you using?
Windows 8.1 x64

What level was this on (e.g. "Demo level", "Full game level 12")?
Full game, level "Frimpton-On-Sea" (not sure which level it is numerically), hard difficulty

Save file and gamelog are here: https://drive.google.com/file/d/0B5mpmm482r0VMU43WEJYSVBGSnM/edit?usp=sharing

**Comment by TheCycoONE** [comment] 2015-05-05 16:20
Thanks adrianopol.  Is there any reason you are not using 0.40 final?

**Comment by adrianopol** [comment] 2015-05-05 16:50
Oh, sorry, I didn't notice the release has been already published! I will update the [ebuild](https://github.com/adrianopol/paq-overlay/blob/master/games-simulation/corsix-th/corsix-th-0.40_rc3.ebuild) and try this version (0.40) in a few days.

Thank you.

**Comment by lewri** [comment] 2020-06-09 15:05
No response, I would assume resolved.

**Comment by TheCycoONE** [comment] 2020-06-09 17:03
@mugmuggy is this a duplicate of any of the stuck bugs that you have fixed?

**Comment by mugmuggy** [comment] 2020-06-09 21:16
@TheCycoOne Not specifically, without save going to be impossible to guess if we would be seeing the cause or a symptom of an earlier cause.

**Comment by lewri** [comment] 2020-06-09 22:22
Both saves are also lost to the void I believe...

**Closed** 2020-06-10 01:03 UTC
Labels: Priority-High, State-Investigating, Type-Game Error
