### ISSUE TITLE
vomit prevents a room from being blueprinted, and blueprint has to be moved for clean up to be detected

### ISSUE THREAD

**Issue by mattmill30** [CorsixTH/CorsixTH#147] opened 2014-01-16 05:25 UTC
When a person vomits, it is not possible to place a blueprint over it.
It would be much more useful for the blueprint to be queued (such as whilst people get out of the area), but for a janitor to be allowed entry to clean up the vomit and then leave again.

In addition, once vomit has been cleaned up, the blueprint does not automatically update and the room build dialog doesn't enable to tick-box, until the blueprint is edited (e.g. moved  away - and optionally back - or resized).

**Comment by Alberth289346** [comment] 2015-06-28 20:21
I just found that #708 is caused by vomit in the room. Would that issue get resolved by your patch?

**Comment by J-Shep** [comment] 2015-06-28 20:49
@Alberth289346 My patch would make a vomit tile blue instead of red in a room's blueprint and then it would delete the vomit when a player clicked OK to enter the "doors and windows" stage of editing/making a room.

I think this bug's issue is actually: how did the vomit get into this room? when patients shouldn't be able to vomit in rooms and the existing room editing code shouldn't allow a player to build room's over vomit tiles.

You could try deleting this room and then seeing if you can build a new room over it and if you can then you could debug the "edit room" code's blueprint checking code while making a new room to find out why it ignores the vomit tile.

**Comment by J-Shep** [comment] 2015-06-28 21:21
@Alberth289346 I've not looked at my patch's code for a long time but if it won't fix the issue mentioned in #66, which allows room to be built over vomit by not doing a blueprint check just before confirm is clicked, then I will make sure it does.

**Comment by Alberth289346** [comment] 2015-06-29 05:02
#708 is a crash when the game is trying to get from a built room back to blue-print by collecting the objects in the room (including some litter), and then crashing on the litter. In other words, it never reaches blue-print stage from the built room due to litter.

To me, that is different from clearing litter when placing a new blue-print. I mostly wonder what the relation is with this problem.
Does #708 happen due to a litter-accident while the room was built, or is there another way to get litter in the room? If you fix the litter-accidents while building, would problems like #708 still happen?

As for fixing stuff for 0.50, you seem to have many irons in the fire and time is running short. May I suggest you take out one iron at a time and deal with it completely, preferably selecting an almost ready iron first?

**Comment by J-Shep** [comment] 2015-06-29 10:03
@Alberth289346 Thanks for the good suggestion: I actually can't finish any of my CorsixTH tasks at the moment because I can't do anything on my PC without a hacker/hackers being able to interfere and he/they like to interfere with my CorsixTH work. I would like to contribute but not while hackers can get a laugh out of causing unfixable CorsixTH programming problems on my PC.

I've reopened #708. It would be best for you to work on fixing this instead of me before the 0.50 bug fix deadline because you won't have any hackers interfering with your work.

**Comment by J-Shep** [comment] 2016-03-05 11:17
Hi,

Has anyone taken over this task during my contribution hiatus?

**Comment by Alberth289346** [comment] 2016-03-05 14:12
I had a go, see #922 but that failed if you reverted the room build process a few steps.
Trying to fix that implies hacking the handyman job queue, which is a hack on top of the dispatch queue, which imho should be done by the handyman itself, but it can't due to the current action system. (Or something like that). Long story short, I wandered off from fixing this issue to rebuilding the action system :)

**Comment by J-Shep** [comment] 2016-03-05 17:06
@Alberth289346 Thanks for this info, I will take a look at your work for #922 and this issue when I've finally implemented automatic error reporting within the next few days hopefully, if I don't have any problems compiling CorsixTH like I did in the past.

**Comment by TheCycoONE** [comment] 2016-08-26 15:21
Resolved by #1119

**Closed by TheCycoONE** 2016-08-26 15:21 UTC
Labels: S:Accepted, P3 Medium
