### ISSUE TITLE
Game freeze due to infinite loop in pathing

### ISSUE THREAD

**Issue by Frassle** [CorsixTH/CorsixTH#717] opened 2015-03-13 01:44 UTC
###### What steps will reproduce the problem?
Load the save game [here](https://drive.google.com/file/d/0BzdXpBSuyzy3TEtPSFN2a2RQZkk/view?usp=sharing) and wait a few seconds

###### What is the expected output? What do you see instead?
Game should keep running, instead freezes.

###### What version of CorsixTH are you using (e.g. "0.30", "4c66e39985")?
0.40

###### What operating system / compile settings are you using?
Windows 7 x64

###### What level was this on (e.g. "Demo level", "Full game level 12")?
Full game (Not sure which level, maybe 6?)

###### Upload a saved game file (preferably an autosave from before the error) if you
have one and it is relevant.
[save](https://drive.google.com/file/d/0BzdXpBSuyzy3TEtPSFN2a2RQZkk/view?usp=sharing)

###### If possible, also upload the gamelog.
No gamelog produced

###### Please provide any additional information below.

Originally raised on #618. @TheCycoONE tracked the freeze down to an infinite loop in the pathing algorithm
> I have determined that there is an infinite path finding loop when the man in the bathroom reaches the door. (tile 58,60)
> In particular it keeps calling https://github.com/CorsixTH/CorsixTH/blob/582fee058e/CorsixTH/Lua/humanoid_actions/walk.lua#L179

**Comment by TheCycoONE** [comment] 2015-03-13 12:22
Thanks @Frassle

**Comment by TheCycoONE** [comment] 2015-03-13 12:38
To be clear the infinite loop is in the action queue, when it fails to find a path.  For reasons I haven't diagnosed yet, recalc_route is always being set to true instead of going to action_walk_raw and opening the door.

**Comment by TheCycoONE** [comment] 2015-03-15 00:29
There is a radiator in front of the bathroom door (inside).  If you rush you can remove it and avoid the freeze.  Duplicate of #221

**Closed by TheCycoONE** 2015-03-15 00:29 UTC
Labels: duplicate

**Comment by Frassle** [comment] 2015-03-15 00:36
Thanks! Will keep an eye out to not place objects like that from here on.
