### ISSUE TITLE
Can't start new game

### ISSUE THREAD

**Issue by PenguiN560** [CorsixTH/CorsixTH#1198] opened 2017-03-08 20:32 UTC
#### Describe the issue
Can't start new game. When I try start new campaign, i saw loading movie with sound and after this nothing is happens. I try to wait about 1 min and nothing was happens.

#### Steps to Reproduce
1. lunch game in console
```$ corsix-th```
2. Click campaign
3. Click Start

#### Save Game
none

#### Expected Behavior
Starting game

#### System Information
**CorsixTH Version:** 0.60

**Operating System:** Gentoo ~amd64

**Theme Hospital Version:** CD

#### Gamelog.txt
There is no Gamelog.txt at `~/.config/CorsixTH/`

### Additional Info
```
$ corsix-th 


---------------------------------------------------------------

Welcome to CorsixTH v0.60!

---------------------------------------------------------------

This window will display useful information if an error occurs.

---------------------------------------------------------------

Checking for CorsixTH updates...
An error has occurred!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The movie_over handler.
A stack trace is included below, and the handler has been disconnected.
/usr/share/lua/5.1/socket/http.lua:189: use of undeclared variable 'PROXY'
stack traceback:
        [C]: in function 'request'
        /usr/share/games/CorsixTH/Lua/app.lua:1448: in function 'checkForUpdates'
        /usr/share/games/CorsixTH/Lua/app.lua:463: in function 'loadMainMenu'
        /usr/share/games/CorsixTH/Lua/app.lua:293: in function 'callback_on_destroy_movie'
        /usr/share/games/CorsixTH/Lua/movie_player.lua:260: in function '_destroyMovie'
        /usr/share/games/CorsixTH/Lua/movie_player.lua:229: in function 'onMovieOver'
        /usr/share/games/CorsixTH/Lua/app.lua:1078: in function </usr/share/games/CorsixTH/Lua/app.lua:1077>
        (tail call): ?
        /usr/share/games/CorsixTH/Lua/app.lua:901: in function </usr/share/games/CorsixTH/Lua/app.lua:896>

starting game with difficulty full
Warning: No event handler for movie_over
```
![screenshot_20170308_232154](https://cloud.githubusercontent.com/assets/816595/23722565/4356e12e-045f-11e7-9b11-4550ca33117a.png)

**Comment by PenguiN560** [comment] 2017-03-08 20:45
Looks like the problem is check for update error. I try set `check_for_updates = false` in config.txt and it works fine

**Comment by TheCycoONE** [comment] 2017-03-08 20:58
Duplicate of #1061

**Closed by TheCycoONE** 2017-03-08 20:58 UTC

**Comment by TheCycoONE** [comment] 2017-03-08 20:59
Please report this to the ebuild maintainer. You need a newer version of luasocket.

**Comment by PenguiN560** [comment] 2017-03-08 21:12
Thank you for answer. As I understand my version luasocketis broken and I should use newly version than =dev-lua/luasocket-3.0_rc1-r3, right? Or what's wrong?

**Comment by TheCycoONE** [comment] 2017-03-09 13:49
@PenguiN560 exactly. That version is over 3 years old and known to be broken. Unfortunately there hasn't been another official release. Most distributions are shipping patched versions of luasocket, but gentoo doesn't seem to be.

There is an open upstream bug here: https://bugs.gentoo.org/show_bug.cgi?id=585962 but it doesn't seem to have any traction.

For now I suggest either turning off the update check like you did (it serves no purpose when you have a package manager to handle your updates), or build a recent git copy of luasocket.

**Comment by PenguiN560** [comment] 2017-03-09 15:41
@TheCycoONE Ok, thank you so much.
