### ISSUE TITLE
Janitors Error When Stuck on doors to broken rooms.

### ISSUE THREAD

**Issue by mrbenjamin1** [CorsixTH/CorsixTH#641] opened 2015-01-29 01:13 UTC
I have been getting errors/crasheswhen the janitor goes to fix a machine that is now destroyed (this would normaly happen after an earthquake. the error recovery message pops up with the janitors info dispalyed but this info box cannot be closed meaning and the game stops but sound, mouse still works and i can use the menus at the top (but not click on anything) i have to minimise the game and close it that way then reload. when i reload the save the janitor is still stuck but the game plays as normal. this error has happened twice now in the Custom camp level 1.

i have attached the log

thanks Ben

___________________________

Created game with savegame version 91.
Warning: Trying to remove nonexistant room build callback (function: 0x0ecb17f0) from humanoid (table: 0x0a294298).
Warning: Trying to remove nonexistant room remove callback (function: 0x0ecfae38) from humanoid (table: 0x0a294298).
Warning: Trying to remove nonexistant room build callback (function: 0x13a9a640) from humanoid (table: 0x0989bc60).
Warning: Trying to remove nonexistant room remove callback (function: 0x0be326e0) from humanoid (table: 0x0989bc60).
Warning: Trying to remove nonexistant room build callback (function: 0x0ec97e70) from humanoid (table: 0x0add32a8).
Warning: Trying to remove nonexistant room remove callback (function: 0x0d1dbb90) from humanoid (table: 0x0add32a8).
Warning: Trying to remove nonexistant room build callback (function: 0x0bfe1dc0) from humanoid (table: 0x0ec65368).
Warning: Trying to remove nonexistant room remove callback (function: 0x0a2d47b0) from humanoid (table: 0x0ec65368).
Warning: Trying to remove nonexistant room build callback (function: 0x0984f320) from humanoid (table: 0x0d2b00b0).
Warning: Trying to remove nonexistant room remove callback (function: 0x09856dd0) from humanoid (table: 0x0d2b00b0).
Warning: Trying to remove nonexistant room build callback (function: 0x0a2d92d8) from humanoid (table: 0x0ed1c888).
Warning: Trying to remove nonexistant room remove callback (function: 0x097dabb0) from humanoid (table: 0x0ed1c888).
Warning: Trying to remove nonexistant room build callback (function: 0x139a3f28) from humanoid (table: 0x0983e8f0).
Warning: Trying to remove nonexistant room remove callback (function: 0x0d2a5450) from humanoid (table: 0x0983e8f0).
Warning: Trying to remove nonexistant room build callback (function: 0x0bde8f68) from humanoid (table: 0x0a3c2b08).
Warning: Trying to remove nonexistant room remove callback (function: 0x0bde8f28) from humanoid (table: 0x0a3c2b08).
Warning: Trying to remove nonexistant room build callback (function: 0x0985b9e8) from humanoid (table: 0x0bfd7b58).
Warning: Trying to remove nonexistant room remove callback (function: 0x0be42ad8) from humanoid (table: 0x0bfd7b58).
Error in frame handler: 
C:\Program Files\CorsixTH\Lua\dialogs\place_staff.lua:78: bad argument #1 to 'getCellFlags' (Map co-ordinates out of bounds)
stack traceback:
	[C]: in function 'getCellFlags'
	C:\Program Files\CorsixTH\Lua\dialogs\place_staff.lua:78: in function 'draw'
	C:\Program Files\CorsixTH\Lua\window.lua:1238: in function 'draw'
	C:\Program Files\CorsixTH\Lua\game_ui.lua:150: in function 'draw'
	C:\Program Files\CorsixTH\Lua\app.lua:869: in function 'dispatch'
	C:\Program Files\CorsixTH\Lua\app.lua:753: in function <C:\Program Files\CorsixTH\Lua\app.lua:748>
Savegame version is 91 (0.40), originally it was 91 (0.40)
Warning: Trying to remove nonexistant room build callback (function: 0x085055a8) from humanoid (table: 0x057d6a88).
Warning: Trying to remove nonexistant room remove callback (function: 0x0910b518) from humanoid (table: 0x057d6a88).
Savegame version is 91 (0.40), originally it was 91 (0.40)
Warning: Trying to remove nonexistant room build callback (function: 0x053453a0) from humanoid (table: 0x044cea20).
Warning: Trying to remove nonexistant room remove callback (function: 0x044c8bc0) from humanoid (table: 0x044cea20).
Warning: Trying to remove nonexistant room build callback (function: 0x0577da40) from humanoid (table: 0x0577d770).
Warning: Trying to remove nonexistant room remove callback (function: 0x0558ff70) from humanoid (table: 0x0577d770).
Error in timer handler: 
C:\Program Files\CorsixTH\Lua\humanoid_actions\walk.lua:227: attempt to index field 'queue' (a nil value)
stack traceback:
	C:\Program Files\CorsixTH\Lua\humanoid_actions\walk.lua: in function 'action_walk_raw'
	C:\Program Files\CorsixTH\Lua\humanoid_actions\walk.lua:187: in function 'timer_function'
	C:\Program Files\CorsixTH\Lua\entity.lua:215: in function 'tick'
	C:\Program Files\CorsixTH\Lua\entities\staff.lua:146: in function 'tick'
	C:\Program Files\CorsixTH\Lua\world.lua:1103: in function 'onTick'
	C:\Program Files\CorsixTH\Lua\app.lua:852: in function 'dispatch'
	C:\Program Files\CorsixTH\Lua\app.lua:753: in function <C:\Program Files\CorsixTH\Lua\app.lua:748>
Recovering from error in timer handler...
Error in buttonup handler: 
C:\Program Files\CorsixTH\Lua\humanoid_actions\walk.lua:60: attempt to call local 'timer_function' (a nil value)
stack traceback:
	C:\Program Files\CorsixTH\Lua\humanoid_actions\walk.lua: in function 'on_interrupt'
	C:\Program Files\CorsixTH\Lua\entities\humanoid.lua:635: in function 'setNextAction'
	C:\Program Files\CorsixTH\Lua\dialogs\staff_dialog.lua:313: in function 'callback'
	C:\Program Files\CorsixTH\Lua\window.lua:645: in function 'handleClick'
	C:\Program Files\CorsixTH\Lua\window.lua:1406: in function 'onMouseUp'
	C:\Program Files\CorsixTH\Lua\dialogs\staff_dialog.lua:269: in function 'onMouseUp'
	C:\Program Files\CorsixTH\Lua\window.lua:1390: in function 'onMouseUp'
	C:\Program Files\CorsixTH\Lua\ui.lua:735: in function 'dispatch'
	C:\Program Files\CorsixTH\Lua\app.lua:753: in function <C:\Program Files\CorsixTH\Lua\app.lua:748>
Warning: Trying to remove nonexistant room build callback (function: 0x0e094490) from humanoid (table: 0x054c1ef0).
Warning: Trying to remove nonexistant room remove callback (function: 0x0e0728b8) from humanoid (table: 0x054c1ef0).
Savegame version is 91 (0.40), originally it was 91 (0.40)
Warning: Trying to remove nonexistant room build callback (function: 0x0eec3510) from humanoid (table: 0x11dfb7e8).
Warning: Trying to remove nonexistant room remove callback (function: 0x175fe420) from humanoid (table: 0x11dfb7e8).
Warning: Trying to remove nonexistant room build callback (function: 0x19351720) from humanoid (table: 0x1765a060).
Warning: Trying to remove nonexistant room remove callback (function: 0x1910e5c0) from humanoid (table: 0x1765a060).
Warning: Trying to remove nonexistant room build callback (function: 0x192de0a0) from humanoid (table: 0x1954aca0).
Warning: Trying to remove nonexistant room remove callback (function: 0x192de060) from humanoid (table: 0x1954aca0).
Warning: Trying to remove nonexistant room build callback (function: 0x192f2610) from humanoid (table: 0x11e792e0).
Warning: Trying to remove nonexistant room remove callback (function: 0x19520a98) from humanoid (table: 0x11e792e0).
Warning: Trying to remove nonexistant room build callback (function: 0x11e56250) from humanoid (table: 0x1954ac18).
Warning: Trying to remove nonexistant room remove callback (function: 0x17668908) from humanoid (table: 0x1954ac18).
Warning: Trying to remove nonexistant room build callback (function: 0x1a4bb4f8) from humanoid (table: 0x0f9fd2a8).
Warning: Trying to remove nonexistant room remove callback (function: 0x0b1908d8) from humanoid (table: 0x0f9fd2a8).
Error in timer handler: 
C:\Program Files\CorsixTH\Lua\humanoid_actions\walk.lua:227: attempt to index field 'queue' (a nil value)
stack traceback:
	C:\Program Files\CorsixTH\Lua\humanoid_actions\walk.lua: in function 'action_walk_raw'
	C:\Program Files\CorsixTH\Lua\humanoid_actions\walk.lua:187: in function 'timer_function'
	C:\Program Files\CorsixTH\Lua\entity.lua:215: in function 'tick'
	C:\Program Files\CorsixTH\Lua\entities\staff.lua:146: in function 'tick'
	C:\Program Files\CorsixTH\Lua\world.lua:1103: in function 'onTick'
	C:\Program Files\CorsixTH\Lua\app.lua:852: in function 'dispatch'
	C:\Program Files\CorsixTH\Lua\app.lua:753: in function <C:\Program Files\CorsixTH\Lua\app.lua:748>
Error in buttonup handler: 
C:\Program Files\CorsixTH\Lua\humanoid_actions\walk.lua:60: attempt to call local 'timer_function' (a nil value)
stack traceback:
	C:\Program Files\CorsixTH\Lua\humanoid_actions\walk.lua: in function 'on_interrupt'
	C:\Program Files\CorsixTH\Lua\entities\humanoid.lua:635: in function 'setNextAction'
	C:\Program Files\CorsixTH\Lua\dialogs\staff_dialog.lua:313: in function 'callback'
	C:\Program Files\CorsixTH\Lua\window.lua:645: in function 'handleClick'
	C:\Program Files\CorsixTH\Lua\window.lua:1406: in function 'onMouseUp'
	C:\Program Files\CorsixTH\Lua\dialogs\staff_dialog.lua:269: in function 'onMouseUp'
	C:\Program Files\CorsixTH\Lua\window.lua:1390: in function 'onMouseUp'
	C:\Program Files\CorsixTH\Lua\ui.lua:735: in function 'dispatch'
	C:\Program Files\CorsixTH\Lua\app.lua:753: in function <C:\Program Files\CorsixTH\Lua\app.lua:748>

**Comment by MarkL1961** [comment] 2015-01-29 11:13
It looks like you had a lot of errors, the first one suggests you were trying to place a staff member somewhere you shouldn't "Map co-ordinates out of bounds".  I have seen that in another issue in recent weeks. 
Can you recall what you were doing when that first error happened?

**Comment by mrbenjamin1** [comment] 2015-01-29 15:26
after looking at the error again (it has happened a number of times now) it seems that if you set a room to be repaired and then it blows up before the janitor gets to fix it. the Icon still remains over the top of the machine saying it due to be fixed and the janitor still heads to fix the room and get stuck when trying to enter a broken room.

**Comment by MarkL1961** [comment] 2015-01-29 19:01
I think this is a duplicate of issue #508

**Closed** 2015-01-29 20:20 UTC
Labels: duplicate
