### ISSUE TITLE
Patient being in treatment can't die nor be cured

### ISSUE THREAD

**Issue by vyguera** [CorsixTH/CorsixTH#1268] opened 2017-10-27 18:23 UTC
#### Describe the issue
My issue can be 2 issues indeed:
When a patient triggers its death while entering or being at its treatment room (at least in psychiatry) he/she can't die nor be cured. The doctor doesn't treat the patient and walks around the room as if he were waiting for a new patient but the patient doesnt leave the room.

This makes the doctor get tired till he reaches 100% of fatigue. Even though he doesn't leave the room.

So, the 2 issues I observe are:
1- Treatment can't finish if patient triggers death while entering the room and/or being lied on the sofa.
2 - Doctors (and maybe nurses too) can't finish the treatment and walks around the room if they reaches its fatigue 100% limit (I think it also happens when the limit is at the usual 60%)

#### Steps to Reproduce
1. *Load save game attached to this ticket*

2. Doctor at psychiatry is already walking around the room and the patient lied on the sofa

3. Wait for a minute so the hour of death arrives to the patient.

4. The patient can't die nor be treated. Also the doctor can't leave the room as he reaches its fatigue limit.

#### Save Game
https://app.box.com/s/sfi5ef63ahiod7fxpy2j3d0ks3v50rny

#### Expected Behavior
Ttreatment must always finish.
Although if the patient's hour of death arrives I don't know if he/she should always die or might be cured
If Doctor gets tired while treating he also must always finish the treatment and then leave the room.

#### System Information
CorsixTH Version: 0.60

Operating System: Windows 7, 64bits

Theme Hospital Version: CD

#### Gamelog.txt
https://app.box.com/s/cuqfzkr46c6mm4hnq8632e5pttgz1oei

### Additional Info
![patient dead while in treatment](https://user-images.githubusercontent.com/1656373/32119112-7d5acad2-bb54-11e7-901e-47c368eef95e.png)

**Comment by lewri** [comment] 2017-10-27 22:02
I wonder if this issue could be caused by the savegame change. But nonetheless I tried to dig around. 
The log doesn't seem to provide anything useful so I'll glaze over that.

Are you able to provide a save before this step (i.e. before our dying patient entered the room)?

When I clicked onto our patient he seemed to have the 'guess at cure' and 'queue status' buttons despite being in the room. I was able to send him home, which resulted in an error.

> Warning: goHome called when the patient is already going home
> Savegame version is 111 (v0.60), originally it was 111 (v0.60)
> Savegame version is 111 (v0.60), originally it was 111 (v0.60)
> Savegame version is 111 (v0.60), originally it was 111 (v0.60)
> Savegame version is 111 (v0.60), originally it was 111 (v0.60)
> Error in timer handler: 
> C:\Program Files\CorsixTH\Lua\world.lua:1804: attempt to index a nil value (local 'humanoid')
> stack traceback:
> 	C:\Program Files\CorsixTH\Lua\world.lua:1804: in method 'findObjectNear'
> 	C:\Program Files\CorsixTH\Lua\rooms\psych.lua:134: in method 'commandEnteringPatient'
> 	C:\Program Files\CorsixTH\Lua\room.lua:400: in method 'onHumanoidEnter'
> 	C:\Program Files\CorsixTH\Lua\humanoid_actions\walk.lua:356: in field 'on_next_tile_set'
> 	C:\Program Files\CorsixTH\Lua\humanoid_actions\walk.lua:150: in function <C:\Program Files\CorsixTH\Lua\humanoid_actions\walk.lua:137>
> 	(...tail calls...)
> 	C:\Program Files\CorsixTH\Lua\entity.lua:219: in method 'tick'
> 	C:\Program Files\CorsixTH\Lua\world.lua:1075: in method 'onTick'
> 	C:\Program Files\CorsixTH\Lua\app.lua:1000: in function <C:\Program Files\CorsixTH\Lua\app.lua:997>
> 	(...tail calls...)
> 	C:\Program Files\CorsixTH\Lua\app.lua:901: in function <C:\Program Files\CorsixTH\Lua\app.lua:896>
> Recovering from error in timer handler...

If I am guessing correctly, @TheCycoONE will need to confirm, the 'goHome' action is somehow linked to a patient dying. I don't know the code side but it looks like when our patient "died" it executed a goHome command that was either: already called -or- never completed.


Additionally, this is what our patient's current action was while being stuck:
![couchhang](https://user-images.githubusercontent.com/20030128/32126781-6b9146b2-bb6a-11e7-8f19-49cafedbd0da.png)

**Comment by TheCycoONE** [comment] 2017-10-28 00:51
This code has also changed quite a bit since 0.60
 We may have already fixed this

**Comment by vyguera** [comment] 2017-10-28 07:31
You are right, the issue is caused by a previous bug:
The doctor is already tired over is limit fatigue and is not treating the patient, so the patient results in death after a while. Even though I cant say why the doctor didn't go to the staff room once he got tired. I guess he got tired at the same time he was treating a patient. There is a shelving in the room. Doctor might got tired while using it.
I have uploaded my savegame to one several minutes before-:
https://app.box.com/s/q133ku4byrmcp80njy8w21npf47crsq0

The new screenshot:
![doctor tired results in patient death](https://user-images.githubusercontent.com/1656373/32132277-5dae4372-bbc1-11e7-8d6b-c8dc86ba2ee1.PNG)

**Comment by vyguera** [comment] 2017-10-28 07:50
Ok this savegame is even better:
https://app.box.com/s/jnnyeh8vn1mr66ylsy8960v0c5warpv3

Just a minute after the doctor enters the room. Is the one leaving from reception following the road and coming to psiquiatry. He is not tired at all, and gets tired while the patient enters but I've loaded the gamesave several times and this bug is not happening

**Comment by lewri** [comment] 2017-10-28 09:20
It could be a carryover bug from Beta 8 too. I dug through the old issues and found comment that bugs present in a savegame aren't automatically fixed when loading a new version of CorsixTH. Because we have a savegame before the bug happened... the bug shouldn't ever happen in a new version. If that makes sense.

**Comment by vyguera** [comment] 2017-10-28 13:02
I'm not quite sure if I understood you. Do you mean you couldn't debug the error in a new version?

Anyway, do you need anything else of me?

**Comment by mugmuggy** [comment] 2019-07-22 06:59
This I believe is related to #1104 just the circumstances could be different to the room editing/crashing that one is focused on. I believe what you maybe seeing with this one, and its root cause is covered  in #1104, is when a doctor goes 'idle' and is available to answer another call.

They can start to leave, and a patient can still enter the room. At this point another doctor has become idle and looks for work and steals the job, this results in the leaving doctor meandering, however as the patient has entered, they complete the actions they had and the doctor does nothing.

**Comment by mugmuggy** [comment] 2020-05-19 07:31
If this was 1104 or was related to the leaving doctor scenario, these issues should be fixed

**Closed by mugmuggy** 2020-05-19 07:31 UTC
