### ISSUE TITLE
On graph, labels should not fall below the bottom of the chart. They should be coloured to match lines.

### ISSUE THREAD

**Issue by altiereslima** [CorsixTH/CorsixTH#1008] opened 2016-03-24 12:27 UTC
Steps to Reproduce
1. Open Status Menu

Or
1. Open Charts Menu
2. See screenshots

System Information
CorsixTH Version: 0.50

Operating System: Windows 7

Theme Hospital Version: CD

Additional Info

Cursixth
![cursixth charts](https://cloud.githubusercontent.com/assets/18044879/14016980/91df2516-f1a2-11e5-8a27-569e264fff72.png)
![cursixth](https://cloud.githubusercontent.com/assets/18044879/14016981/91e15368-f1a2-11e5-87fa-6154528dcde4.png)

DOSBox
![otiginal charts](https://cloud.githubusercontent.com/assets/18044879/14016982/91e2eda4-f1a2-11e5-8a17-c7f8f5b915ff.png)
![otiginal status](https://cloud.githubusercontent.com/assets/18044879/14016983/91ed45ec-f1a2-11e5-83da-62fe8ffe158d.png)

**Comment by TheCycoONE** [comment] 2016-03-24 13:26
We haven't implemented the AI hospitals yet which is why you see the population pie chart in one case but not the other.

Lets focus this issue on the position and color of the legend in the graph.

**Comment by lewri** [comment] 2020-06-09 14:24
Partly resolved. Rest is a duplicate of #967

**Closed** 2020-06-09 18:10 UTC
Labels: Component-Graphical
