### ISSUE TITLE
I had an error (patients got stuck and can't pass through)

### ISSUE THREAD

**Issue by kekk** [CorsixTH/CorsixTH#682] opened 2015-02-08 08:47 UTC
Screenshots from the console and the game attached

![1a](https://cloud.githubusercontent.com/assets/4378903/6095956/4d521132-af6e-11e4-9844-83186aa275c0.jpg)
![2b](https://cloud.githubusercontent.com/assets/4378903/6095957/544a684a-af6e-11e4-8bab-d463c0028ec9.jpg)

**Comment by SimplyRyan** [comment] 2015-02-15 12:07
#666 &  #682 look to be the same issue.

**Comment by lewri** [comment] 2020-06-09 14:19
Duplicate of #666

**Comment by mugmuggy** [comment] 2020-07-12 08:58
This issue looks more like the its related to the room crashing, and the walk into room incorrectly being a must_happen. The walk after queue action is not interrrupted but starts instead, that issue has been fixed (I hope) and the other time this would have occured due to swing doors ticking is guarded against.

**Closed by mugmuggy** 2020-07-12 08:58 UTC
