### ISSUE TITLE
Mini window 'view person at work' doesn't work anymore

### ISSUE THREAD

**Issue by bobcanthelpyou** [CorsixTH/CorsixTH#846] opened 2015-08-01 09:52 UTC
Selecting a staff member doesn't show them working in the staff info dialog, anymore 
It shows a different place, also there is an artifact under the dialog.

![bildschirmfoto von 2015-08-01 11 25 11](https://cloud.githubusercontent.com/assets/4523264/9021405/f08b7c3e-3840-11e5-956e-963bbbf07b03.png)

And the 'view person at work' window within the staff management is black

![bildschirmfoto von 2015-08-01 11 29 22](https://cloud.githubusercontent.com/assets/4523264/9021406/f4e72dbe-3840-11e5-918d-df8a62ba1b1f.png)

CorsixTH trunk ee23df1fb7ae5a0842854f3aea7a2cddb8e3a711 / Lua 5.1 / Debian Jessie 64 bit & 32 bit

**Comment by TheCycoONE** [comment] 2015-08-03 01:38
I cannot reproduce myself.

You say in your ticket "anymore", could you find the commit that causes the problem for you? (http://git-scm.com/docs/git-bisect)

**Comment by Alberth289346** [comment] 2015-08-03 05:54
Reproduction: windowed mode, 1600x900 (in case that matters), bisecting commit: d525af01e95aab6a92059882e61c1ad263d4a308 (Always use zoom texture for map), build program from scratch, play single scenario "Finisham", buy nurse, click on nurse. The round area is just see-through, and not displaying the nurse.

I don't get the area below the window.

**Comment by TheCycoONE** [comment] 2015-08-03 16:46
Alright, I can reproduce with opengl, thanks.

**Comment by TheCycoONE** [comment] 2015-08-03 17:21
It seems that without that commit there is an issue with the placement of the previews when using full screen at non-native resolution in all rendering back ends, but at native resolution (or windowed mode) the placement is right in all renderers. With that commit there is a problem with the placement of all previews in only opengl. The software renderer has severe rendering problems across the board but the placement of the preview is right.

**Comment by TheCycoONE** [comment] 2015-08-03 17:47
Determined that this is an SDL bug that will be fixed with SDL 2.0.4: https://bugzilla.libsdl.org/show_bug.cgi?id=2700

**Closed** 2015-08-04 06:19 UTC
Labels: Component-OpenGL, State-Upstream, Type-Regression
