### ISSUE TITLE
Stuck patient

### ISSUE THREAD

**Issue by TinusVL** [CorsixTH/CorsixTH#193] opened 2014-02-20 18:45 UTC
A patient got stuck in front of a door of a GP's office.

I tried sending the patient home, reloading the save file below, editing the room, adding and removing staff to the room, but she didn't move.

A save where the patient is already stuck: 
https://www.dropbox.com/s/wtdu43pai2mbuy6/T7.sav
(She's in the GP's office near the entrance.)

**Comment by lewri** [comment] 2020-06-09 13:46
Duplicate of #76

**Comment by lewri** [comment] 2020-07-23 10:34
@mugmuggy you posted in #76 the issue was fixed there. As this appears to be a duplicate are you happy to close?

**Comment by mugmuggy** [comment] 2020-07-23 22:00
I'd be in favour of just closing as we can't progress it now. No save, no log, its age.

**Closed by mugmuggy** 2020-07-23 22:00 UTC
Labels: S:Investigating
