### ISSUE TITLE
X-Ray room blocked after request repairing for machine

### ISSUE THREAD

**Issue by carlosrd** [CorsixTH/CorsixTH#1557] opened 2019-08-10 18:21 UTC
#### Describe the issue
After and earthquake, I reviewed all hospital machine to check status and request a repair from handymen. After request repair several times for X-Ray room, two handymen at same time try to repair the machine, but both get stucked and X-Ray is not repaired. 

In fact, the room is totally blocked since no handymen is able to repair the machine and patients must wait until machine is repaired

#### Steps to Reproduce
1. Wait for an earthquake
2. Review your machines by clicking in one and right-click on the name to change rapidly to the next machine. While visiting in each machine, click on "Request repair"
3. Wait until all machines gets repaired
4. X-Ray room is not repaired and blocked while two handymen trying to repairing it

You can check this [saved game](https://github.com/CorsixTH/CorsixTH/files/3489191/XRAY_ERROR.zip) to see the issue. There are two handymen stucked in the X-Ray room trying to repair the machine with no success

- You can move them outside the room but no one will return to repair the machine.
- If you try to fire them, then they will get stucked in the room without leaving the hospital
- Trying to make modifications in the room ( ? button to modify rooms) neither doesn't force handymen to leave the room 

#### Expected Behavior
X-Ray room is repaired and not blocked

#### System Information
**CorsixTH Version:** *0.63*

**Operating System:** *Windows 7 Home Premium SP1*

**Theme Hospital Version:** *CD*

### Additional Info
![x-ray](https://user-images.githubusercontent.com/2896275/62825429-adba9a00-bbab-11e9-9c06-c7eed9524156.png)

**Comment by mugmuggy** [comment] 2019-08-10 23:07
Doctor in inflation room has the door reserved, so this is a dupe of #1087. Moving the doctor from inflation into that room will allow the room to recover.

**Closed by mugmuggy** 2019-08-10 23:07 UTC
