### ISSUE TITLE
An hummanoid cannot leave the room

### ISSUE THREAD

**Issue by Cyram** [CorsixTH/CorsixTH#986] opened 2016-02-20 13:17 UTC
And... the last level is all bug because the room is Cardiology. Im tried to send the patiens to another room of cardiology and reduce the number in the wait list, but the sistem always send to the bug room (doctors and patiens). (sorry, my english is awful).

I was print an instanscreen for you of my error log.

![errorthemehospitalcardiologia](https://cloud.githubusercontent.com/assets/17355102/13196883/b6795d2c-d7dc-11e5-95dd-edc2de706129.jpg)

**Comment by wolfy1339** [comment] 2016-02-20 13:30
Do you have a save game?
Also, what version of CorsixTH and Windows are you running?

**Comment by Cyram** [comment] 2016-02-20 13:34
Yes, I have a save game, but I not be aware of until the game is very avanced. About the version, I have the last one. An message in the game in the menu screen send me to the page of Corsix to download it. Version of Windows: 7

Thx ^^

**Comment by TheCycoONE** [comment] 2016-04-13 19:09
Transcription of error:
```
Running: The timer handler.
...
CorsixTH/Lua/entities/humanoid.lua:662: Can only finish current action
stack traceback:
    [C]: In function 'assert'
    CorsixTH/Lua/entities/humanoid.lua:662: in method 'finishAction'
    CorsixTH/Lua/rooms/cardiogram.lua:97: in field 'after_use'
    CorsixTH/Lua/humanoid_actions/multi_use_object.lua:264: in local 'timer_function'
    ...

Warning: No event handler for timer
Warning: Humanoid leaving a room that they are not in
...
```

**Comment by TheCycoONE** [comment] 2016-04-13 19:13
Duplicate of #500

**Closed by TheCycoONE** 2016-04-13 19:13 UTC
Labels: Type-Game Error
