### ISSUE TITLE
Font Error [RUS]

### ISSUE THREAD

**Issue by ButCheR-PRO** [CorsixTH/CorsixTH#1213] opened 2017-04-17 04:31 UTC
У меня Windows 10 x64.
Установил игру, вместе с CorsixTH, английская версия. Скачал последнюю версию CorsixTH (0.60), накатил поверх установленной, но нет русского языка в списке. Как выяснилось, оно не может найти шрифт ARIALUNI.TTF в папке Windows/fonts. Этому свидетельствует строка в файле "CorsixTH\Lua\graphics.lua":

`font_file = windir .. pathsep .. "Fonts" .. pathsep .. "ARIALUNI.TTF"`

Запускаю CorsixTH, далее захожу в Settings -> Folders -> Fonts (тут просто напротив кнопку нажимаю), открылось окно в котором следую по пути (путь для windows) "C:/Windows/Fonts/Arial.ttf" - нажимаю два раза на Arial.ttf. Что получилось - я выбрал шрифт которым будет отображаться текст в игре. Перезагружаю игру и в этот раз в настройках Settings -> Game Language -> отображается больше языков, в том числе и русский. Теперь все нормально, а то долго не мог разобраться в чем причина.

Можно еще отредактировать файл "CorsixTH\Lua\config_finder.lua"
и вместо строки

`unicode_font = nil`

написать

`unicode_font = [[c:\Windows\Fonts\arial.ttf]]`

Ну или просто в папке Windows\Fonts\ создать копию файла arial.ttf и переименовать её в arialuni.ttf (мало ли еще какие игры и приложения начнут его запрашивать)

**Comment by TheCycoONE** [comment] 2017-04-17 12:19
Google Translate:
I have Windows 10 x64.
Installed the game, along with CorsixTH, the English version. I downloaded the latest version of CorsixTH (0.60), rolled over the installed one, but there is no Russian language in the list. As it turned out, it can not find the ARIALUNI.TTF font in the Windows / fonts folder. This is evidenced by the line in the file "CorsixTH \ Lua \ graphics.lua":

Font_file = windir .. pathsep .. "Fonts" .. pathsep .. "ARIALUNI.TTF"

I run CorsixTH, then I go to Settings -> Folders -> Fonts (I just click the button opposite), I opened the window where I follow the path (the path for windows) "C: /Windows/Fonts/Arial.ttf" - I double-click on Arial.ttf. What happened - I chose a font that will display the text in the game. Reboot the game and this time in Settings -> Game Language -> more languages ​​are displayed, including Russian. Now everything is fine, but for a long time I could not figure out what the reason was.

You can also edit the file "CorsixTH \ Lua \ config_finder.lua"
And instead of the string

Unicode_font = nil

Write

Unicode_font = [[c: \ Windows \ Fonts \ arial.ttf]]

Well, or just in the Windows \ Fonts \ folder, create a copy of the arial.ttf file and rename it to arialuni.ttf (how many other games and applications will start asking for it)

**Comment by TheCycoONE** [comment] 2017-04-17 12:22
So @ButCheR-PRO what exactly is it you would like to see changed? Some sort of automatic font detection, or a message indicating why you can't see some language options?

**Comment by shizeeg** [comment] 2017-04-19 15:58
an issue report in Russian? That's savage. =D I don't see any problem here tbh. Arialuni.ttf is a standard Windows font & should be integrated in Windows https://en.wikipedia.org/wiki/Arial_Unicode_MS
It's not a surprise to me CorsixTH relies on that as well as many other games & software packages (CS:GO & Adobe Photoshop for ex.) do.

**Comment by MarkL1961** [comment] 2017-04-19 18:53
I have windows 10 64 bit and the list of fonts seen in-game
![in-game fonts](https://cloud.githubusercontent.com/assets/4965487/25196638/255f48aa-2539-11e7-9a1b-6b90c963af6d.png)
does not match the list in the windows font folder
![fonts](https://cloud.githubusercontent.com/assets/4965487/25196644/28db0c1c-2539-11e7-9d69-416fd1bd6132.jpg)
If the game is looking for `  Font_file = windir .. pathsep .. "Fonts" .. pathsep .. "ARIALUNI.TTF"  ` as suggested then this will be why it cannot be found. So I can see the problem - why should the player have to re-name his/her font file in windows or make  a copy.

Is this something new with windows 10?

**Comment by MarkL1961** [comment] 2017-04-19 18:59
From the above screenshot I can now see the one I want is the tenth in the list, which I could not see in game (the above screen is slightly larger).   However I cannot see Russian as an option in game.

**Comment by shizeeg** [comment] 2017-04-19 21:29
@MarkL1961 Russian is on your screenshot actually. It's "Русский" (written in Cyrillic)

**Comment by MarkL1961** [comment] 2017-04-19 22:09
Thanks, but where does that name come from?
In the language file I see `  Language("Ð ÑƒÑÑÐºÐ¸Ð¹", "Russian", "ru", "rus")  `
although I suppose if I spoke or read Russian I would know what it meant....
I also looked in the config file and didn't  see anything different there either. `  Russian               / ru / rus  `

I am just trying to understand the reasons behind the issue here, although the problem maybe in trying to find the correct font to use

Now I have selected this the config is `  language = [[Русский]]  `  which is not shown in the current help text in the config either

**Comment by shizeeg** [comment] 2017-04-20 10:37
@MarkL1961 Language("Ð ÑƒÑ�Ñ�ÐºÐ¸Ð¹", "Russian", "ru", "rus") it's a UTF-8 encoded string in CP1252 encoding I suppose.
In my browser I see 
```lua
22: Language("Русский", "Russian", "ru", "rus")
```
here: https://github.com/CorsixTH/CorsixTH/blob/master/CorsixTH/Lua/languages/russian.lua#L22

**Comment by MarkL1961** [comment] 2017-04-20 18:42
I can now see what I did wrong last night, I opened the language file and by default my pc used a lua editor rather than notepad.  (duh)
I like your fallback idea
I also think the config.txt needs to be updated to display this additional name so you can see what the available languages are, and the user could copy the relevant one including the square brackets if they chose to e.g.
`  [[Русский]]   Russian / ru / rus  `

**Comment by TheCycoONE** [comment] 2017-04-24 00:45
The way CorsixTH uses and exposes fonts is lower level than most people are use to and are comfortable with. Normally a program would query the operating system e.g. fontconfig on linux or windows.h on windows for a list of font faces to show the user. There can be multiple files for multiple styles of the same font face which is part of why the lists don't match. It would be a good task for someone new to CorsixTH development.

**Comment by FlameArtLab** [comment] 2018-01-26 18:26
Arial looks very bad. I think, best font for russian is Gothic.ttf (in windows standart packet)

**Comment by 1vanK** [comment] 2018-07-03 14:30
I have no Gothic.ttf in my windows 10

**Comment by ARGAMX** [comment] 2021-05-30 13:00
Just Installed the CorsixTH 0.64 on MacOS X.

The Localization page says that game have Russian translate. But in fact in doesn't it out of box, because there no Russian Language to select in game Settings.

https://github.com/CorsixTH/CorsixTH/wiki/Localization

You can install game and check it.

Looks like an issue.

**Comment by lewri** [comment] 2021-05-30 13:21
@ARGAMX this is intended behaviour. You need to select a font to be able to use some languages, as we only use the original game font. Though an improvement is suggested on #1901

**Comment by TheCycoONE** [comment] 2021-05-30 14:04
Closing in favor of #1901

**Closed by TheCycoONE** 2021-05-30 14:04 UTC
Labels: P4 Low, S:Help wanted, T:UI
