### ISSUE TITLE
Crash:  CorsixTH\Lua\humanoid_actions\walk.lua:282: assertion failed!

### ISSUE THREAD

**Issue by KeeperSt** [CorsixTH/CorsixTH#1250] opened 2017-09-22 12:41 UTC
#### Describe the issue
---------------------------------------------------------------

This window will display useful information if an error occurs.

---------------------------------------------------------------

Checking for CorsixTH updates...
You are running the latest version of CorsixTH.
An error has occurred!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The timer handler.
A stack trace is included below, and the handler has been disconnected.
...hivos de programa\CorsixTH\Lua\humanoid_actions\walk.lua:282: assertion failed!
stack traceback:
        [C]: in function 'assert'
        ...hivos de programa\CorsixTH\Lua\humanoid_actions\walk.lua:282: in function <...hivos de programa\CorsixTH\Lua\humanoid_actions\walk.lua:210>
        (...tail calls...)
        ...hivos de programa\CorsixTH\Lua\humanoid_actions\walk.lua:188: in local 'timer_function'
        F:\Archivos de programa\CorsixTH\Lua\entity.lua:219: in method 'tick'
        F:\Archivos de programa\CorsixTH\Lua\world.lua:1075: in method 'onTick'
        F:\Archivos de programa\CorsixTH\Lua\app.lua:1000: in function <F:\Archivos de programa\CorsixTH\Lua\app.lua:997>
        (...tail calls...)
        F:\Archivos de programa\CorsixTH\Lua\app.lua:901: in function <F:\Archivos de programa\CorsixTH\Lua\app.lua:896>

Warning: No event handler for timer

#### Steps to Reproduce
  I place a radiator on the outer wall of any room.  Then, I build another room in front of the radiator, and I place the door in front of the radiator.  Finally, I put a doctor into the built room, and in a few seconds it crashes.

#### Save Game
https://www.dropbox.com/s/zpx1r60u063wjxw/keeper6.sav?dl=0

#### System Information
**CorsixTH Version:**0.60

**Operating System:**Windows 10 64 bits

**Theme Hospital Version:**CD

### Additional Info
![med general18](https://user-images.githubusercontent.com/31771827/30744268-93e19cfa-9fa1-11e7-8f34-d31f185385c3.jpg)

**Comment by TheCycoONE** [comment] 2017-09-23 01:13
Duplicate of #221

**Closed by TheCycoONE** 2017-09-23 01:13 UTC
