### ISSUE TITLE
Bug Report - Game freezing

### ISSUE THREAD

**Issue by badabingbambini** [CorsixTH/CorsixTH#714] opened 2015-03-04 20:22 UTC
What steps will reproduce the problem?
1.Move an existing room (found it with staff room)
2. Scroll to edge of screen until menu bar appears (noticed it by scrolling to top-left over "File")

What is the expected output? What do you see instead?
Game freezes.  When I come out of the game, DOS screen says "Warning: No event handler for motion"

What version of CorsixTH are you using (e.g. "0.30", "4c66e39985")?
0.40

What operating system / compile settings are you using?
Windows 7 Ultimate with Service Pack 1

What level was this on (e.g. "Demo level", "Full game level 12")?
Full Game level 8 (Full game downloaded from Origin)

Save file available at https://www.dropbox.com/s/14uozyfai8sq73y/Autosave4.sav?dl=0

**Comment by Alberth289346** [comment] 2015-06-23 19:48
I just tried, and cannot reproduce it in current trunk version, commit: 41646aa but  maybe I tested it wrong.

**Comment by bobcanthelpyou** [comment] 2015-07-05 11:15
@badabingbambini could you reproduce the game freeze with the v0.50 beta release?

**Comment by TheCycoONE** [comment] 2015-07-17 00:17
I can reproduce this in the latest trunk. It is not fixed by #806 but it is a related issue.

**Comment by TheCycoONE** [comment] 2015-07-17 00:19
To reproduce the room needs to be dragged off the top left corner of the map.

**Comment by TheCycoONE** [comment] 2015-07-17 02:13
Added fix for this to #806

**Comment by Alberth289346** [comment] 2015-07-17 04:23
fixed in commit: de27e4d

**Closed by Alberth289346** 2015-07-17 04:23 UTC
Labels: Reported-0.40
