### ISSUE TITLE
Another unknown game crash

### ISSUE THREAD

**Issue by ledowong** [CorsixTH/CorsixTH#659] opened 2015-02-02 16:22 UTC
save:
https://drive.google.com/file/d/0B05D0Cat5usfcUZvRmRoTzVON2c/view?usp=sharing

no trace log in console, Windows level crash.

**Comment by MarkL1961** [comment] 2015-02-02 19:25
At what point did it crash?

**Comment by ledowong** [comment] 2015-02-03 01:25
wow, i load the save again and no crash. After a few more test, i think i found the reason...

originally, the game crash when the woman open the door into pharmacy. (but not due to this reason)
if you load the save, and do NOTHING, it crash.
if you load the game, and close the Patient popup windows (top right corner), it won't crash...

what i think is, if a patient popup windows opened, and that patient leaving the map... it crash.

here is the video:
http://youtu.be/EyrM68vvcOk

**Comment by TheCycoONE** [comment] 2015-02-03 02:02
Duplicate of #124

**Closed by TheCycoONE** 2015-02-03 02:02 UTC
Labels: duplicate
